---
permalink: sm-storage/access-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access volumes 
summary: 'Ein Zugriffs-Volume ist ein werkseitig konfiguriertes Volume auf dem Storage-Array, das über die Host-I/O-Verbindung für die Kommunikation mit dem Storage-Array und dem Host verwendet wird. Das Zugriffsvolume erfordert eine LUN (Logical Unit Number).' 
---
= Zugriff auf Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Zugriffs-Volume ist ein werkseitig konfiguriertes Volume auf dem Storage-Array, das über die Host-I/O-Verbindung für die Kommunikation mit dem Storage-Array und dem Host verwendet wird. Das Zugriffsvolume erfordert eine LUN (Logical Unit Number).

Das Access Volume wird in der folgenden Instanz verwendet:

* *In-Band-Management* -- das Zugriffsvolume wird für eine in-Band-Verbindung zur Verwaltung des Speicher-Arrays verwendet. Dies kann nur geschehen, wenn Sie das Storage Array über die Befehlszeilenschnittstelle (CLI) verwalten.
+
[NOTE]
====
Für E4000-, EF600-/EF600C- oder EF300/EF300C-Speichersysteme ist das bandinterne Management mit dem Access Volume nicht verfügbar.

====


Beim ersten Zuweisen eines Volumes zu einem Host wird automatisch ein Zugriffsvolume erstellt. Wenn Sie beispielsweise Volume_1 und Volume_2 einem Host zuweisen, werden beim Anzeigen der Ergebnisse dieser Zuweisung drei Volumes angezeigt (Volume_1, Volume_2 und Access).

Wenn Sie nicht automatisch Hosts erstellen oder ein Speicher-Array in-Band mit der CLI verwalten, brauchen Sie nicht das Zugriffs-Volume, und Sie können die LUN freigeben, indem Sie das Zugriffs-Volume löschen. Durch diese Aktion werden die Zuweisung von Volume zu LUN sowie alle bandinternen Managementverbindungen zum Host entfernt.
