---
permalink: sm-storage/activate-or-suspend-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot schedule 
summary: Sie können die geplante Sammlung von Snapshot-Images vorübergehend unterbrechen, wenn Sie Speicherplatz sparen müssen. Diese Methode ist effizienter als das Löschen und das spätere Erstellen des Snapshot-Zeitplans. 
---
= Aktivieren und Aussetzen eines Snapshot-Zeitplans im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die geplante Sammlung von Snapshot-Images vorübergehend unterbrechen, wenn Sie Speicherplatz sparen müssen. Diese Methode ist effizienter als das Löschen und das spätere Erstellen des Snapshot-Zeitplans.

.Über diese Aufgabe
Der Status des Snapshot-Zeitplans bleibt ausgesetzt, bis Sie die Option *Aktivieren* verwenden, um die geplanten Snapshot-Aktivitäten wieder aufzunehmen.

.Schritte
. Wählen Sie im linken Bereich Menü:Storage[Snapshots].
. Falls sie noch nicht angezeigt wird, klicken Sie auf die Registerkarte *Snapshot Schedules*.
+
Die Zeitpläne sind auf der Seite aufgeführt.

. Wählen Sie einen aktiven Snapshot-Zeitplan aus, den Sie aussetzen möchten, und klicken Sie dann auf *Aktivieren/Deaktivieren*.
+
Der Status der Spalte Status ändert sich in *suspended*, und der Snapshot-Zeitplan stoppt die Sammlung aller Snapshot-Bilder.

. Um das Sammeln von Snapshot-Bildern fortzusetzen, wählen Sie den suspendierten Snapshot-Zeitplan aus, den Sie fortsetzen möchten, und klicken Sie dann auf *Aktivieren / anhalten*.
+
Der Status der Spalte Status ändert sich in *aktiv*.


