---
permalink: sm-storage/automatic-versus-manual-host-creation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, automatic, manual, host, 
summary: Das Erstellen eines Hosts ist einer der Schritte, die erforderlich sind, damit das Storage-Array wissen kann, an welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen. Sie können einen Host automatisch oder manuell erstellen. 
---
= Automatische statt manueller Host-Erstellung
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Erstellen eines Hosts ist einer der Schritte, die erforderlich sind, damit das Storage-Array wissen kann, an welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen. Sie können einen Host automatisch oder manuell erstellen.



== Automatische Erstellung

Die automatische Host-Erstellung für SCSI-basierte Hosts (nicht NVMe-of) wird vom Host Context Agent (HCA) initiiert. Die HCA ist ein Dienstprogramm, das Sie auf jedem Host installieren können, der mit dem Speicher-Array verbunden ist. Jeder Host, auf dem die HCA installiert ist, sendet seine Konfigurationsinformationen über den I/O-Pfad an die Speicher-Array-Controller. Basierend auf den Host-Informationen erstellen die Controller automatisch den Host und die zugehörigen Host-Ports und legen den Host-Typ fest. Bei Bedarf können Sie mit System Manager alle zusätzlichen Änderungen an der Hostkonfiguration vornehmen.

Nachdem die HCA die automatische Erkennung durchgeführt hat, wird der Host automatisch auf der Seite Hosts mit den folgenden Attributen angezeigt:

* Der Hostname, der vom Systemnamen des Hosts abgeleitet wurde.
* Die dem Host zugeordneten Host-Identifikator-Ports.
* Der Host-Betriebssystem-Typ des Hosts.


Hosts werden als eigenständige Hosts erstellt. Das HCA erstellt oder fügt nicht automatisch zu Host-Clustern hinzu.



== Manuelle Erstellung

Sie können einen Host aus einem der folgenden Gründe manuell erstellen:

. Sie haben sich entschieden, das HCA-Dienstprogramm nicht auf Ihren Hosts zu installieren.
. Sie möchten sicherstellen, dass die von den Speicher-Array-Controllern erkannten Host-Port-IDs den Hosts ordnungsgemäß zugeordnet sind.


Bei der manuellen Hosterstellung verknüpfen Sie Host-Port-IDs, indem Sie sie aus einer Liste auswählen oder manuell eingeben. Nachdem Sie einen Host erstellt haben, können Sie ihm Volumes zuweisen oder einem Host Cluster hinzufügen, wenn Sie den Zugriff auf Volumes freigeben möchten.
