---
permalink: sm-storage/cancel-snapshot-image-rollback.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cancel, snapshot, image, rollback 
summary: 'Sie können ein aktives Rollback abbrechen, das gerade läuft (Daten aktiv kopieren), ein ausstehendes Rollback (in einer Warteschlange, in der auf den Start warten) oder ein Rollback, das aufgrund eines Fehlers angehalten wurde.' 
---
= Abbrechen des Zurücksetzvorgangs von Snapshot-Bildern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein aktives Rollback abbrechen, das gerade läuft (Daten aktiv kopieren), ein ausstehendes Rollback (in einer Warteschlange, in der auf den Start warten) oder ein Rollback, das aufgrund eines Fehlers angehalten wurde.

Wenn Sie einen laufenden Rollback-Vorgang abbrechen, wird das Basis-Volume in einen unbrauchbaren Zustand zurückgesetzt und wird als fehlgeschlagen angezeigt. Daher sollten Sie einen Rollback-Vorgang nur dann abbrechen, wenn Recovery-Optionen zur Wiederherstellung des Inhalts des Basis-Volumes vorhanden sind.

[NOTE]
====
Wenn in der Snapshot-Gruppe, auf der sich das Snapshot-Image befindet, ein oder mehrere Snapshot-Images vorhanden sind, die automatisch gelöscht wurden, ist das für den Rollback-Vorgang verwendete Snapshot-Image möglicherweise nicht für künftige Rollbacks verfügbar.

====
.Schritte
. Wählen Sie Menü:Storage[Snapshots].
. Klicken Sie auf die Registerkarte *Snapshot Images*.
. Wählen Sie den aktiven oder unterbrochenen Rollback aus und wählen Sie dann Menü:Rollback[Abbrechen].
+
Das Dialogfeld Rollback bestätigen wird angezeigt.

. Klicken Sie zur Bestätigung auf *Ja*.


System Manager stoppt den Rollback-Vorgang. Das Basis-Volume ist zwar nutzbar, kann aber Daten enthalten, die inkonsistent oder nicht intakt sind.

Nachdem Sie einen Rollback-Vorgang abgebrochen haben, müssen Sie eine der folgenden Aktionen durchführen:

* Initialisieren Sie den Inhalt des Basis-Volume neu.
* Führen Sie einen neuen Rollback-Vorgang durch, um das Basisvolume entweder mit demselben Snapshot-Image wiederherzustellen, das beim Rollback abbrechen verwendet wurde, oder mit einem anderen Snapshot-Image, um den neuen Rollback-Vorgang durchzuführen.

