---
permalink: sm-storage/capacity-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity terms 
summary: Erfahren Sie, welche Kapazitätbedingungen sich auf Ihr Storage Array beziehen. 
---
= Erfahren Sie mehr über die Kapazitätsterminologie in der SANtricity-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, welche Kapazitätbedingungen sich auf Ihr Storage Array beziehen.



== Storage-Objekte

In der folgenden Terminologie werden die verschiedenen Typen von Speicherobjekten beschrieben, die mit Ihrem Speicher-Array interagieren können.

[cols="25h,~"]
|===
| Storage Objekt | Beschreibung 


 a| 
Host
 a| 
Ein Host ist ein Server, der I/O an ein Volume auf einem Storage-Array sendet.



 a| 
LUN
 a| 
Eine Logical Unit Number (LUN) ist die Nummer, die dem Adressraum zugewiesen ist, den ein Host für den Zugriff auf ein Volume verwendet. Das Volume wird dem Host als Kapazität in Form einer LUN präsentiert.

Jeder Host verfügt über seinen eigenen LUN-Adressraum. Daher kann dieselbe LUN von unterschiedlichen Hosts für den Zugriff auf verschiedene Volumes verwendet werden.



 a| 
Spiegelung der Konsistenzgruppe
 a| 
Eine gespiegelte Konsistenzgruppe ist ein Container für ein oder mehrere gespiegelte Paare. Für asynchrone Spiegelungsvorgänge müssen Sie eine Konsistenzgruppe erstellen.



 a| 
Gespiegeltes Volume-Paar
 a| 
Ein gespiegeltes Paar besteht aus zwei Volumes, einem primären Volume und einem sekundären Volume.



 a| 
Pool
 a| 
Ein Pool ist eine Reihe von Laufwerken, die logisch gruppiert sind. Mit einem Pool können Sie ein oder mehrere Volumes erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einem Pool oder einer Volume-Gruppe.)



 a| 
Snapshot Konsistenzgruppe
 a| 
Eine Snapshot Konsistenzgruppe ist eine Sammlung von Volumes, die beim Erstellen eines Snapshot Images als eine Einheit behandelt werden. Jedes dieser Volumes verfügt über ein eigenes Snapshot-Image, jedoch werden alle Bilder zum gleichen Zeitpunkt erstellt.



 a| 
Snapshot-Gruppe
 a| 
Eine Snapshot-Gruppe ist eine Sammlung von Snapshot Images aus einem einzigen Basis-Volume.



 a| 
Snapshot Volume
 a| 
Ein Snapshot-Volume ermöglicht dem Host den Zugriff auf Daten im Snapshot Image. Das Snapshot Volume verfügt über eine eigene reservierte Kapazität, um alle Änderungen am Basis-Volume ohne Beeinträchtigung des ursprünglichen Snapshot Images zu speichern.



 a| 
Datenmenge
 a| 
Ein Volume ist ein Container, in dem Applikationen, Datenbanken und Filesysteme Daten speichern. Dies ist die logische Komponente, die erstellt wird, damit der Host auf den Speicher des Speicherarrays zugreifen kann.



 a| 
Volume-Gruppe
 a| 
Eine Volume-Gruppe ist ein Container für Volumes mit gemeinsamen Merkmalen. Eine Volume-Gruppe verfügt über eine definierte Kapazität und einen RAID-Level. Sie können eine Volume-Gruppe verwenden, um ein oder mehrere Volumes zu erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einer Volume-Gruppe oder aus einem Pool.)

|===


== Storage-Kapazität

In der folgenden Terminologie werden die verschiedenen Kapazitätstypen beschrieben, die auf Ihrem Storage Array verwendet werden.

[cols="25h,~"]
|===
| Kapazitätstyp | Beschreibung 


 a| 
Zugewiesene Kapazität
 a| 
Zugewiesene Kapazität ist die physische Kapazität, die den Laufwerken in einem Pool bzw. einer Volume-Gruppe zugewiesen ist.

Die zugewiesene Kapazität wird zur Erstellung von Volumes und für Kopierdienste genutzt.



 a| 
Freie Kapazität
 a| 
Freie Kapazität ist die in einem Pool oder einer Volume-Gruppe verfügbare Kapazität, der der Volume-Erstellung noch nicht zugewiesen wurde.



 a| 
Pool- oder Volume-Gruppen-Kapazität
 a| 
Pool-, Volume- oder Volume-Gruppenkapazität ist die Kapazität in einem Speicher-Array, das einem Pool oder einer Volume-Gruppe zugewiesen wurde. Diese Kapazität wird verwendet, um Volumes zu erstellen und die verschiedenen Kapazitätsanforderungen von Services-Vorgängen und Storage-Objekten zu warten.



 a| 
Pool – nicht nutzbare Kapazität
 a| 
Die nicht nutzbare Kapazität im Pool ist der Speicherplatz in einem Pool, der aufgrund von nicht übereinstimmenden Laufwerksgrößen nicht verwendet werden kann.



 a| 
Erhaltungskapazität
 a| 
Bei der Konservierung wird die Kapazität (Anzahl der Laufwerke) verwendet, die in einem Pool reserviert ist, um potenzielle Laufwerksausfälle zu unterstützen.



 a| 
Gemeldete Kapazität
 a| 
Die gemeldete Kapazität ist die Kapazität, die dem Host gemeldet wird und vom Host abgerufen werden kann.



 a| 
Reservierte Kapazität
 a| 
Reservierte Kapazität ist die zugewiesene physische Kapazität, die für jeden Kopierdienst- und Storage-Objekt verwendet wird. Er ist nicht direkt vom Host lesbar.



 a| 
SSD Cache
 a| 
SSD Cache ist eine Gruppe von Solid-State Disk (SSD)-Laufwerken, die Sie logisch in Ihrem Storage-Array zusammenfassen. Die SSD Cache Funktion speichert die am häufigsten verwendeten Daten („heiße“ Daten) im Cache auf SSD-Laufwerken mit niedrigerer Latenz und beschleunigt dadurch Applikations-Workloads dynamisch.



 a| 
Nicht zugewiesene Kapazität
 a| 
Nicht zugewiesene Kapazität ist der Speicherplatz in einem Speicher-Array, dem ein Pool oder eine Volume-Gruppe *nicht* zugewiesen wurde.



 a| 
Geschriebene Kapazität
 a| 
Die geschriebene Kapazität ist die Menge an Kapazität, die aus der für Thin Volumes zugewiesenen reservierten Kapazität geschrieben wurde.

|===