---
permalink: sm-storage/change-workload-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, workload, settings 
summary: Sie können den Namen für einen Workload ändern und den zugehörigen Applikationstyp anzeigen. Ändern Sie den Namen eines Workloads, wenn der aktuelle Name nicht mehr aussagekräftig oder anwendbar ist. 
---
= Arbeitslasteinstellungen im SANtricity System Manager ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können den Namen für einen Workload ändern und den zugehörigen Applikationstyp anzeigen. Ändern Sie den Namen eines Workloads, wenn der aktuelle Name nicht mehr aussagekräftig oder anwendbar ist.

.Schritte
. Wählen Sie im linken Bereich Menü:Storage[Volumes].
. Wählen Sie die Registerkarte *Applications and workloads* aus.
+
Die Ansicht „Anwendungen und Workloads“ wird angezeigt.

. Wählen Sie die Arbeitslast aus, die Sie ändern möchten, und klicken Sie dann auf das Menü:Ellipsen-Symbol[Einstellungen bearbeiten].
+
Das Dialogfeld „Einstellungen für Anwendungen und Workloads“ wird angezeigt.

. *Optional:* Ändern Sie den vom Benutzer bereitgestellten Namen des Workloads.
. Klicken Sie Auf *Speichern*.

