---
permalink: sm-storage/change-host-port-identifiers-for-a-host.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host port, identifiers, host 
summary: Ändern Sie die Host-Port-IDs Wenn Sie die Benutzerbezeichnung auf einer Host-Port-ID ändern möchten, fügen Sie dem Host eine neue Host-Port-ID hinzu oder löschen Sie eine Host-Port-ID vom Host. 
---
= Ändern der Host-Port-Kennungen für einen Host im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ändern Sie die Host-Port-IDs Wenn Sie die Benutzerbezeichnung auf einer Host-Port-ID ändern möchten, fügen Sie dem Host eine neue Host-Port-ID hinzu oder löschen Sie eine Host-Port-ID vom Host.

.Über diese Aufgabe
Beachten Sie beim Ändern der Host-Port-IDs die folgenden Richtlinien:

* *Hinzufügen* -- Wenn Sie einen Host-Port hinzufügen, verknüpfen Sie die Host-Port-ID mit dem Host, den Sie für die Verbindung mit Ihrem Speicher-Array erstellt haben. Sie können Portinformationen manuell über ein HBA-Dienstprogramm (Host Bus Adapter) eingeben.
* *Bearbeiten* -- Sie können die Host-Ports bearbeiten, um einen Host-Port zu einem anderen Host zu verschieben (zuordnen). Möglicherweise haben Sie den Host Bus Adapter oder iSCSI Initiator auf einen anderen Host verschoben, daher müssen Sie den Host Port zum neuen Host verschieben (zuordnen).
* *Löschen* -- Sie können Host-Ports löschen, um Host-Ports von einem Host zu entfernen (unassoziieren).


.Schritte
. Wählen Sie im linken Bereich Menü:Storage[Hosts].
. Wählen Sie den Host aus, dem die Ports zugeordnet werden sollen, und klicken Sie dann auf das Menü:ellipsis icon[Einstellungen bearbeiten].
+
Wenn Sie einem Host in einem Hostcluster Ports hinzufügen möchten, wählen Sie den gewünschten Host aus. Sie können auf Hostclusterebene keine Ports hinzufügen.

+
Ein Bildschirm „Host-Einstellungen bearbeiten“ erscheint, der die aktuellen Host-Einstellungen anzeigt.

. Ändern Sie die Einstellungen für die Host-Port-ID.
+
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Host Port
 a| 
Sie können eine der folgenden Optionen auswählen:

** *Hostport hinzufügen* -- Klicken Sie auf *Hostport hinzufügen*, um dem Host eine neue Hostport-Kennung zuzuweisen. Die Länge des Hostport-Kennungsnamens wird durch die Host-Schnittstellentechnologie bestimmt. Fibre Channel- und Infiniband-Hostport-Kennungsnamen müssen 16 Zeichen haben. iSCSI-Hostport-Kennungsnamen dürfen maximal 223 Zeichen haben. Der Port muss eindeutig sein. Eine bereits konfigurierte Portnummer ist nicht zulässig.
** *Löschen (X-Symbol)* – Klicken Sie auf das *X*-Symbol, um eine Host-Port-Kennung zu entfernen (die Zuordnung aufzuheben). Die Option „Löschen“ entfernt den Host-Port nicht physisch. Diese Option hebt die Zuordnung zwischen dem Host-Port und dem Host auf. Solange Sie den Host-Bus-Adapter oder den iSCSI-Initiator nicht entfernen, wird der Host-Port weiterhin vom Controller erkannt.
+
[NOTE]
====
Wenn Sie eine Host-Port-ID löschen, ist sie diesem Host nicht mehr zugeordnet. Darüber hinaus verliert der Host über diese Host-Port-Kennung den Zugriff auf jedes seiner zugewiesenen Volumes.

====




 a| 
Name
 a| 
Bei Bedarf können Sie den Portbezeichnungsnamen ändern. Der Portbezeichnungsname muss eindeutig sein. Ein bereits konfigurierter Bezeichnungsname ist nicht zulässig.



 a| 
CHAP-Schlüssel
 a| 
Erscheint nur für iSCSI-Hosts. Sie können den CHAP-Schlüssel für die Initiatoren (iSCSI-Hosts) festlegen oder ändern.

System Manager verwendet die CHAP-Methode (Challenge Handshake Authentication Protocol), mit der die Identität von Zielen und Initiatoren während der ersten Verbindung überprüft wird. Die Authentifizierung basiert auf einem gemeinsamen Sicherheitsschlüssel, dem CHAP-Schlüssel.

|===
. Klicken Sie Auf *Speichern*.

