---
permalink: sm-storage/change-the-reserved-capacity-settings-for-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved capacity, settings, mirrored pair volume 
summary: Sie können die Einstellungen für ein gespiegeltes Paar-Volume ändern, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paar-Volumes voll ist. 
---
= Ändern Sie die Einstellungen für die reservierte Kapazität für ein gespiegeltes Paarvolumen im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für ein Volume mit gespiegelten Paaren ändern, um den Prozentpunkt anzupassen, an dem SANtricity System Manager eine Warnmeldung sendet, wenn die reservierte Kapazität für ein Volume mit gespiegelten Paaren fast voll ist.

.Schritte
. Wählen Sie Menü:Speicher[Pools & Volume Groups].
. Wählen Sie die Registerkarte *reservierte Kapazität* aus.
. Wählen Sie das zu bearbeitende gespiegelte Paar-Volume aus und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld Einstellungen für die reservierte Kapazität des gespiegelten Paar-Volumes wird angezeigt.

. Ändern Sie gegebenenfalls die Einstellungen für die reservierte Kapazität des gespiegelten Paar-Volumes.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Benachrichtigen, wenn...
 a| 
Verwenden Sie das Spinner-Feld, um den Prozentpunkt anzupassen, an dem System Manager eine Benachrichtigung sendet, wenn die reservierte Kapazität eines gespiegelten Paares sich der vollen Kapazität nähert.

Wenn die reservierte Kapazität für das gespiegelte Paar den angegebenen Schwellenwert überschreitet, sendet System Manager eine Warnmeldung, sodass Sie die reservierte Kapazität erweitern können.


NOTE: Durch Ändern der Alarmeinstellung für ein gespiegeltes Paar wird die Alarmeinstellung für alle gespiegelten Paare, die zur gleichen SpiegelungsConsistency Group gehören, geändert.

|===
====
. Klicken Sie auf *Speichern*, um Ihre Änderungen anzuwenden.

