---
permalink: sm-storage/copy-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy volume 
summary: 'Sie können Daten von einem Volume auf ein anderes im selben Storage Array kopieren und ein physisches, zeitpunktgenaues Duplikat (Klon) eines Quell-Volumes erstellen.' 
---
= Volume kopieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Daten von einem Volume auf ein anderes im selben Storage Array kopieren und ein physisches, zeitpunktgenaues Duplikat (Klon) eines Quell-Volumes erstellen.

.Bevor Sie beginnen
* Alle I/O-Aktivitäten des Quell-Volume und des Ziel-Volume müssen angehalten werden.
* Alle Dateisysteme auf dem Quell-Volume und dem Zielvolume müssen abgehängt werden.
* Wenn Sie das Ziel-Volume zuvor bei einem Kopiervolume-Vorgang verwendet haben, benötigen Sie diese Daten nicht mehr oder haben Sie ein Backup der Daten.


Das Quell-Volume ist das Volume, das Host-I/O akzeptiert und Applikationsdaten speichert. Wenn ein Copy Volume gestartet wird, werden Daten aus dem Quell-Volume vollständig in das Ziel-Volume kopiert.

Das Ziel-Volume ist ein Standard-Volume, das eine Kopie der Daten vom Quell-Volume beibehält. Nach Abschluss des Kopiervorgangs ist das Ziel-Volume identisch mit dem Quell-Volume. Das Zielvolume muss die gleiche oder größere Kapazität haben wie das Quell-Volume, es kann jedoch ein anderes RAID-Level aufweisen.

.Mehr zu Online- und Offline-Kopien
====
*Online-Kopie*

Eine Online-Kopie erstellt eine zeitpunktgenaue Kopie eines beliebigen Volumes innerhalb eines Storage Arrays, während es weiterhin möglich ist, in Bearbeitung der Kopie auf das Volume zu schreiben. Diese Funktion wird erreicht, indem ein Snapshot des Volumes erstellt und der Snapshot als tatsächliches Quellvolume für die Kopie verwendet wird. Das Volume, für das das zeitpunktgenaue Image erstellt wird, wird als Basis-Volume bezeichnet. Es kann sich um ein Standard-Volume oder ein Thin Volume im Storage Array handelt.

*Offline-Kopie*

Eine Offline-Kopie liest Daten vom Quell-Volume und kopiert sie auf ein Ziel-Volume, während gleichzeitig alle Updates für das Quell-Volume unterbrochen werden, während die Kopie gerade läuft. Alle Updates des Quell-Volumes werden ausgesetzt, um zu verhindern, dass chronologische Inkonsistenzen auf dem Ziel-Volume erstellt werden. Die offline Volume Copy-Beziehung besteht zwischen einem Quell-Volume und einem Ziel-Volume.

====
[NOTE]
====
Bei einem Vorgang zum Kopieren von Volumes werden die Daten auf dem Ziel-Volume überschrieben und alle dem Ziel-Volume zugeordneten Snapshot-Volumes sind fehlgeschlagen, sofern vorhanden.

====
.Schritte
. Wählen Sie Menü:Storage[Volumes].
. Wählen Sie das Volume aus, das Sie als Quelle für den Kopiervolume verwenden möchten, und wählen Sie anschließend Menü:Kopierdienste[Volume kopieren].
+
Das Dialogfeld Volume-Select-Ziel kopieren wird angezeigt.

. Wählen Sie das Ziel-Volume aus, auf das die Daten kopiert werden sollen.
+
In der Tabelle dieses Dialogfelds werden alle berechtigten Ziel-Volumes aufgelistet.

. Verwenden Sie den Schieberegler, um die Kopierpriorität für den Kopiervorgang festzulegen.
+
Die Kopierpriorität legt fest, wie viele der Systemressourcen zum Abschluss des Vorgangs „Copy Volume“ im Vergleich zu Service-I/O-Anforderungen verwendet werden.

+
.Mehr zu den Prioritätsraten für Kopien
====
Es gibt fünf Prioritätsstufen für Kopien:

** Am Niedrigsten
** Niedrig
** Mittel
** Hoch
** Höchste


Wenn die Kopierpriorität auf die niedrigste Rate eingestellt ist, wird die I/O-Aktivität priorisiert und der Vorgang des Kopiervolumens dauert länger. Wenn die Kopierpriorität auf die höchste Rate eingestellt ist, wird der Kopiervolume-Vorgang priorisiert, aber die I/O-Aktivität für das Speicherarray kann davon betroffen sein.

====
. Wählen Sie aus, ob Sie eine Online-Kopie oder eine Offline-Kopie erstellen möchten. Um eine Online-Kopie zu erstellen, aktivieren Sie das Kontrollkästchen **Quellvolumen während des Kopiervorgangs online halten**.
. Führen Sie einen der folgenden Schritte aus:
+
** Klicken Sie zum Ausführen eines Kopiervorgangs „_Online_“ auf *Weiter*, um mit dem Dialogfeld „Reserve Capacity*“ fortzufahren.
** Um einen Kopiervorgang _offline_ durchzuführen, klicken Sie auf *Fertig stellen*, um die Offline-Kopie zu starten.


. Wenn Sie eine Online-Kopie erstellen möchten, legen Sie die reservierte Kapazität fest, die zum Speichern von Daten und anderen Informationen für die Online-Kopie benötigt wird, und klicken Sie dann auf *Fertig stellen*, um die Online-Kopie zu starten.
+
In der Tabelle für Volume-Kandidaten werden nur die Kandidaten angezeigt, die die angegebene reservierte Kapazität unterstützen. Reservierte Kapazität ist die zugewiesene physische Kapazität, die für jeden Kopierdienst- und Storage-Objekt verwendet wird. Er ist nicht direkt vom Host lesbar.

+
Weisen Sie die reservierte Kapazität mithilfe folgender Richtlinien zu:

+
** Die Standardeinstellung für die reservierte Kapazität ist 40 % der Kapazität des Basis-Volumes, und in der Regel reicht diese Kapazität aus.
** Die reservierte Kapazität kann jedoch je nach Anzahl der Änderungen an den ursprünglichen Daten variieren. Je länger ein Storage-Objekt aktiv ist, desto größer sollte die reservierte Kapazität sein.




System Manager kopiert alle Daten vom Quell-Volume auf das Ziel-Volume. Nachdem der Vorgang des Copy-Volume abgeschlossen ist, wird das Ziel-Volume automatisch schreibgeschützt für die Hosts.

Wählen Sie MENU:Home[Vorgänge in Bearbeitung anzeigen], um den Fortschritt des Vorgangs „Copy Volume“ anzuzeigen. Dieser Vorgang kann langwierig sein und die System-Performance beeinträchtigen.
