---
permalink: sm-storage/copy-snapshot-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, copy, snapshot, volume 
summary: Sie können einen Prozess zum Kopieren von Volumes auf einem Snapshot-Volume oder einem Snapshot-Snapshot-Volume der Konsistenzgruppe durchführen. 
---
= Snapshot Volume kopieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Prozess zum Kopieren von Volumes auf einem Snapshot-Volume oder einem Snapshot-Snapshot-Volume der Konsistenzgruppe durchführen.

Sie können ein Snapshot-Volume wie bei einem normalen Kopiervorgang auf das Ziel-Volume kopieren. Snapshot-Volumen können jedoch während des Kopiervorgangs nicht online bleiben.

.Schritte
. Wählen Sie Menü:Storage[Snapshots].
. Wählen Sie die Registerkarte *Snapshot Volumes* aus.
+
Die Tabelle Snapshot Volumes wird angezeigt und zeigt alle dem Speicher-Array zugeordneten Snapshot-Volumes an.

. Wählen Sie das Snapshot-Volume aus, das Sie kopieren möchten, und wählen Sie dann *Volume kopieren* aus.
+
Das Dialogfeld Volume kopieren wird angezeigt, in dem Sie aufgefordert werden, ein Ziel auszuwählen.

. Wählen Sie das Zielvolume, das als Kopierziel verwendet werden soll, und klicken Sie dann auf *Fertig stellen*.

