---
permalink: sm-storage/create-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, volumes 
summary: Sie erstellen Volumes, um einem applikationsspezifischen Workload Storage-Kapazität hinzuzufügen und die erstellten Volumes für einen bestimmten Host oder Host-Cluster sichtbar zu machen. Darüber hinaus bietet die Erstellung eines Volumes Optionen, mit denen jedem zu erstellenden Volume bestimmte Kapazitätsmengen zugewiesen werden können. 
---
= Erstellen Sie Volumes im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie erstellen Volumes, um einem applikationsspezifischen Workload Storage-Kapazität hinzuzufügen und die erstellten Volumes für einen bestimmten Host oder Host-Cluster sichtbar zu machen. Darüber hinaus bietet die Erstellung eines Volumes Optionen, mit denen jedem zu erstellenden Volume bestimmte Kapazitätsmengen zugewiesen werden können.

.Über diese Aufgabe
Die meisten Applikationstypen sind standardmäßig auf eine benutzerdefinierte Volume-Konfiguration eingestellt. Bei einigen Anwendungstypen wird bei der Volume-Erstellung eine intelligente Konfiguration angewendet. Wenn Sie beispielsweise Volumes für die Microsoft Exchange Applikation erstellen, werden Sie gefragt, wie viele Mailboxen Sie benötigen, wie viele Mailboxen Ihre durchschnittlichen Anforderungen an die Mailbox-Kapazität sind und wie viele Kopien der Datenbank Sie benötigen. System Manager verwendet diese Informationen, um eine optimale Volume-Konfiguration für Sie zu erstellen, die Sie nach Bedarf bearbeiten können.

Der Prozess zur Erstellung eines Volumes ist ein mehrstufiges Verfahren.



== Schritt 1: Wählen Sie Host für ein Volume

Sie erstellen Volumes, um einem applikationsspezifischen Workload Storage-Kapazität hinzuzufügen und die erstellten Volumes für einen bestimmten Host oder Host-Cluster sichtbar zu machen. Darüber hinaus bietet die Erstellung eines Volumes Optionen, mit denen jedem zu erstellenden Volume bestimmte Kapazitätsmengen zugewiesen werden können.

.Bevor Sie beginnen
* Unter dem Feld Hosts sind gültige Hosts oder Host-Cluster vorhanden.
* Für den Host wurden Host-Port-IDs definiert.
* Vor dem Erstellen eines da-fähigen Volumes muss die Host-Verbindung, die Sie verwenden möchten, da unterstützen. Wenn eine der Host-Verbindungen auf den Controllern im Speicher-Array keine Unterstützung für da bietet, können die zugeordneten Hosts auf da-fähige Volumes keinen Zugriff auf Daten haben.


.Über diese Aufgabe
Beachten Sie bei der Zuweisung von Volumes die folgenden Richtlinien:

* Das Betriebssystem eines Hosts kann bestimmte Einschränkungen für die Zugriffsmöglichkeiten auf die Anzahl der Volumes haben, auf die der Host zugreifen kann. Beachten Sie diese Einschränkung bei der Erstellung von Volumes zur Verwendung durch einen bestimmten Host.
* Sie können eine Zuweisung für jedes Volume im Storage-Array definieren.
* Zugewiesene Volumes werden von den Controllern im Storage-Array gemeinsam genutzt.
* Die gleiche Logical Unit Number (LUN) kann nicht zweimal von einem Host oder einem Host-Cluster verwendet werden, um auf ein Volume zuzugreifen. Sie müssen eine eindeutige LUN verwenden.
* Wenn Sie den Prozess zum Erstellen von Volumes beschleunigen möchten, können Sie den Hostzuordnungsschritt überspringen, damit neu erstellte Volumes offline initialisiert werden.


[NOTE]
====
Die Zuweisung eines Volumes zu einem Host schlägt fehl, wenn Sie versuchen, einem Host-Cluster ein Volume zuzuweisen, das mit einer festgelegten Zuordnung für einen Host in den Host-Clustern in Konflikt steht.

====
.Schritte
. Wählen Sie Menü:Storage[Volumes].
. Wählen Sie Menü:Erstellen[Volumen].
+
Das Dialogfeld Volumes erstellen wird angezeigt.

. Wählen Sie aus der Dropdown-Liste einen bestimmten Host oder Host-Cluster aus, dem Sie Volumes zuweisen möchten, oder wählen Sie aus, zu einem späteren Zeitpunkt den Host oder Host-Cluster zuzuweisen.
. Um die Volume-Erstellungsreihenfolge für den ausgewählten Host oder Host-Cluster fortzusetzen, klicken Sie auf *Weiter* und gehen Sie zu <<Schritt 2: Wählen Sie einen Workload für ein Volume>>.
+
Das Dialogfeld „Workload auswählen“ wird angezeigt.





== Schritt 2: Wählen Sie einen Workload für ein Volume

Wählen Sie einen Workload aus, um die Storage-Array-Konfiguration für eine bestimmte Applikation wie Microsoft SQL Server, Microsoft Exchange, Videoüberwachungsanwendungen oder VMware anzupassen. Sie können „andere Anwendung“ auswählen, wenn die Anwendung, die Sie für dieses Speicher-Array verwenden möchten, nicht aufgeführt ist.

.Über diese Aufgabe
In dieser Aufgabe wird beschrieben, wie Volumes für einen vorhandenen Workload erstellt werden.

* _Wenn Sie Volumes mit einem applikationsspezifischem Workload_ erstellen, empfiehlt das System möglicherweise eine optimierte Volume-Konfiguration, um Konflikte zwischen Applikations-Workload-I/O und anderem Datenverkehr aus Ihrer Applikationsinstanz zu minimieren. Sie können die empfohlene Volume-Konfiguration überprüfen und die vom System empfohlenen Volumes und Merkmale bearbeiten, hinzufügen oder löschen. Verwenden Sie dazu das Dialogfeld Volumes hinzufügen/bearbeiten.
* _Wenn Sie Volumes mit „anderen“_ Anwendungen erstellen (oder Anwendungen ohne spezifische Unterstützung der Volume-Erstellung), geben Sie die Volume-Konfiguration manuell über das Dialogfeld Volumes hinzufügen/bearbeiten an.


.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
** Wählen Sie die Option *Volumes für einen vorhandenen Workload erstellen* aus, um Volumes für einen vorhandenen Workload zu erstellen.
** Wählen Sie die Option *Einen neuen Workload erstellen* aus, um einen neuen Workload für eine unterstützte Anwendung oder für „andere“ Anwendungen zu definieren.
+
*** Wählen Sie in der Dropdown-Liste den Namen der Anwendung aus, für die Sie den neuen Workload erstellen möchten.
+
Wählen Sie einen der „anderen“ Einträge aus, wenn die Anwendung, die Sie für dieses Speicher-Array verwenden möchten, nicht aufgeführt ist.

*** Geben Sie einen Namen für den zu erstellenden Workload ein.




. Klicken Sie Auf *Weiter*.
. Wenn Ihr Workload einem unterstützten Applikationstyp zugewiesen ist, geben Sie die angeforderten Informationen ein. Andernfalls fahren Sie mit fort <<Schritt 3: Volumes hinzufügen oder bearbeiten>>.




== Schritt 3: Volumes hinzufügen oder bearbeiten

System Manager kann eine Volume-Konfiguration auf Grundlage der von Ihnen ausgewählten Applikation oder Workload vorschlagen. Diese Volume-Konfiguration ist basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Sie können die empfohlene Volume-Konfiguration akzeptieren oder Sie können sie nach Bedarf bearbeiten. Wenn Sie eine der „anderen“ Anwendungen ausgewählt haben, müssen Sie manuell die Volumes und Merkmale angeben, die Sie erstellen möchten.

.Bevor Sie beginnen
* Die Pools oder Volume-Gruppen müssen über eine ausreichende freie Kapazität verfügen.
* In einer Volume-Gruppe sind maximal 256 Volumes zulässig.
* Die maximale Anzahl an Volumes, die in einem Pool zulässig sind, hängt vom Modell des Storage-Systems ab:
+
** 2,048 Volumes (EF600, EF600C und E5700 Series)
** 1,024 Volumes (EF300 und EF300C)
** 512 Volumes (E4000 und E2800 Serie)


* Um ein für Data Assurance (da) fähiges Volume zu erstellen, muss die Host-Verbindung, die Sie verwenden möchten, da unterstützen.
+
.Auswahl eines sicheren Pools oder einer Volume-Gruppe
[%collapsible]
====
Wenn Sie ein DA-fähiges Volume erstellen möchten, wählen Sie einen Pool oder eine Volume-Gruppe aus, die für da geeignet ist (suchen Sie in der Tabelle mit den Kandidaten für Pool- und Volume-Gruppen nach *Ja* neben „da“).

DA-Funktionen werden auf Pool- und Volume-Gruppenebene in System Manager präsentiert. DA der Schutz auf Fehler überprüft und korrigiert, die auftreten können, wenn Daten durch die Controller an die Laufwerke übertragen werden. Durch die Auswahl eines da-fähigen Pools oder einer Volume-Gruppe für das neue Volume wird sichergestellt, dass Fehler erkannt und behoben werden.

Wenn eine der Host-Verbindungen auf den Controllern im Speicher-Array keine Unterstützung für da bietet, können die zugeordneten Hosts auf da-fähige Volumes keinen Zugriff auf Daten haben.

====
* Um ein sicheres Volume zu erstellen, muss für das Storage Array ein Sicherheitsschlüssel erstellt werden.
+
.Auswahl eines sicheren Pools oder einer Volume-Gruppe
[%collapsible]
====
Wenn Sie ein sicheres Volume erstellen möchten, wählen Sie einen Pool oder eine Volume-Gruppe aus, die sicher ist (suchen Sie in der Tabelle mit den Kandidaten für Pool- und Volume-Gruppen nach *Ja* neben „Secure-fähig“).

Die Sicherheitsfunktionen für die Laufwerke werden auf Pool- und Volume-Gruppenebene in System Manager dargestellt. Sichere Laufwerke verhindern unbefugten Zugriff auf die Daten auf einem Laufwerk, das physisch vom Storage-Array entfernt wird. Ein sicheres Laufwerk verschlüsselt Daten während des Schreibvorgangs und entschlüsselt Daten während des Lesevorgangs mit einem eindeutigen _Verschlüsselungsschlüssel_.

Ein Pool oder eine Volume-Gruppe kann sowohl sichere als auch nicht sichere Laufwerke enthalten. Zur Nutzung der Verschlüsselungsfunktionen müssen jedoch alle Laufwerke sicher sein.

====
* Um ein Volume mit Ressourcenbereitstellung zu erstellen, müssen alle Laufwerke NVMe-Laufwerke mit der dezugewiesenen oder nicht geschriebenen Option Logical Block Error (DULBE) sein.


.Über diese Aufgabe
Sie erstellen Volumes aus Pools oder Volume-Gruppen. Das Dialogfeld Volumes hinzufügen/bearbeiten zeigt alle berechtigten Pools und Volume-Gruppen im Speicher-Array an. Für jeden infrage kommenden Pool und jede Volume-Gruppe wird die Anzahl der verfügbaren Laufwerke und die gesamte freie Kapazität angezeigt.

Für einige applikationsspezifische Workloads zeigt jede qualifizierte Pool- oder Volume-Gruppe die vorgeschlagene Kapazität basierend auf der vorgeschlagenen Volume-Konfiguration und zeigt die verbleibende freie Kapazität in gib an. Für andere Workloads wird die vorgeschlagene Kapazität angezeigt, wenn Sie Volumes zu einem Pool oder einer Volume-Gruppe hinzufügen und die gemeldete Kapazität angeben.

.Schritte
. Wählen Sie eine dieser Aktionen aus, je nachdem, ob Sie eine andere oder einen applikationsspezifischen Workload ausgewählt haben:
+
** *Other* -- Klicken Sie *Neues Volume hinzufügen* in jedem Pool oder Volume-Gruppe, die Sie verwenden möchten, um ein oder mehrere Volumes zu erstellen.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Feld | Beschreibung 


 a| 
Volume-Name
 a| 
Einem Volume wird während der Volume-Erstellung von System Manager ein Standardname zugewiesen. Sie können entweder den Standardnamen akzeptieren oder einen aussagekräftigeren Namen angeben, der die Art der im Volume gespeicherten Daten angibt.



 a| 
Gemeldete Kapazität
 a| 
Definieren Sie die Kapazität des neuen Volume und der zu verwendenden Kapazitätseinheiten (MiB, gib oder tib). Bei dicken Volumes beträgt die Mindestkapazität 1 MiB, und die maximale Kapazität wird durch die Anzahl und Kapazität der Laufwerke im Pool oder der Volume-Gruppe bestimmt.

Storage-Kapazität ist auch für Copy-Services erforderlich (Snapshot Images, Snapshot Volumes, Volume-Kopien und Remote-Spiegelungen). Weisen Sie Standard-Volumes nicht die gesamte Kapazität zu.

Die Kapazität in einem Pool wird je nach Festplattentyp in Schritten von 4 gib oder 8 gib zugewiesen. Kapazität, die nicht ein Vielfaches von 4- oder 8-gib beträgt, wird zugewiesen, jedoch nicht nutzbar. Um sicherzustellen, dass die gesamte Kapazität nutzbar ist, geben Sie die Kapazität in Schritten von 4 gib oder 8 gib an. Wenn eine nicht nutzbare Kapazität vorhanden ist, besteht die einzige Möglichkeit zur Wiederherstellung darin, die Kapazität des Volume zu erhöhen.



 a| 
Volume-Block-Größe (nur EF300 und EF600)
 a| 
Zeigt die Block-Größen, die für das Volume erstellt werden können:

*** 512 -- 512 Byte
*** 4K -- 4,096 Byte




 a| 
Segmentgröße
 a| 
Zeigt die Einstellung für die Segmentgrößen, die nur für Volumes in einer Volume-Gruppe angezeigt wird. Sie können die Segmentgröße ändern, um die Leistung zu optimieren.

*Zulässige Segmentgrößen-Übergänge* -- System Manager bestimmt die zulässigen Segmentgrößen-Übergänge. Segmentgrößen, bei denen es sich um unangemessene Übergänge aus der aktuellen Segmentgröße handelt, sind in der Dropdown-Liste nicht verfügbar. Zulässige Übergänge sind in der Regel doppelt oder halb so groß wie das aktuelle Segment. Wenn die aktuelle Volume-Segmentgröße beispielsweise 32 KiB beträgt, ist eine neue Volume-Segmentgröße von entweder 16 KiB oder 64 KiB zulässig.

*SSD Cache-fähige Volumes* -- Sie können eine 4-KiB-Segmentgröße für SSD Cache-fähige Volumes angeben. Vergewissern Sie sich, dass Sie die 4-KiB-Segmentgröße nur für SSD-Cache-fähige Volumes auswählen, die I/O-Vorgänge mit kleinen Blöcken bearbeiten (beispielsweise 16 KiB-I/O-Blockgrößen oder kleiner). Die Performance könnte beeinträchtigt werden, wenn Sie 4 als Segmentgröße für SSD Cache-fähige Volumes auswählen, die sequenzielle Operationen von großen Blöcken bearbeiten.

*Zeit zum Ändern der Segmentgröße* -- die Zeit, die zur Änderung der Segmentgröße eines Volumes benötigt wird, hängt von diesen Variablen ab:

*** Die I/O-Last vom Host
*** Die Änderungspriorität des Volumes
*** Die Anzahl der Laufwerke in der Volume-Gruppe
*** Die Anzahl der Laufwerkskanäle
*** Die Verarbeitungsleistung der Speicher-Array-Controller


Wenn Sie die Segmentgröße für ein Volume ändern, wirkt sich die I/O-Performance auf die I/O-Performance aus, doch die Daten bleiben verfügbar.



 a| 
Sicher
 a| 
*Ja* erscheint neben "Secure-fähig" nur dann, wenn die Laufwerke im Pool oder in der Volume-Gruppe sicher sind.

Die Laufwerkssicherheit verhindert, dass nicht autorisierter Zugriff auf die Daten auf einem Laufwerk erfolgt, das physisch vom Speicher-Array entfernt wird. Diese Option ist nur verfügbar, wenn die Laufwerksicherheit aktiviert wurde und für das Speicher-Array ein Sicherheitsschlüssel eingerichtet wurde.

Ein Pool oder eine Volume-Gruppe kann sowohl sichere als auch nicht sichere Laufwerke enthalten. Zur Nutzung der Verschlüsselungsfunktionen müssen jedoch alle Laufwerke sicher sein.



 a| 
DA
 a| 
*Ja* erscheint neben „da“ nur dann, wenn die Laufwerke im Pool oder in der Volume-Gruppe Data Assurance (da) unterstützen.

DA erhöht die Datenintegrität im gesamten Storage-System. DA ermöglicht es dem Storage-Array, Fehler zu überprüfen, die auftreten können, wenn Daten durch die Controller an die Laufwerke übertragen werden. Die Verwendung von da für das neue Volume stellt sicher, dass alle Fehler erkannt werden.



 a| 
Bereitgestellte Ressource (nur EF300 und EF600)
 a| 
*Ja* erscheint neben „Ressourcen bereitgestellt“ nur, wenn die Laufwerke diese Option unterstützen. Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen.

|===
====
** *Anwendungsspezifischer Workload* -- Klicken Sie entweder auf *Weiter*, um die vom System empfohlenen Volumes und Merkmale für den ausgewählten Workload zu akzeptieren, oder klicken Sie auf *Volumes bearbeiten*, um die vom System empfohlenen Volumes und Merkmale für den ausgewählten Workload zu ändern, hinzuzufügen oder zu löschen.
+
.Felddetails
[%collapsible]
====
[cols="1a,1a"]
|===
| Feld | Beschreibung 


 a| 
Volume-Name
 a| 
Einem Volume wird während der Volume-Erstellung von System Manager ein Standardname zugewiesen. Sie können entweder den Standardnamen akzeptieren oder einen aussagekräftigeren Namen angeben, der die Art der im Volume gespeicherten Daten angibt.



 a| 
Gemeldete Kapazität
 a| 
Definieren Sie die Kapazität des neuen Volume und der zu verwendenden Kapazitätseinheiten (MiB, gib oder tib). Bei dicken Volumes beträgt die Mindestkapazität 1 MiB, und die maximale Kapazität wird durch die Anzahl und Kapazität der Laufwerke im Pool oder der Volume-Gruppe bestimmt.

Storage-Kapazität ist auch für Copy-Services erforderlich (Snapshot Images, Snapshot Volumes, Volume-Kopien und Remote-Spiegelungen). Weisen Sie Standard-Volumes nicht die gesamte Kapazität zu.

Die Kapazität in einem Pool wird je nach Festplattentyp in Schritten von 4 gib oder 8 gib zugewiesen. Kapazität, die nicht ein Vielfaches von 4- oder 8-gib beträgt, wird zugewiesen, jedoch nicht nutzbar. Um sicherzustellen, dass die gesamte Kapazität nutzbar ist, geben Sie die Kapazität in Schritten von 4 gib oder 8 gib an. Wenn eine nicht nutzbare Kapazität vorhanden ist, besteht die einzige Möglichkeit zur Wiederherstellung darin, die Kapazität des Volume zu erhöhen.



 a| 
Volume-Typ
 a| 
Volume-Typ gibt den Volume-Typ an, der für einen applikationsspezifischen Workload erstellt wurde.



 a| 
Volume-Block-Größe (nur EF300 und EF600)
 a| 
Zeigt die Block-Größen, die für das Volume erstellt werden können:

*** 512 -- 512 Byte
*** 4K -- 4,096 Byte




 a| 
Segmentgröße
 a| 
Zeigt die Einstellung für die Segmentgrößen, die nur für Volumes in einer Volume-Gruppe angezeigt wird. Sie können die Segmentgröße ändern, um die Leistung zu optimieren.

*Zulässige Segmentgrößen-Übergänge* -- System Manager bestimmt die zulässigen Segmentgrößen-Übergänge. Segmentgrößen, bei denen es sich um unangemessene Übergänge aus der aktuellen Segmentgröße handelt, sind in der Dropdown-Liste nicht verfügbar. Zulässige Übergänge sind in der Regel doppelt oder halb so groß wie das aktuelle Segment. Wenn die aktuelle Volume-Segmentgröße beispielsweise 32 KiB beträgt, ist eine neue Volume-Segmentgröße von entweder 16 KiB oder 64 KiB zulässig.

*SSD Cache-fähige Volumes* -- Sie können eine 4-KiB-Segmentgröße für SSD Cache-fähige Volumes angeben. Vergewissern Sie sich, dass Sie die 4-KiB-Segmentgröße nur für SSD-Cache-fähige Volumes auswählen, die I/O-Vorgänge mit kleinen Blöcken bearbeiten (beispielsweise 16 KiB-I/O-Blockgrößen oder kleiner). Die Performance könnte beeinträchtigt werden, wenn Sie 4 als Segmentgröße für SSD Cache-fähige Volumes auswählen, die sequenzielle Operationen von großen Blöcken bearbeiten.

*Zeit zum Ändern der Segmentgröße* -- die Zeit, die zur Änderung der Segmentgröße eines Volumes benötigt wird, hängt von diesen Variablen ab:

*** Die I/O-Last vom Host
*** Die Änderungspriorität des Volumes
*** Die Anzahl der Laufwerke in der Volume-Gruppe
*** Die Anzahl der Laufwerkskanäle
*** Die Verarbeitungsleistung der Storage-Array-Controller, wenn Sie die Segmentgröße für ein Volume ändern, wirkt sich dies auf die I/O-Performance aus, doch Ihre Daten bleiben verfügbar.




 a| 
Sicher
 a| 
*Ja* erscheint neben "Secure-fähig" nur dann, wenn die Laufwerke im Pool oder in der Volume-Gruppe sicher sind.

Die Laufwerkssicherheit verhindert, dass nicht autorisierter Zugriff auf die Daten auf einem Laufwerk erfolgt, das physisch vom Speicher-Array entfernt wird. Diese Option ist nur verfügbar, wenn die Sicherheitsfunktion des Laufwerks aktiviert ist und für das Speicher-Array ein Sicherheitsschlüssel eingerichtet wurde.

Ein Pool oder eine Volume-Gruppe kann sowohl sichere als auch nicht sichere Laufwerke enthalten. Zur Nutzung der Verschlüsselungsfunktionen müssen jedoch alle Laufwerke sicher sein.



 a| 
DA
 a| 
*Ja* erscheint neben „da“ nur dann, wenn die Laufwerke im Pool oder in der Volume-Gruppe Data Assurance (da) unterstützen.

DA erhöht die Datenintegrität im gesamten Storage-System. DA ermöglicht es dem Storage-Array, Fehler zu überprüfen, die auftreten können, wenn Daten durch die Controller an die Laufwerke übertragen werden. Die Verwendung von da für das neue Volume stellt sicher, dass alle Fehler erkannt werden.



 a| 
Bereitgestellte Ressource (nur EF300 und EF600)
 a| 
*Ja* erscheint neben „Ressourcen bereitgestellt“ nur, wenn die Laufwerke diese Option unterstützen. Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen.

|===
====


. Um die Sequenz zur Volume-Erstellung für die ausgewählte Anwendung fortzusetzen, klicken Sie auf *Weiter* und gehen Sie zu <<Schritt 4: Prüfen der Volume-Konfiguration>>.




== Schritt 4: Prüfen der Volume-Konfiguration

Prüfen Sie eine Zusammenfassung der Volumes, die Sie erstellen möchten, und nehmen Sie die erforderlichen Änderungen vor.

.Schritte
. Prüfen Sie die Volumes, die Sie erstellen möchten. Klicken Sie auf *Zurück*, um Änderungen vorzunehmen.
. Wenn Sie mit Ihrer Volumenkonfiguration zufrieden sind, klicken Sie auf *Fertig stellen*.


.Ergebnisse
System Manager erstellt die neuen Volumes in den ausgewählten Pools und Volume-Gruppen und zeigt dann die neuen Volumes in der Tabelle Alle Volumes an.

.Nachdem Sie fertig sind
* Führen Sie alle auf dem Applikations-Host erforderlichen Betriebssystemänderungen durch, damit die Applikationen das Volume verwenden können.
* Führen Sie das betriebssystemspezifische Dienstprogramm (verfügbar von einem Drittanbieter) aus, und führen Sie dann den Befehl SMcli aus `-identifyDevices` So korrelieren Sie Volume-Namen mit Host-Storage-Array-Namen
+
Die SMcli ist direkt über den SANtricity System Manager erhältlich. Diese Version kann von den SMcli heruntergeladen werden und ist für die Controller E4000, EF600, EF600C, EF300, EF300C, E5700, EF570, E2800 und EF280 erhältlich. Um den SMcli im SANtricity System Manager herunterzuladen, wählen Sie *Einstellungen* > *System* und *Add-ons* > *Befehlszeilenschnittstelle*.


