---
permalink: sm-storage/create-host-manually.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, create, host, manually 
summary: Für Hosts, die nicht automatisch erkannt werden können, können Sie manuell einen Host erstellen. Das Erstellen eines Hosts ist einer der Schritte, die erforderlich sind, damit das Storage-Array wissen kann, an welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen. 
---
= Host manuell erstellen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für Hosts, die nicht automatisch erkannt werden können, können Sie manuell einen Host erstellen. Das Erstellen eines Hosts ist einer der Schritte, die erforderlich sind, damit das Storage-Array wissen kann, an welche Hosts angeschlossen sind und um den I/O-Zugriff auf die Volumes zu ermöglichen.

.Über diese Aufgabe
Beachten Sie beim Erstellen eines Hosts die folgenden Richtlinien:

* Sie müssen die dem Host zugeordneten Host-Identifier-Ports definieren.
* Stellen Sie sicher, dass Sie denselben Namen wie den zugewiesenen Systemnamen des Hosts angeben.
* Dieser Vorgang ist nicht erfolgreich, wenn der gewählte Name bereits verwendet wird.
* Die Länge des Namens darf nicht mehr als 30 Zeichen umfassen.


.Schritte
. Wählen Sie Menü:Storage[Hosts].
. Klicken Sie auf Menü:Create[Host].
+
Das Dialogfeld Host erstellen wird angezeigt.

. Wählen Sie die entsprechenden Einstellungen für den Host aus.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Name
 a| 
Geben Sie einen Namen für den neuen Host ein.



 a| 
Host-Betriebssystem-Typ
 a| 
Wählen Sie aus der Dropdown-Liste das auf dem neuen Host ausgeführte Betriebssystem aus.



 a| 
Host-Schnittstellentyp
 a| 
(Optional) Wenn auf Ihrem Speicherarray mehr als eine Host-Schnittstelle unterstützt wird, wählen Sie den Host-Schnittstellentyp aus, den Sie verwenden möchten.



 a| 
Host-Ports
 a| 
Führen Sie einen der folgenden Schritte aus:

** *E/A-Schnittstelle auswählen*
+
Im Allgemeinen sollten sich die Host-Ports angemeldet haben und in der Dropdown-Liste verfügbar sein. Sie können die Host-Port-IDs aus der Liste auswählen.

** *Manuelles Hinzufügen*
+
Wenn eine Host-Port-ID nicht in der Liste angezeigt wird, bedeutet dies, dass der Host-Port nicht angemeldet ist. Mithilfe eines HBA-Dienstprogramms oder des iSCSI-Initiator-Dienstprogramms können die Host-Port-IDs ermittelt und mit dem Host verknüpft werden.

+
Sie können die Host-Port-IDs manuell eingeben oder sie aus dem Dienstprogramm (nacheinander) in das Feld *Host-Ports* kopieren/einfügen.

+
Sie müssen eine Host-Port-ID gleichzeitig auswählen, um sie dem Host zuzuordnen. Sie können jedoch weiterhin so viele Kennungen auswählen, die dem Host zugeordnet sind. Jede Kennung wird im Feld *Host Ports* angezeigt. Bei Bedarf können Sie auch einen Bezeichner entfernen, indem Sie neben ihm die *X*-Option auswählen.





 a| 
CHAP-Initiator
 a| 
(Optional) Wenn Sie einen Host-Port mit einem iSCSI-IQN ausgewählt oder manuell eingegeben haben und wenn Sie einen Host benötigen möchten, der versucht, auf das Speicher-Array zuzugreifen, um sich mit dem Challenge Handshake Authentication Protocol (CHAP) zu authentifizieren, aktivieren Sie das Kontrollkästchen *CHAP Initiator*. Gehen Sie für jeden ausgewählten oder manuell eingegebenen iSCSI-Host-Port wie folgt vor:

** Geben Sie denselben CHAP-Schlüssel ein, der auf jedem iSCSI-Hostinitiator für die CHAP-Authentifizierung festgelegt wurde. Wenn Sie die gegenseitige CHAP-Authentifizierung verwenden (zwei-Wege-Authentifizierung, die es einem Host ermöglicht, sich am Speicher-Array zu validieren, und damit sich ein Speicher-Array am Host validieren kann), müssen Sie auch den CHAP-Schlüssel für das Speicher-Array bei der Ersteinrichtung oder durch Ändern von Einstellungen festlegen.
** Wenn Sie keine Host-Authentifizierung benötigen, lassen Sie das Feld leer.


Derzeit ist CHAP die einzige in System Manager verwendete iSCSI-Authentifizierungsmethode.

|===
====
. Klicken Sie Auf *Erstellen*.


.Ergebnisse
Nachdem der Host erfolgreich erstellt wurde, erstellt das System für jeden Host-Port, der für den Host konfiguriert wurde (Benutzungsbezeichnung) einen Standardnamen.

Der Standard-Alias ist <``Hostname_Port Number``>. Beispiel: Der Standard-Alias für den ersten Port, für den erstellt wurde `host IPT is IPT_1`.
