---
permalink: sm-storage/delete-snapshot-schedule.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, delete, snapshot, schedule 
summary: Wenn Sie keine Snapshot-Images mehr erstellen möchten, können Sie einen vorhandenen Snapshot-Zeitplan löschen. 
---
= Löschen eines Snapshot-Zeitplans im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie keine Snapshot-Images mehr erstellen möchten, können Sie einen vorhandenen Snapshot-Zeitplan löschen.

.Über diese Aufgabe
Wenn Sie einen Snapshot-Zeitplan löschen, werden die zugehörigen Snapshot-Images nicht zusammen mit ihm gelöscht. Wenn Sie der Meinung sind, dass die Sammlung von Snapshot-Bildern irgendwann wieder aufgenommen werden könnte, sollten Sie den Snapshot-Zeitplan unterbrechen, anstatt ihn zu löschen.

.Schritte
. Wählen Sie im linken Bereich Menü:Storage[Snapshots].
. Klicken Sie auf die Registerkarte *Snapshots Schedules*.
. Wählen Sie den Snapshot-Zeitplan aus, den Sie löschen möchten, klicken Sie auf *Delete*, und bestätigen Sie den Vorgang.


.Ergebnisse
Das System entfernt alle Zeitplanattribute vom Basis-Volume oder der Snapshot-Konsistenzgruppe.
