---
permalink: sm-storage/disable-resource-provisioning-on-existing-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, disable, resource provisioning, 
summary: Sie können die Ressourcenbereitstellung in einem vorhandenen Pool oder einer Volume-Gruppe aktivieren oder deaktivieren. 
---
= Aktivieren oder deaktivieren Sie die Ressourcenbereitstellung für vorhandene Volumegruppen und Pools im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für alle DELBE-fähigen Laufwerke können Sie die Ressourcenbereitstellung auf vorhandenen Volumes in einem Pool oder einer Volume-Gruppe aktivieren oder deaktivieren.

Die Ressourcenbereitstellung ist eine Funktion der Speichersysteme EF80, EF50, EF300/EF300C und EF600/EF600C, die es ermöglicht, Volumes sofort ohne Hintergrundinitialisierung zu verwenden. Alle dem Volume zugewiesenen Laufwerksblöcke werden deallokiert (nicht zugeordnet), was die SSD-Verschleißlebensdauer verbessern und die maximale Schreibleistung erhöhen kann.

Standardmäßig ist die Ressourcenbereitstellung auf Systemen aktiviert, auf denen die Laufwerke DULBE unterstützen. Die Ressourcenbereitstellung muss erst aktiviert werden, wenn Sie sie zuvor deaktiviert haben.

.Bevor Sie beginnen
* Sie müssen über ein EF80-, EF50-, EF300- oder EF600-Speicherarray verfügen.
* Sie müssen SSD-Volume-Gruppen oder -Pools haben, wobei alle Laufwerke die Funktion zur Wiederherstellung von dezugewiesenen oder nicht geschriebenen logischen Blockfehlern (DULBE) unterstützen. Andernfalls ist die Option zur Ressourcenbereitstellung nicht verfügbar.


.Über diese Aufgabe
Wenn Sie die Ressourcenbereitstellung für vorhandene Volume-Gruppen und -Pools aktivieren, werden alle Volumes in der ausgewählten Volume-Gruppe oder dem ausgewählten Pool geändert, damit die Blöcke wieder entzugewiesen werden können. Dieser Prozess kann einen Hintergrundvorgang erfordern, um eine konsistente Zuweisung auf der Granularität zu gewährleisten. Dieser Vorgang zeigt die Zuordnung von Speicherplatz nicht an. Sobald der Hintergrundvorgang abgeschlossen ist, muss das Betriebssystem die Zuordnung ungenutzter Blöcke aufheben, um freien Speicherplatz zu erstellen.

Wenn Sie die Ressourcenbereitstellung für vorhandene Volume-Gruppen oder Pools deaktivieren, schreibt ein Hintergrundvorgang alle logischen Blöcke in jedem Volume neu. Die bestehenden Daten bleiben erhalten. Die Schreibvorgänge zuordnen oder stellen die Blöcke auf den Laufwerken bereit, die der Volume-Gruppe oder dem Pool zugeordnet sind.


NOTE: Für neue Volume-Gruppen und -Pools können Sie die Ressourcenbereitstellung über Menü:Einstellungen[System > zusätzliche Einstellungen > Aktivieren/Deaktivieren von Volumes mit Ressourcenbereitstellung] aktivieren oder deaktivieren.

.Schritte
. Wählen Sie im linken Bereich menu:Storage[Pools und volume groups].
. Klicken Sie auf das *Ellipsen*-Symbol und wählen Sie entweder *Ressourcenbereitstellung aktivieren* oder *Ressourcenbereitstellung deaktivieren* für den ausgewählten Pool oder die ausgewählte Volumengruppe.
. Bestätigen Sie im Dialogfeld den Vorgang.



NOTE: *Wenn Sie DULBE* erneut aktiviert haben -- nach Abschluss des Hintergrundvorgangs müssen Sie möglicherweise den Host neu starten, damit die DULBE-Konfigurationsänderungen erkannt und anschließend alle Dateisysteme neu mounten.
