---
permalink: sm-storage/faq-remote-storage.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Remote-Speicher-FAQ für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Was muss ich vor der Erstellung einer Remote-Speicherverbindung wissen?

Zur Konfiguration der Remote-Speicherfunktion müssen Sie das Remote-Gerät und die Zielspeichersysteme direkt über iSCSI verbinden.

Informationen zum Einrichten der iSCSI-Systemverbindung finden Sie unter:

* link:../sm-hardware/configure-iscsi-ports-hardware.html["Konfigurieren Sie die iSCSI-Ports"]
* https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Technischer Bericht Zu Remote-Storage"^]




== Warum wird ich aufgefordert, meine Remote-Volumes zu entfernen?

Wenn die maximale Anzahl an Remote-Volumes erreicht ist, erkennt das Speichersystem automatisch alle nicht verwendeten Remote-Volumes und fordert Sie auf, diese zu entfernen.

In einigen Fällen werden die nicht verwendeten Remote-Volumes während des Erstellungsprozesses nicht bereinigt. Bevor Sie weitere Importvorgänge starten, überprüfen Sie, ob Ihre Systeme optimal sind und die Netzwerkverbindungen stabil sind.



== Warum werden mir nicht alle meine Volumes auf meinem Ziel-Array angezeigt?

Bei der Konfiguration eines Imports für die Remote-Speicherfunktion können Sie feststellen, dass einige Volumes aufgrund von Blockgröße, Kapazität oder Volume-Verfügbarkeit nicht in der Liste der Zielkandidaten angezeigt werden.

Um in der Liste angezeigt zu werden, müssen Volumenkandidaten Folgendes haben:

* Kapazität, die dem Remote-Volume entspricht oder größer ist.
* Blockgröße, die mit dem Remote Volume identisch ist.
* Aktueller Status von optimal.


Volumes-Kandidaten werden aus der Liste ausgeschlossen, wenn sie:

* Jede der folgenden Beziehungen: Volume-Kopie, Snapshot oder Spiegelung.
* Neukonfigurierung wird ausgeführt.
* Zuordnung zu einem anderen Gerät (Host oder Host-Cluster)
* Lese-Flash-Cache aktiviert.




== Was muss ich über das Remote Volume bei einem Import wissen?

Bei Verwendung der Remote-Storage-Funktion ist zu beachten, dass das Remote-Volume die Quelle ist, aus der die Daten stammen.

Wenn der Import ausgeführt wird, werden die Daten vom Remote-Volume auf das Ziel-Volume auf dem Ziel-Storage-System übertragen. Diese beiden Volumes müssen eine passende Blockgröße aufweisen.



== Was muss ich vor dem Start eines Remote-Storage-Imports beachten?

Mit der Remote Storage-Funktion können Sie Daten von einem Remote Storage-System auf ein Volume auf einem lokalen E-Series Storage-System kopieren. Bevor Sie diese Funktion verwenden, lesen Sie die folgenden Richtlinien durch.



=== Konfiguration

Bevor Sie den Remote-Speicherimport erstellen, müssen Sie die folgenden Aktionen durchführen und die folgenden Bedingungen überprüfen:

* Stellen Sie sicher, dass jeder Controller des lokalen E-Series Storage-Systems über eine iSCSI-Verbindung zum Remote Storage-System verfügt.
* Erstellen Sie auf Ihrem lokalen E-Series Storage-System ein Ziel-Volume für den Importvorgang. Stellen Sie sicher, dass das Volume über eine Kapazität verfügt, die dem Quell-Volume entspricht oder größer ist als das Quell-Volume, über eine Blockgröße verfügt, die dem Quell-Volume entspricht und nicht zugeordnet ist. Siehe link:create-volumes.html["Volumes erstellen"].
* Richten Sie das lokale E-Series Storage-System mithilfe des iSCSI Qualified Name (IQN) als Host auf dem Remote-System ein. Sie können den IQN über Menü:Einstellungen[System > iSCSI-Einstellungen > Ziel-IQN] anzeigen. Stellen Sie außerdem sicher, dass Sie den entsprechenden Host-Typ auf Grundlage des verwendeten Systems festlegen.
* Beenden Sie alle I/OS, heben Sie die Mounten von Dateisystemen ab und entfernen Sie alle Zuweisungen zu Hosts oder Anwendungen für das ausgewählte Volume auf dem Remote-Speichersystem.
* Weisen Sie das Volume dem Remote-Storage-System dem neu erstellten lokalen Host des E-Series Storage-Systems zu.
* Sammeln Sie die folgenden Informationen aus dem Remote-Speichersystem, damit der Import erstellt werden kann:
+
** Qualifizierter iSCSI-Name (IQN)
** ISCSI-IP-Adresse
** Die LUN-Nummer des Remote-Storage-Geräts, aus dem die Quelldaten stammen


* Sobald der Importvorgang beginnt, wird das gesamte lokale Zielvolume mit den kopierten Daten überschrieben. Alle neuen Daten, die auf das lokale Ziel-Volume geschrieben werden, werden nach der Importerstellung auf dem Volume des Remote-Speichergeräts übertragen. Daher empfehlen wir, vor Beginn des Importvorgangs Backups von Volumes auf dem Remote-Storage-System durchzuführen.




=== Importvorgang

Die folgenden Schritte beschreiben den Importvorgang.

. Öffnen Sie die System Manager-Schnittstelle und gehen Sie dann zur Seite *Remote Storage*. Wählen Sie *Import*, um eine neue Importerstellung zu starten. Ausführliche Anweisungen finden Sie unter link:rtv-import-remote-storage.html["Remote-Speicher importieren"].
+
Wenn Sie einen Offline-Import durchführen möchten, weisen Sie das Zielvolume erst nach Abschluss des Imports zu.

. Überwachen Sie den Importfortschritt.
+
Sobald der Import gestartet wurde, kann das Zielvolume zugeordnet werden. Wie lange der Importvorgang abgeschlossen werden muss, hängt von der Größe des Remote-Speichergeräts (Quell-Volume), der Prioritätseinstellung für den Import und der Menge der I/O-Last sowohl auf den Speichersystemen als auch den zugehörigen Volumes ab.

+
Nach Abschluss des Imports handelt es sich bei dem Zielvolume um ein Duplikat der Quelle.

. Wenn Sie bereit sind, die Mapping-Beziehung zu brechen, führen Sie im Fenster *Operationen in Progress* ein *Trennen* auf dem Importobjekt aus.


Sobald der Import getrennt ist, kehrt die Leistung des lokalen Ziels wieder in den Normalzustand zurück und wird nicht mehr von der Remote-Verbindung beeinträchtigt.



=== Einschränkungen

Die Remote-Speicherfunktion verfügt über folgende Einschränkungen:

* Die Spiegelung muss deaktiviert werden.
* Auf dem Ziel-Volume des E-Series Systems dürfen keine Snapshots vorhanden sein.
* Das Ziel-Volume auf dem E-Series System darf vor dem Start des Imports keinen Hosts zugeordnet werden.
* Auf dem Ziel-Volume des E-Series Systems muss die Ressourcen-Bereitstellung deaktiviert sein.
* Direkte Zuordnungen des Remote-Storage-Volumes zu einem oder mehreren Hosts werden nicht unterstützt.
* Web Services Proxy wird nicht unterstützt.
* ISCSI-CHAP-Schlüssel werden nicht unterstützt.
* SMcli wird nicht unterstützt.
* VMware Datastore wird nicht unterstützt.
* Ein Upgrade von nur einem Speichersystem im Verhältnis-/Importpaar kann zu einem Zeitpunkt durchgeführt werden, an dem ein Importpaar vorhanden ist.




=== Weitere Informationen

Weitere Informationen zur Remote-Speicherung finden Sie auf der https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Technischer Bericht Zu Remote-Storage"^].
