---
permalink: sm-storage/faq-pools-volume-groups.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= FAQ zu Pools und Volumegruppen für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Was ist eine Volume-Gruppe?

Eine Volume-Gruppe ist ein Container für Volumes mit gemeinsamen Merkmalen. Eine Volume-Gruppe verfügt über eine definierte Kapazität und einen RAID-Level. Sie können eine Volume-Gruppe verwenden, um ein oder mehrere Volumes zu erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einer Volume-Gruppe oder aus einem Pool.)



== Was ist ein Pool?

Ein Pool ist eine Reihe von Laufwerken, die logisch gruppiert sind. Mit einem Pool können Sie ein oder mehrere Volumes erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einem Pool oder einer Volume-Gruppe.)

Pools können Administratoren die Auslastung jedes Hosts nicht mehr überwachen und feststellen, wann dieser nicht mehr genügend Speicherplatz hat, und vermeiden, dass herkömmliche Ausfälle aufgrund der Festplattengröße auftreten. Wenn ein Pool knapp wird, können ohne Unterbrechungen zusätzliche Laufwerke zum Pool hinzugefügt werden, und das Kapazitätswachstum ist für den Host transparent.

Mit Pools werden die Daten automatisch neu verteilt, um das Gleichgewicht aufrechtzuerhalten. Durch die Verteilung von Paritätsinformationen und freien Kapazitäten im gesamten Pool kann jedes Laufwerk im Pool zur Neuerstellung eines ausgefallenen Laufwerks verwendet werden. Bei diesem Ansatz werden keine dedizierten Hot Spare-Festplatten verwendet. Stattdessen wird im gesamten Pool die unveränderte (freie) Kapazität reserviert. Beim Laufwerksausfall werden Segmente auf anderen Laufwerken gelesen, um die Daten neu zu erstellen. Anschließend wird ein neues Laufwerk ausgewählt, um jedes Segment, das sich auf einem ausgefallenen Laufwerk befand, zu schreiben, damit die Datenverteilung auf verschiedenen Laufwerken erhalten bleibt.



== Was ist reservierte Kapazität?

Die reservierte Kapazität ist die physisch zugewiesene Kapazität, die Daten für Copy-Service-Objekte wie Snapshot Images, Volumes von Konsistenzgruppen und gespiegelte Paar-Volumes speichert.

Das Volume mit reservierter Kapazität, das einem Kopiervorgang zugeordnet ist, befindet sich in einem Pool oder einer Volume-Gruppe. Sie erstellen reservierte Kapazität entweder aus einem Pool oder einer Volume-Gruppe.



== Was ist FDE/FIPS-Sicherheit?

FDE/FIPS-Sicherheit bezieht sich auf sichere Laufwerke, die Daten bei Schreibvorgängen verschlüsseln und während Lesevorgängen mit einem eindeutigen Verschlüsselungsschlüssel entschlüsseln. Diese sicheren Laufwerke verhindern unbefugten Zugriff auf die Daten auf einem Laufwerk, das physisch vom Storage-Array entfernt wird.

Sichere Laufwerke können entweder vollständige Festplattenverschlüsselung (Full Disk Encryption, FDE) oder FIPS-Laufwerke (Federal Information Processing Standard) sein. FIPS-Laufwerke wurden getestet.

[NOTE]
====
Für Volumes, die FIPS-Unterstützung erfordern, verwenden Sie nur FIPS-Laufwerke. Durch das Mischen von FIPS- und FDE-Laufwerken in einer Volume-Gruppe oder einem Pool werden alle Laufwerke als FDE-Laufwerke behandelt. Außerdem kann ein FDE-Laufwerk nicht zu einer Ersatzfestplatte in einer reinen FIPS-Volume-Gruppe oder einem Pool hinzugefügt oder verwendet werden.

====


== Was ist Redundanzprüfung?

Durch eine Redundanzprüfung wird ermittelt, ob die Daten auf einem Volume in einem Pool oder einer Volume-Gruppe konsistent sind. Redundanzdaten dienen der schnellen Rekonstruktion von Informationen über das Ersatzlaufwerk, wenn eines der Laufwerke im Pool oder der Volume-Gruppe ausfällt.

Sie können diese Prüfung nur für einen Pool oder eine Volume-Gruppe gleichzeitig durchführen. Bei einer Volume-Redundanzprüfung werden folgende Aktionen durchgeführt:

* Scannt die Datenblöcke in einem RAID 3-Volume, einem RAID 5-Volume oder einem RAID 6-Volume und überprüft anschließend die Redundanzinformationen für jeden Block. (RAID 3 kann Volume-Gruppen nur über die Befehlszeilenschnittstelle zugewiesen werden.)
* Vergleicht die Datenblöcke auf gespiegelten RAID 1-Laufwerken.
* Gibt Redundanzfehler zurück, wenn die Daten von der Controller-Firmware uneinheitlich sind.


[NOTE]
====
Eine sofortige Durchführung einer Redundanzprüfung auf demselben Pool oder derselben Volume-Gruppe kann zu einem Fehler führen. Um dieses Problem zu vermeiden, warten Sie ein bis zwei Minuten, bevor Sie eine weitere Redundanzprüfung auf demselben Pool oder derselben Volume-Gruppe durchführen.

====


== Worin bestehen die Unterschiede zwischen Pools und Volume-Gruppen?

Ein Pool ähnelt einer Volume-Gruppe mit den folgenden Unterschieden.

* Die Daten in einem Pool werden zufällig auf allen Laufwerken im Pool gespeichert, im Gegensatz zu Daten in einer Volume-Gruppe, die auf demselben Satz an Laufwerken gespeichert werden.
* Wenn ein Laufwerk ausfällt, weist ein Pool weniger Performance-Einbußen auf und die Rekonstruktionszeit verkürzt sich.
* Ein Pool verfügt über integrierte Konservierungskapazität und benötigt daher keine dedizierten Hot-Spare-Festplatten.
* Ein Pool ermöglicht die Gruppierung einer großen Anzahl von Laufwerken.
* Ein Pool benötigt keine angegebene RAID-Stufe.




== Warum sollte ich einen Pool manuell konfigurieren?

Die folgenden Beispiele beschreiben, warum Sie einen Pool manuell konfigurieren möchten.

* Wenn Ihr Storage-Array über mehrere Applikationen verfügt und Sie nicht möchten, dass dieselben Laufwerkressourcen miteinander konkurrieren, sollten Sie möglicherweise manuell einen kleineren Pool für eine oder mehrere Applikationen erstellen.
+
Sie können nur ein oder zwei Volumes zuweisen, statt den Workload einem großen Pool mit vielen Volumes zuzuweisen, über die die Daten verteilt werden sollen. Durch die manuelle Erstellung eines separaten Pools, der dem Workload einer bestimmten Applikation zugewiesen ist, kann die Performance von Storage-Array-Operationen mit weniger Konflikten schneller erfolgen.

+
Um einen Pool manuell zu erstellen, wählen Sie *Speicher* und dann *Pools & Volume Groups*. Klicken Sie auf der Registerkarte Alle Kapazitäten auf Menü:Create[Pool].

* Wenn mehrere Pools desselben Laufwerkstyps vorhanden sind, wird eine Meldung angezeigt, dass System Manager die Laufwerke nicht automatisch für einen Pool empfehlen kann. Sie können die Laufwerke jedoch manuell einem vorhandenen Pool hinzufügen.
+
So fügen Sie manuell Laufwerke zu einem vorhandenen Pool hinzu: Wählen Sie auf der Seite Pools & Volume Groups den Pool aus und klicken Sie dann auf *Add Capacity*.





== Warum sind Kapazitätswarnungen wichtig?

Kapazitätswarnungen geben an, wann Laufwerke zu einem Pool hinzugefügt werden sollen. Ein Pool benötigt ausreichend freie Kapazität, um Storage-Array-Vorgänge erfolgreich durchzuführen. Vermeiden Sie Unterbrechungen dieser Vorgänge, indem Sie SANtricity System Manager so konfigurieren, dass Warnmeldungen gesendet werden, wenn die freie Kapazität eines Pools einen bestimmten Prozentsatz erreicht oder überschreitet.

Sie legen diesen Prozentsatz fest, wenn Sie einen Pool mit der Option *Pool Auto-Configuration* oder mit der Option *Pool erstellen* erstellen. Wenn Sie die Option automatisch wählen, bestimmen die Standardeinstellungen automatisch, wann Sie Benachrichtigungen erhalten. Wenn Sie den Pool manuell erstellen möchten, können Sie die Benachrichtigungseinstellungen festlegen oder die Standardeinstellungen übernehmen. Sie können diese Einstellungen später im Menü:Einstellungen[Warnungen] anpassen.

[NOTE]
====
Wenn die freie Kapazität im Pool den angegebenen Prozentsatz erreicht, wird eine Warnmeldung mit der Methode gesendet, die Sie in der Warnungskonfiguration angegeben haben.

====


== Warum kann ich meine Konservierungskapazität nicht erhöhen?

Wenn Sie Volumes auf allen verfügbaren nutzbaren Kapazitäten erstellt haben, können Sie die dauerhafte Kapazität möglicherweise nicht erhöhen.

Bei der Festplattenkapazität wird die in einem Pool reservierte Kapazität zur Unterstützung potenzieller Laufwerksausfälle angegeben. Wenn ein Pool erstellt wird, reserviert das System abhängig von der Anzahl der Laufwerke im Pool automatisch eine standardmäßige Anlagenkapazität. Falls Sie Volumes auf allen verfügbaren nutzbaren Kapazitäten erstellt haben, können Sie die dauerhafte Kapazität auch nicht vergrößern, wenn Sie die Kapazität zum Pool erweitern, indem Sie Laufwerke hinzufügen oder Volumes löschen.

Sie können die Erhaltungskapazität aus *Pools & Volume Groups* ändern. Wählen Sie den Pool aus, den Sie bearbeiten möchten. Klicken Sie auf *Einstellungen anzeigen/bearbeiten* und wählen Sie dann die Registerkarte *Einstellungen*.

[NOTE]
====
Die dauerhafte Kapazität wird als eine Reihe von Laufwerken festgelegt, auch wenn die tatsächliche Festplattenkapazität auf den Laufwerken im Pool verteilt ist.

====


== Ist die Anzahl der Laufwerke, die ich aus einem Pool entfernen kann, begrenzt?

SANtricity System Manager legt Grenzwerte für die Anzahl der Laufwerke fest, die aus einem Pool entfernt werden können.

* Sie können die Anzahl der Laufwerke in einem Pool nicht auf weniger als 11 Laufwerke reduzieren.
* Laufwerke können nicht entfernt werden, wenn nicht genügend freie Kapazität im Pool vorhanden ist, um die Daten von den entfernten Laufwerken zu enthalten, wenn diese Daten auf die übrigen Laufwerke im Pool verteilt werden.
* Sie können maximal 60 Laufwerke gleichzeitig entfernen. Wenn Sie mehr als 60 Laufwerke auswählen, ist die Option Laufwerke entfernen deaktiviert. Wenn Sie mehr als 60 Laufwerke entfernen müssen, wiederholen Sie den Vorgang zum Entfernen von Laufwerken.




== Welche Medientypen werden für ein Laufwerk unterstützt?

Die folgenden Medientypen werden unterstützt: Festplattenlaufwerk (HDD) und Solid State Disk (SSD).



== Warum werden einige Laufwerke nicht angezeigt?

Im Dialogfeld Kapazität hinzufügen stehen nicht alle Laufwerke zur Verfügung, um einem vorhandenen Pool oder einer Volume-Gruppe Kapazität hinzuzufügen.

Festplatten können aus den folgenden Gründen nicht genutzt werden:

* Ein Laufwerk muss nicht zugewiesen und nicht sicher aktiviert sein. Laufwerke, die bereits zu einem anderen Pool, einer anderen Volume-Gruppe oder als Hot Spare konfiguriert sind, sind nicht berechtigt. Wenn ein Laufwerk nicht zugewiesen, aber sicher aktiviert ist, müssen Sie dieses Laufwerk manuell löschen, damit es in Frage kommt.
* Ein Laufwerk in einem nicht optimalen Zustand ist nicht berechtigt.
* Wenn die Kapazität eines Laufwerks zu klein ist, ist es nicht förderfähig.
* Der Laufwerkstyp muss innerhalb eines Pools oder einer Volume-Gruppe übereinstimmen. Sie können Folgendes nicht mischen:
+
** Festplattenlaufwerke (HDDs) mit Solid State Disks (SSDs)
** NVMe mit SAS-Laufwerken
** Laufwerke mit 512 Byte und 4 KiB Volume-Blockgrößen


* Wenn ein Pool oder eine Volume-Gruppe alle sicheren Laufwerke enthält, werden nicht sichere Laufwerke nicht aufgelistet.
* Wenn eine Pool- oder Volume-Gruppe alle FIPS-Laufwerke (Federal Information Processing Standards) enthält, werden Laufwerke außerhalb von FIPS nicht aufgeführt.
* Wenn ein Pool oder eine Volume-Gruppe alle Data Assurance (da)-fähigen Laufwerke enthält und mindestens ein da-fähiges Volume im Pool oder in der Volume-Gruppe vorhanden ist, kann ein Laufwerk, das nicht für da geeignet ist, nicht zugelassen werden, sodass es diesem Pool oder dieser Volume-Gruppe nicht hinzugefügt werden kann. Wenn jedoch kein da-fähiges Volume im Pool oder in der Volume-Gruppe vorhanden ist, kann ein Laufwerk, das nicht über da-fähig ist, zu diesem Pool oder dieser Volume-Gruppe hinzugefügt werden. Wenn Sie sich für eine Kombination dieser Laufwerke entscheiden, sollten Sie bedenken, dass keine da-fähigen Volumes erstellt werden können.


[NOTE]
====
Die Kapazität kann im Speicher-Array erhöht werden, indem neue Laufwerke hinzugefügt oder Pools oder Volume-Gruppen gelöscht werden.

====


== Wie kann ich den Schutz vor Shelf-/Schubladenverlust aufrechterhalten?

Verwenden Sie die in der folgenden Tabelle aufgeführten Kriterien, um den Schutz vor Shelf-/Schubladenverlusten für einen Pool oder eine Volume-Gruppe zu erhalten.

[cols="1a,1a,1a"]
|===
| Ebene | Kriterien für den Schutz vor Shelf-/Schubladenverlust | Mindestanzahl der benötigten Regale/Schubladen 


 a| 
Pool
 a| 
Bei Shelfs darf der Pool nicht mehr als zwei Laufwerke in einem einzelnen Shelf enthalten.

Bei Schubladen muss der Pool eine gleiche Anzahl von Laufwerken von jeder Schublade enthalten.
 a| 
6 für Shelves

5 für Schubladen



 a| 
RAID 6
 a| 
Die Volume-Gruppe enthält nicht mehr als zwei Laufwerke in einem einzelnen Shelf oder einer einzelnen Schublade.
 a| 
3



 a| 
RAID 3 oder RAID 5
 a| 
Jedes Laufwerk in der Volume-Gruppe befindet sich in einem separaten Shelf oder einer separaten Schublade.
 a| 
3



 a| 
RAID 1
 a| 
Jedes Laufwerk in einem gespiegelten Paar muss sich in einem eigenen Shelf oder einer separaten Schublade befinden.
 a| 
2



 a| 
RAID 0
 a| 
Schutz vor Shelf-/Schubladenverlust kann nicht erreicht werden.
 a| 
Keine Angabe

|===
[NOTE]
====
Der Schutz vor Shelf-/Schubladenverlust bleibt nicht erhalten, wenn ein Laufwerk bereits in dem Pool oder der Volume-Gruppe ausgefallen ist. Geht in dieser Situation der Zugriff auf ein Festplatten-Shelf oder eine Laufwerksschublade verloren und somit ein weiteres Laufwerk im Pool bzw. der Volume-Gruppe, geht es zu Datenverlusten.

====


== Wie sieht die optimale Laufwerkspositionierung von Pools und Volume-Gruppen aus?

Achten Sie beim Erstellen von Pools und Volume-Gruppen darauf, die Laufwerkauswahl zwischen den oberen und unteren Laufwerksschächten auszugleichen.

Bei den EF600- und EF300-Controllern werden die Laufwerksschächte 0-11 mit einer PCI-Bridge verbunden, die Steckplätze 12-23 sind mit einer anderen PCI-Bridge verbunden. Um eine optimale Leistung zu erzielen, sollten Sie die Laufwerksauswahl auf eine ungefähr gleiche Laufwerksanzahl von den oberen und unteren Steckplätzen ausbalancieren. Durch diese Positionierung wird sichergestellt, dass Ihre Volumen nicht früher als nötig auf ein Bandbreitenlimit treffen.



== Welches RAID-Level eignet sich am besten für meine Applikation?

Um die Performance einer Volume-Gruppe zu maximieren, müssen Sie den entsprechenden RAID-Level auswählen. Sie können den entsprechenden RAID-Level ermitteln, indem Sie die Prozentsätze für Lese- und Schreibvorgänge für die Anwendungen kennen, die auf die Volume-Gruppe zugreifen. Verwenden Sie die Seite Performance, um diese Prozentsätze zu erhalten.



=== RAID-Level und Applikations-Performance

RAID verwendet eine Reihe von Konfigurationen, die sogenannten _Level_, um zu ermitteln, wie Benutzer- und Redundanzdaten von den Laufwerken geschrieben und abgerufen werden. Jedes RAID-Level stellt eigene Performance-Funktionen bereit. Applikationen mit einem hohen Prozentsatz für Lesevorgänge können aufgrund der hervorragenden Lese-Performance der RAID 5- und RAID 6-Konfigurationen auch mit RAID 5-Volumes oder RAID 6-Volumes arbeiten.

Applikationen mit einem niedrigen Read-Prozentsatz (schreibintensiv) erbringen keine gute Performance auf RAID 5 Volumes oder RAID 6 Volumes. Die Performance ist beeinträchtigt, und das Ergebnis ist die Art und Weise, wie ein Controller Daten und Redundanzdaten auf die Laufwerke in einer RAID 5-Volume-Gruppe oder einer RAID 6-Volume-Gruppe schreibt.

Wählen Sie basierend auf den folgenden Informationen einen RAID-Level aus.

*RAID 0*

* *Beschreibung*
+
** Nicht-redundant, Striping-Modus.


* *Wie es funktioniert*
+
** RAID 0 verteilt Daten auf alle Laufwerke der Volume-Gruppe.


* *Datenschutzfunktionen*
+
** RAID 0 wird für hohe Verfügbarkeitsanforderungen nicht empfohlen. RAID 0 ist besser für nicht-kritische Daten.
** Wenn ein einzelnes Laufwerk in der Volume-Gruppe ausfällt, fallen alle zugehörigen Volumes aus und alle Daten gehen verloren.


* *Anforderungen an die Fahrnummer*
+
** Für RAID-Level 0 ist mindestens ein Laufwerk erforderlich.
** RAID 0-Volume-Gruppen können mehr als 30 Laufwerke haben.
** Sie können eine Volume-Gruppe erstellen, die alle Laufwerke im Speicher-Array umfasst.




*RAID 1 oder RAID 10*

* *Beschreibung*
+
** Striping/Mirror-Modus.


* *Wie es funktioniert*
+
** RAID 1 verwendet die Festplattenspiegelung, um Daten auf zwei doppelte Festplatten gleichzeitig zu schreiben.
** RAID 10 nutzt Laufwerk-Striping, um Daten über eine Reihe gespiegelter Laufwerkpaare zu verteilen.


* *Datenschutzfunktionen*
+
** RAID 1 und RAID 10 bieten eine hohe Performance und eine beste Datenverfügbarkeit.
** RAID 1 und RAID 10 verwenden die Laufwerkspiegelung, um eine exakte Kopie von einem Laufwerk auf ein anderes Laufwerk zu erstellen.
** Fällt eines der Laufwerke in einem Laufwerkspaar aus, kann das Storage-Array sofort auf ein anderes Laufwerk umschalten, ohne dass Daten oder Service verloren gehen.
** Ein Ausfall eines Laufwerks führt dazu, dass zugehörige Volumes beeinträchtigt werden. Das Spiegellaufwerk ermöglicht den Zugriff auf die Daten.
** Ein Laufwerkausfall in einer Volume-Gruppe führt zu einem Ausfall aller damit verbundenen Volumes und es kann zu einem Datenverlust kommen.


* *Anforderungen an die Fahrnummer*
+
** Für RAID 1 sind mindestens zwei Laufwerke erforderlich: Ein Laufwerk für die Benutzerdaten und ein Laufwerk für die gespiegelten Daten.
** Wenn Sie vier oder mehr Laufwerke auswählen, wird RAID 10 automatisch für die gesamte Volume-Gruppe konfiguriert: Zwei Laufwerke für Benutzerdaten und zwei Laufwerke für die gespiegelten Daten.
** Sie müssen eine gerade Anzahl von Laufwerken in der Volume-Gruppe haben. Wenn Sie nicht über eine gerade Anzahl von Laufwerken verfügen und noch einige nicht zugewiesene Laufwerke haben, gehen Sie zu *Pools & Volume Groups*, um der Volume-Gruppe zusätzliche Laufwerke hinzuzufügen, und wiederholen Sie den Vorgang.
** RAID 1- und RAID 10-Volume-Gruppen können mehr als 30 Laufwerke haben. Es kann eine Volume-Gruppe erstellt werden, die alle Laufwerke im Storage-Array umfasst.




*RAID 5*

* *Beschreibung*
+
** Hoher I/O-Modus


* *Wie es funktioniert*
+
** Benutzerdaten und redundante Informationen (Parität) werden auf die Laufwerke verteilt.
** Die entsprechende Kapazität eines Laufwerks wird für redundante Informationen verwendet.


* *Datenschutzfunktionen*
+
** Wenn ein einzelnes Laufwerk in einer RAID 5-Volume-Gruppe ausfällt, werden alle zugehörigen Volumes beeinträchtigt. Durch die redundanten Informationen kann weiterhin auf die Daten zugegriffen werden.
** Wenn zwei oder mehr Laufwerke in einer RAID 5-Volume-Gruppe ausfallen, fallen alle damit verbundenen Volumes aus und alle Daten gehen verloren.


* *Anforderungen an die Fahrnummer*
+
** Sie müssen mindestens drei Laufwerke in der Volume-Gruppe haben.
** In der Regel sind Sie auf maximal 30 Laufwerke in der Volume-Gruppe begrenzt.




*RAID 6*

* *Beschreibung*
+
** Hoher I/O-Modus


* *Wie es funktioniert*
+
** Benutzerdaten und redundante Informationen (Dual Parity) werden auf die Laufwerke verteilt.
** Die entsprechende Kapazität von zwei Laufwerken wird für redundante Informationen verwendet.


* *Datenschutzfunktionen*
+
** Wenn ein oder zwei Laufwerke in einer RAID 6-Volume-Gruppe ausfallen, werden alle zugehörigen Volumes beeinträchtigt, aber aufgrund der redundanten Informationen ist es möglich, weiterhin auf die Daten zuzugreifen.
** Wenn drei oder mehr Laufwerke in einer RAID 6-Volume-Gruppe ausfallen, fallen alle damit verbundenen Volumes aus und alle Daten gehen verloren.


* *Anforderungen an die Fahrnummer*
+
** Sie müssen mindestens fünf Laufwerke in der Volume-Gruppe haben.
** In der Regel sind Sie auf maximal 30 Laufwerke in der Volume-Gruppe begrenzt.




[NOTE]
====
Sie können den RAID-Level eines Pools nicht ändern. Die Benutzeroberfläche konfiguriert Pools automatisch als RAID 6.

====


=== RAID-Level und Datensicherung

RAID 1-, RAID 5- und RAID 6-Daten für Schreibredundanz auf den Datenträger für Fehlertoleranz. Bei den Redundanzdaten kann es sich um eine Kopie der Daten (gespiegelt) oder um einen aus den Daten abgeleiteten, fehlerkorrigierenden Code handelt. Bei einem Laufwerksausfall können Sie mithilfe der Redundanzdaten schnell Informationen über das Ersatzlaufwerk wiederherstellen.

Sie konfigurieren eine einzelne RAID-Ebene für eine einzelne Volume-Gruppe. Alle Redundanzdaten der Volume-Gruppe werden innerhalb der Volume-Gruppe gespeichert. Die Kapazität der Volume-Gruppe ist die aggregierte Kapazität der Mitgliedslaufwerke abzüglich der für Redundanzdaten reservierten Kapazität. Die Menge der zur Redundanz benötigten Kapazität hängt vom verwendeten RAID-Level ab.



== Was ist Data Assurance?

Data Assurance (da) implementiert den T10 Protection Information (PI)-Standard. Dies erhöht die Datenintegrität, indem Fehler geprüft und korrigiert werden, die bei der Datenübertragung entlang des I/O-Pfads auftreten können.

Die typische Nutzung der Data Assurance Funktion überprüft den Teil des I/O-Pfads zwischen den Controllern und Laufwerken. DA-Funktionen werden auf Pool- und Volume-Gruppenebene präsentiert.

Wenn diese Funktion aktiviert ist, hängt das Speicherarray die Fehlerprüfungscodes (auch zyklische Redundanzprüfungen oder CRCs genannt) an jeden Datenblock im Volume an. Nach dem Verschieben eines Datenblocks ermittelt das Speicher-Array anhand dieser CRC-Codes, ob während der Übertragung Fehler aufgetreten sind. Potenziell beschädigte Daten werden weder auf Festplatte geschrieben noch an den Host zurückgegeben. Wenn Sie die da-Funktion verwenden möchten, wählen Sie einen Pool oder eine Volume-Gruppe aus, die bei der Erstellung eines neuen Volumes mit der da-Fähigkeit ausgestattet ist (suchen Sie in der Tabelle „da“ neben „da“ und „Volume-Gruppen-Kandidaten“ nach „Ja“).

Stellen Sie sicher, dass Sie diese DA-fähigen Volumes einem Host über eine E/A-Schnittstelle zuweisen, die über eine da-fähige Schnittstelle verfügt. Zu den I/O-Schnittstellen, die da fähig sind, gehören Fibre Channel, SAS, iSCSI über TCP/IP, NVMe/FC, NVMe/IB, NVME/RoCE und iSER over InfiniBand (iSCSI-Erweiterungen für RDMA/IB). DA wird von SRP nicht über InfiniBand unterstützt.



== Was ist sicher-fähig (Drive Security)?

Drive Security ist eine Funktion, die bei Entfernung aus dem Speicher-Array unberechtigten Zugriff auf Daten auf sicheren Laufwerken verhindert. Dabei können es sich entweder um vollständige Festplattenverschlüsselung (Full Disk Encryption, FDE)-Laufwerke oder um FIPS-Laufwerke (Federal Information Processing Standard) handeln.



== Was muss ich über die Erhöhung der reservierten Kapazität wissen?

In der Regel sollten Sie die Kapazität erhöhen, wenn Sie die Warnung erhalten, dass die reservierte Kapazität in Gefahr ist, voll zu werden. Sie können die reservierte Kapazität nur in Schritten von 8 gib erhöhen.

* Sie müssen über ausreichende freie Kapazitäten im Pool oder Volume-Gruppe verfügen, damit diese bei Bedarf erweitert werden kann.
+
Wenn auf einem Pool oder Volume-Gruppen keine freie Kapazität vorhanden ist, können Sie einem Pool oder einer Volume-Gruppe nicht zugewiesene Kapazität in Form nicht verwendeter Laufwerke hinzufügen.

* Das Volume im Pool oder in der Volume-Gruppe muss den optimalen Status aufweisen und darf sich nicht in einem bestimmten Zustand befinden.
* Freie Kapazität muss im Pool bzw. in der Volume-Gruppe vorhanden sein, mit der die Kapazität erhöht werden soll.
* Sie können die reservierte Kapazität für ein schreibgeschütztes Snapshot-Volume nicht erhöhen. Nur Snapshot Volumes mit Lese- und Schreibvorgängen erfordern reservierte Kapazität.


Für Snapshot-Vorgänge beträgt die reservierte Kapazität normalerweise 40 Prozent des Basis-Volumes. Bei asynchronen Spiegelungsvorgängen beträgt die reservierte Kapazität in der Regel 20 Prozent des Basis-Volumes. Verwenden Sie einen höheren Prozentsatz, wenn Sie glauben, dass das Basis-Volume viele Änderungen durchlaufen wird oder wenn die geschätzte Lebensdauer des Kopierservice eines Storage-Objekts sehr lang sein wird.



== Warum kann ich keinen anderen Betrag auswählen, um den ich verringern möchte?

Sie können die reservierte Kapazität nur um den Betrag reduzieren, den Sie zur Steigerung verwendet haben. Reservierte Kapazität für Mitglieder-Volumes kann nur in umgekehrter Reihenfolge entfernt werden, in der sie hinzugefügt wurden.

Sie können die reservierte Kapazität für ein Speicherobjekt nicht verringern, wenn eine der folgenden Bedingungen vorliegt:

* Wenn es sich bei dem Storage-Objekt um ein gespiegeltes Paar-Volume handelt.
* Wenn das Storage-Objekt nur ein Volume für die reservierte Kapazität enthält. Das Storage-Objekt muss mindestens zwei Volumes für die reservierte Kapazität enthalten.
* Wenn es sich bei dem Speicherobjekt um ein deaktiviertes Snapshot-Volume handelt.
* Wenn das Speicherobjekt mindestens ein Snapshot-Image enthält.


Sie können Volumes für die reservierte Kapazität nur in der umgekehrten Reihenfolge entfernen, in der sie hinzugefügt wurden.

Sie können die reservierte Kapazität für ein schreibgeschütztes Snapshot-Volume nicht verringern, da ihm keine zugewiesene Kapazität zur Verfügung steht. Nur Snapshot Volumes mit Lese- und Schreibvorgängen erfordern reservierte Kapazität.



== Warum brauche ich reservierte Kapazität für jedes Member Volume?

Jedes Mitglied-Volume in einer Snapshot-Konsistenzgruppe muss über seine eigene reservierte Kapazität verfügen, um alle Änderungen, die von der Host-Applikation auf dem Basis-Volume vorgenommen wurden, ohne das referenzierte Snapshot-Image der Konsistenzgruppe zu beeinträchtigen. Die reservierte Kapazität ermöglicht der Host-Applikation den Schreibzugriff auf eine Kopie der Daten im Mitglied-Volume, die als Lese- und Schreibzugriff festgelegt ist.

Ein Snapshot-Image für Konsistenzgruppen ist nicht direkt für Hosts zugänglich. Vielmehr wird das Snapshot-Image verwendet, um nur die Daten zu speichern, die vom Basis-Volume erfasst wurden.

Während der Erstellung eines Snapshot Volume für die Konsistenzgruppe, das als Lesen/Schreiben bezeichnet wird, erstellt System Manager für jedes Mitglied-Volume in der Konsistenzgruppe eine reservierte Kapazität. Diese reservierte Kapazität ermöglicht der Host-Applikation den Schreibzugriff auf eine Kopie der Daten im Snapshot Image der Konsistenzgruppe.



== Wie kann ich sämtliche SSD Cache Statistiken anzeigen und interpretieren?

Sie können nominale Statistiken und detaillierte Statistiken für SSD Cache anzeigen. Die Nominalstatistiken sind eine Untergruppe der detaillierten Statistiken.

Die detaillierten Statistiken können nur angezeigt werden, wenn Sie alle SSD-Statistiken zu A exportieren `.csv` Datei: Während Sie die Statistiken überprüfen und interpretieren, beachten Sie, dass einige Interpretationen durch die Prüfung einer Kombination von Statistiken abgeleitet werden.



=== Nominale Statistiken

Um SSD Cache Statistiken anzuzeigen, wählen Sie Menü:Speicher[Pools & Volume Groups]. Wählen Sie den SSD-Cache aus, für den Sie Statistiken anzeigen möchten, und wählen Sie dann Menü:Mehr[Statistik anzeigen]. Die nominalen Statistiken werden im Dialogfeld „View SSD Cache Statistics“ angezeigt.

Die folgende Liste enthält nominale Statistiken, die eine Untermenge der detaillierten Statistiken sind.

[cols="25h,~"]
|===
| Nominale Statistik | Beschreibung 


 a| 
Lese-/Schreibvorgänge
 a| 
Die Gesamtzahl der Host-Lesevorgänge von bzw. Host-Schreibvorgängen auf die SSD Cache-fähigen Volumes. Vergleichen Sie die Lesevorgänge relativ zu den Schreibvorgängen. Für einen effektiven SSD-Cache-Vorgang müssen die Schreibvorgänge größer sein als die Schreibvorgänge. Je mehr das Verhältnis von Lese- zu Schreibzugriffen ist, desto besser der Cache-Betrieb.



 a| 
Cache-Treffer
 a| 
Die Anzahl der Cache-Treffer.



 a| 
Cache-Treffer (%)
 a| 
Abgeleitet aus Cache-Hits / (Lese- + Schreibvorgänge). Der Cache-Trefferprozentsatz sollte im Hinblick auf einen effektiven SSD-Cache-Vorgang mehr als 50 Prozent betragen. Eine kleine Zahl könnte auf mehrere Dinge hinweisen:

* Das Verhältnis von Lese- zu Schreibvorgängen ist zu klein
* Lesezugriffe werden nicht wiederholt
* Cache-Kapazität ist zu klein




 a| 
Cache-Zuweisung (%)
 a| 
Die zugewiesene SSD-Cache-Storage-Menge wird als Prozentsatz des SSD-Cache-Storage ausgedrückt, der für diesen Controller verfügbar ist. Abgeleitet von zugewiesenen Bytes/verfügbaren Bytes. Der Prozentsatz der Cache-Zuweisung wird normalerweise als 100 Prozent angezeigt. Wenn diese Zahl weniger als 100 % beträgt, bedeutet dies, dass entweder der Cache nicht aufgewärmt ist oder die SSD Cache Kapazität größer ist als alle Daten, auf die zugegriffen wird. Im zweiten Fall könnte eine kleinere SSD-Cache-Kapazität das gleiche Performance-Niveau bieten. Beachten Sie, dass dies nicht bedeutet, dass zwischengespeicherte Daten im SSD-Cache gespeichert wurden. Es ist lediglich ein Vorbereitungsschritt, bevor die Daten im SSD-Cache platziert werden können.



 a| 
Cache-Auslastung (%)
 a| 
Die Menge an SSD-Cache-Storage, die Daten von aktivierten Volumes enthält, ausgedrückt als Prozentsatz des zugewiesenen SSD-Cache-Storage. Dieser Wert stellt die Auslastung oder Dichte des SSD-Caches dar, der aus Benutzerdaten-Bytes/zugewiesenen Bytes abgeleitet wird. Die Cache-Auslastung ist in der Regel niedriger als 100 Prozent, vielleicht viel niedriger. Diese Zahl zeigt den Prozentsatz der SSD-Cache-Kapazität an, die mit Cache-Daten gefüllt ist. Diese Zahl ist niedriger als 100 %, da jede Zuweisungseinheit des SSD Cache, der SSD Cache-Block, in kleinere Einheiten unterteilt wird, die als Sub-Blöcke bezeichnet werden und die etwas unabhängig gefüllt werden. Eine höhere Zahl ist im Allgemeinen besser, aber die Leistungssteigerung kann auch bei einer kleineren Zahl signifikant sein.

|===


=== Detaillierte Statistiken

Die detaillierten Statistiken bestehen aus den Nominalstatistiken sowie zusätzlichen Statistiken. Diese zusätzlichen Statistiken werden zusammen mit den nominalen Statistiken gespeichert, werden aber im Gegensatz zu den nominalen Statistiken nicht im Dialogfeld „View SSD Cache Statistics“ angezeigt. Sie können die detaillierten Statistiken nur anzeigen, nachdem Sie die Statistiken auf A exportiert haben `.csv` Datei:

Beim Anzeigen des `.csv` Beachten Sie, dass die detaillierten Statistiken nach den Nominalstatistiken aufgelistet sind:

[cols="25h,~"]
|===
| Detaillierte Statistiken | Beschreibung 


 a| 
Blöcke Werden Gelesen
 a| 
Die Anzahl der Blöcke im Host-Lesezugriff.



 a| 
Schreibblöcke
 a| 
Die Anzahl der Blöcke im Host-Schreibvorgang.



 a| 
Full-Hit-Blöcke
 a| 
Die Anzahl der Blöcke im Cache-Treffer. Die vollständigen Hit-Blöcke geben an, wie viele Blöcke vollständig aus SSD Cache gelesen wurden. Der SSD-Cache bietet nur Vorteile für die Performance bei Vorgängen, die Vollcache-Treffer sind.



 a| 
Teilweise Treffer
 a| 
Die Anzahl der Host-Lesezugriffe, bei denen mindestens ein Block, aber nicht alle Blöcke, im SSD Cache waren. Ein partieller Hit ist ein SSD Cache *miss* wo die Reads vom Basis-Volume erfüllt wurden.



 a| 
Teilweise Treffer - Blöcke
 a| 
Die Anzahl der Blöcke in Teilbestrahungen. Teilweise Cache-Treffer und partielle Cache-Trefferblöcke resultieren aus einem Vorgang, der nur einen Teil seiner Daten im SSD Cache enthält. In diesem Fall muss der Vorgang die Daten aus dem zwischengespeicherten Festplattenlaufwerk (HDD) abrufen. Der SSD-Cache bietet für diese Art von Hit keine Performance-Vorteile. Wenn die Anzahl der teilweise Cachetreffer-Blöcke höher ist als die der Vollcache-Trefferblöcke, könnte ein anderer I/O-Merkmalstyp (Filesystem, Datenbank oder Web-Server) die Performance verbessern. Es wird erwartet, dass es im Vergleich zu Cache-Hits eine größere Anzahl von Teileinsätzen und -Auslassungen gibt, während sich der SSD Cache wärmt.



 a| 
Fehlschläge
 a| 
Die Anzahl der Host-Lesevorgänge, wo sich keine der Blöcke im SSD Cache befanden. Ein Ausfall des SSD-Caches tritt auf, wenn die Lesevorgänge vom Basis-Volume zufrieden waren. Es wird erwartet, dass es im Vergleich zu Cache-Hits eine größere Anzahl von Teileinsätzen und -Auslassungen gibt, während sich der SSD Cache wärmt.



 a| 
Fehlschläge - Blöcke
 a| 
Die Anzahl der Blöcke in Fehlschläge.



 a| 
Ausfüllen Von Aktionen (Host Reads)
 a| 
Die Anzahl der Host-Lesevorgänge, auf denen Daten vom Basis-Volume in den SSD Cache kopiert wurden.



 a| 
Füllen Sie Aktionen (Host-Lesevorgänge) - Blöcke
 a| 
Die Anzahl der Blöcke in den Befüllen-Aktionen (Host-Lesevorgänge).



 a| 
Ausfüllen Von Aktionen (Host-Schreibvorgänge)
 a| 
Die Anzahl der Host-Schreibvorgänge, bei denen Daten vom Basis-Volume in den SSD-Cache kopiert wurden. Die Anzahl der Befüllen-Aktionen (Host-Schreibvorgänge) kann für die Cache-Konfigurationseinstellungen, die den Cache als Folge eines I/O-Vorgangs nicht füllen, Null sein.



 a| 
Befüllen Von Aktionen (Host Writes) - Blöcken
 a| 
Die Anzahl der Blöcke in den Befüllen-Aktionen (Host-Schreibvorgänge).



 a| 
Aktionen Ungültig Machen
 a| 
Die Anzahl der Mal, dass Daten im SSD-Cache ungültig oder entfernt wurden. Für jeden Host-Schreibanforderung, jede Host-Leseanforderung mit Forced Unit Access (FUA), jede Anforderung zur Überprüfung und unter anderen Umständen wird ein nicht validierter Cache-Vorgang durchgeführt.



 a| 
Recyclingmaßnahmen
 a| 
Die Anzahl der Zeiten, in denen der SSD Cache Block für ein anderes Basis-Volume und/oder einen anderen LBA-Bereich (Logical Block Addressing) wiederverwendet wurde. Für einen effektiven Cache-Betrieb muss die Anzahl der Recycles im Vergleich zur kombinierten Anzahl von Lese- und Schreibvorgängen gering sein. Wenn sich die Anzahl der Recycle-Aktionen nahe der kombinierten Anzahl von Lese- und Schreibvorgängen befindet, ist der SSD Cache begeistert. Entweder die Cache-Kapazität muss erhöht werden oder der Workload eignet sich nicht für den Einsatz mit SSD Cache.



 a| 
Verfügbare Bytes
 a| 
Die Anzahl der im SSD-Cache zur Verwendung durch diesen Controller verfügbaren Bytes.



 a| 
Zugewiesene Bytes
 a| 
Die Anzahl der Bytes, die diesem Controller aus dem SSD-Cache zugewiesen wurden. Aus dem SSD-Cache zugewiesene Bytes können leer sein oder Daten aus Basis-Volumes enthalten.



 a| 
Benutzerdaten Bytes
 a| 
Die Anzahl der zugewiesenen Bytes im SSD-Cache, die Daten von Basis-Volumes enthalten. Die verfügbaren Bytes, zugewiesenen Bytes und Benutzerdaten Bytes werden zur Berechnung des prozentualen Cache-Zuordnungsanteils und des Prozentsatzes der Cache-Auslastung verwendet.

|===


== Was ist die Optimierungskapazität für Pools?

SSD-Laufwerke haben eine längere Lebensdauer und eine bessere maximale Schreib-Performance, wenn ein Teil ihrer Kapazität nicht zugewiesen ist.

Bei Laufwerken, die einem Pool zugeordnet sind, besteht nicht zugewiesene Kapazität aus der Erhaltungskapazität eines Pools, der freien Kapazität (nicht von Volumes genutzte Kapazität) und einem Teil der nutzbaren Kapazität, der als zusätzliche Optimierungskapazität zur Verfügung steht. Die zusätzliche Optimierungskapazität stellt ein Mindestmaß an Optimierungskapazität zur Verfügung, indem die nutzbare Kapazität reduziert wird. Somit ist für die Volume-Erstellung nicht verfügbar.

Wenn ein Pool erstellt wird, wird eine empfohlene Optimierungskapazität generiert, die ein ausgewogenes Verhältnis zwischen Performance, Laufwerksabnutzung und verfügbarer Kapazität bietet. Der Schieberegler zusätzliche Optimierung der Kapazität im Dialogfeld „Pooleinstellungen“ ermöglicht die Anpassung der Optimierungskapazität des Pools. Durch das Anpassen des Schiebereglers erhalten Sie eine bessere Performance und längere Lebensdauer der Laufwerke, und zwar auf Kosten der verfügbaren Kapazität oder zusätzlicher verfügbarer Kapazität, und zwar auf Kosten der Leistung und des Verschleißes der Laufwerke.

[NOTE]
====
Der Schieberegler „zusätzliche Optimierung der Kapazität“ ist nur für Speichersysteme EF600 und EF300 verfügbar.

====


== Was ist die Optimierungskapazität für Volume-Gruppen?

SSD-Laufwerke haben eine längere Lebensdauer und eine bessere maximale Schreib-Performance, wenn ein Teil ihrer Kapazität nicht zugewiesen ist.

Bei Laufwerken, die einer Volume-Gruppe zugeordnet sind, besteht nicht zugewiesene Kapazität aus der freien Kapazität einer Volume-Gruppe (nicht von Volumes genutzte Kapazität) und einem Teil der nutzbaren Kapazität, die als Optimierungskapazität zur Verfügung steht. Die zusätzliche Optimierungskapazität stellt ein Mindestmaß an Optimierungskapazität zur Verfügung, indem die nutzbare Kapazität reduziert wird. Somit ist für die Volume-Erstellung nicht verfügbar.

Wenn eine Volume-Gruppe erstellt wird, wird eine empfohlene Optimierungskapazität generiert, die einen Ausgleich zwischen Performance, Laufwerkverschleiß und verfügbarer Kapazität bietet. Mit dem Schieberegler „zusätzliche Optimierung der Kapazität“ im Dialogfeld „Einstellungen der Volume-Gruppe“ können Sie die Optimierungskapazität einer Volume-Gruppe anpassen. Durch das Anpassen des Schiebereglers erhalten Sie eine bessere Performance und längere Lebensdauer der Laufwerke, und zwar auf Kosten der verfügbaren Kapazität oder zusätzlicher verfügbarer Kapazität, und zwar auf Kosten der Leistung und des Verschleißes der Laufwerke.

[NOTE]
====
Der Schieberegler „zusätzliche Optimierung der Kapazität“ ist nur für Speichersysteme EF600 und EF300 verfügbar.

====


== Was ist die Fähigkeit zur Ressourcenbereitstellung?

Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen.

Ein vom Ressourcen bereitgestelltes Volume ist ein Thick Volume in einer SSD-Volume-Gruppe oder einem Pool. Dabei wird bei der Erstellung des Volume die Laufwerkskapazität zugewiesen (dem Volume zugewiesen), die Laufwerksblöcke jedoch aufgehoben (nicht zugewiesen). In einem herkömmlichen Thick Volume werden im Vergleich dazu alle Laufwerkblöcke während der Initialisierung eines Volume im Hintergrund zugeordnet oder zugewiesen, um die Felder für den Schutz der Data Assurance zu initialisieren und die Daten- und RAID-Parität in jedem RAID Stripe konsistent zu gestalten. Bei einem Volume, das für die Ressource bereitgestellt wird, gibt es keine zeitgebundene Hintergrundinitialisierung. Stattdessen wird jeder RAID-Stripe nach dem ersten Schreibvorgang auf einen Volume-Block im Stripe initialisiert.

Über Ressourcen bereitgestellte Volumes werden nur auf SSD-Volume-Gruppen und -Pools unterstützt, wobei alle Laufwerke in der Gruppe oder dem Pool die nicht zugewiesene oder nicht geschriebene DULBE-Fehlerwiederherstellungsfunktion (Logical Block Error Enable) unterstützen. Bei der Erstellung eines Volume mit Ressourcenbereitstellung werden alle dem Volume zugewiesenen Festplattenblöcke wieder zugewiesen (Zuordnung). Zusätzlich können Hosts logische Blöcke im Volume mithilfe des Befehls NVMe Dataset Management oder des Befehls SCSI Unmap ausfindig machen. Die Deallokung von Blöcken kann die SSD-Abnutzung verbessern und die maximale Schreib-Performance erhöhen. Die Verbesserung variiert je nach Modell und Kapazität der Laufwerke.


NOTE: DULBE wird derzeit nicht auf EF300C- oder EF600C-Speicherarrays unterstützt.



== Was muss ich über die Funktion der Ressourcen-bereitgestellten Volumes wissen?

Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen.

Ein vom Ressourcen bereitgestelltes Volume ist ein Thick Volume in einer SSD-Volume-Gruppe oder einem Pool. Dabei wird bei der Erstellung des Volume die Laufwerkskapazität zugewiesen (dem Volume zugewiesen), die Laufwerksblöcke jedoch aufgehoben (nicht zugewiesen). In einem herkömmlichen Thick Volume werden im Vergleich dazu alle Laufwerkblöcke während der Initialisierung eines Volume im Hintergrund zugeordnet oder zugewiesen, um die Felder für den Schutz der Data Assurance zu initialisieren und die Daten- und RAID-Parität in jedem RAID Stripe konsistent zu gestalten. Bei einem Volume, das für die Ressource bereitgestellt wird, gibt es keine zeitgebundene Hintergrundinitialisierung. Stattdessen wird jeder RAID-Stripe nach dem ersten Schreibvorgang auf einen Volume-Block im Stripe initialisiert.

Über Ressourcen bereitgestellte Volumes werden nur auf SSD-Volume-Gruppen und -Pools unterstützt, wobei alle Laufwerke in der Gruppe oder dem Pool die nicht zugewiesene oder nicht geschriebene DULBE-Fehlerwiederherstellungsfunktion (Logical Block Error Enable) unterstützen. Bei der Erstellung eines Volume mit Ressourcenbereitstellung werden alle dem Volume zugewiesenen Festplattenblöcke wieder zugewiesen (Zuordnung). Zusätzlich können Hosts logische Blöcke im Volume mithilfe des Befehls NVMe Dataset Management oder des Befehls SCSI Unmap ausfindig machen. Die Deallokung von Blöcken kann die SSD-Abnutzung verbessern und die maximale Schreib-Performance erhöhen. Die Verbesserung variiert je nach Modell und Kapazität der Laufwerke.

Die Ressourcenbereitstellung ist standardmäßig auf Systemen aktiviert, auf denen die Laufwerke DULBE unterstützen. Sie können diese Standardeinstellung über *Pools & Volume Groups* deaktivieren.


NOTE: DULBE wird derzeit nicht auf EF300C- oder EF600C-Speicherarrays unterstützt.
