---
permalink: sm-storage/faq-storage-array-settings.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= FAQ zu Speicherarrayeinstellungen für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Was ist der automatische Lastausgleich?

Die Funktion „Automatischer Lastausgleich“ bietet einen automatischen I/O-Ausgleich und stellt sicher, dass eingehender I/O-Datenverkehr von den Hosts auf beiden Controllern dynamisch verwaltet und ausgeglichen wird.

Die Funktion Automatic Load Balancing bietet ein verbessertes I/O-Ressourcenmanagement, das dynamisch auf Laständerungen im Laufe der Zeit reagiert und die Eigentümerschaft der Volume-Controller automatisch angepasst wird, um Probleme bei der Lastverteilung, die zwischen den Controllern verschoben werden, zu beheben.

Die Auslastung jedes Controllers wird kontinuierlich überwacht und, zusammen mit den auf den Hosts installierten Multipath-Treibern, kann bei Bedarf automatisch ausgeglichen werden. Wenn die Workload automatisch auf die Controller umverteilt wird, entlastet der Storage-Administrator die manuelle Anpassung der Eigentümerschaft der Volume Controller, um Laständerungen am Storage Array zu bewältigen.

Wenn der automatische Lastenausgleich aktiviert ist, führt er folgende Funktionen aus:

* Automatische Überwachung und ausgewogene Nutzung von Controller-Ressourcen
* Bei Bedarf passt die Volume-Controller-Eigentümerschaft automatisch an, was die I/O-Bandbreite zwischen Hosts und Storage Array optimiert.


[NOTE]
====
Jedes Volume, das der Nutzung des SSD-Caches eines Controllers zugewiesen ist, kann keine automatische Lastverteilung durchführen.

====


== Was ist der Controller Cache?

Der Controller-Cache ist ein physischer Speicherplatz, der zwei Arten von I/O-Vorgängen (Input/Output) vereinfacht: Zwischen den Controllern und Hosts sowie zwischen den Controllern und Festplatten.

Beim Lesen und Schreiben von Datentransfers kommunizieren die Hosts und Controller über High-Speed-Verbindungen. Die Kommunikation zwischen dem Backend des Controllers und den Festplatten ist jedoch langsamer, da die Festplatten relativ langsam sind.

Wenn der Controller-Cache Daten erhält, bestätigt der Controller den Host-Applikationen, dass er jetzt die Daten hält. Auf diese Weise müssen die Host-Applikationen nicht warten, bis der I/O auf die Festplatte geschrieben wird. Stattdessen können Applikationen den Betrieb fortsetzen. Auf die im Cache gespeicherten Daten können zudem von Server-Applikationen schnell zugegriffen werden, sodass kein zusätzliches Lesen von Festplatten erforderlich ist, um auf die Daten zuzugreifen.

Der Controller-Cache wirkt sich auf die Gesamt-Performance des Storage Arrays aus:

* Der Cache fungiert als Puffer, sodass die Übertragung von Host- und Festplattendaten nicht synchronisiert werden muss.
* Die Daten eines Lese- oder Schreibvorgangs vom Host befinden sich möglicherweise im Cache eines vorherigen Vorgangs, sodass kein Zugriff auf die Festplatte erforderlich ist.
* Bei Verwendung von Schreib-Caching kann der Host nachfolgende Schreibbefehle senden, bevor die Daten eines früheren Schreibvorgangs auf die Festplatte geschrieben werden.
* Wenn Cache-Prefetch aktiviert ist, wird der sequenzielle Lesezugriff optimiert. Cache Prefetch sorgt für einen Lesevorgang, bei dem die Daten im Cache gefunden werden, anstatt die Daten von der Festplatte zu lesen.


[CAUTION]
====
*Möglicher Datenverlust* -- Wenn Sie die *Write Caching ohne Batterien* Option aktivieren und keine universelle Stromversorgung zum Schutz haben, könnten Sie Daten verlieren. Darüber hinaus könnten Sie Daten verlieren, wenn Sie keine Controller-Batterien haben und Sie die Option *Write Caching ohne Batterien* aktivieren.

====


== Was wird Cachespülung?

Wenn die Menge der nicht geschriebenen Daten im Cache eine bestimmte Ebene erreicht, schreibt der Controller regelmäßig Cache-Daten auf ein Laufwerk. Dieser Schreibvorgang wird als „Spülen“ bezeichnet.

Der Controller verwendet zwei Algorithmen für das Spülen von Cache: Bedarfsbasiert und altersbasiert. Der Controller verwendet einen bedarfsorientierten Algorithmus, bis die Menge der im Cache gespeicherten Daten unter den Schwellenwert für die Cache-Spülung fällt. Standardmäßig beginnt ein Flush, wenn 80 Prozent des Caches verwendet werden.

In System Manager können Sie den Schwellenwert für „`Start Demand Cache Flush`“ festlegen, um den in Ihrer Umgebung verwendeten I/O-Typ optimal zu unterstützen. In einer Umgebung, in der hauptsächlich Schreibvorgänge ausgeführt werden, sollten Sie den „`Start Demand Cache Flush`“-Prozentsatz hoch einstellen, um die Wahrscheinlichkeit zu erhöhen, dass neue Schreibanforderungen durch den Cache verarbeitet werden können, ohne auf die Festplatte gehen zu müssen. Eine Einstellung mit hohem Prozentsatz begrenzt die Anzahl der Cache-Flushes, so dass mehr Daten im Cache verbleiben, was die Wahrscheinlichkeit von mehr Cache-Treffern erhöht.

In einer Umgebung, in der der I/O unregelmäßig ist (bei sprunghaften Datenanbrüchen), können Sie geringe Cache-Schreibvorgänge verwenden, sodass das System häufig zwischen Datenstoßweisen den Cache-Speicher stürzt. In einer vielfältigen I/O-Umgebung, die eine Vielzahl von Lasten verarbeitet, oder wenn die Lasttypen unbekannt sind, setzen Sie den Schwellenwert auf 50 Prozent als guter Mittelweg. Wenn Sie einen Startprozentsatz unter 80 Prozent wählen, können Sie eine verminderte Leistung feststellen, da die Daten für einen Host-Lesevorgang möglicherweise nicht verfügbar sind. Wird ein niedrigerer Prozentsatz ausgewählt, erhöht sich auch die Anzahl der Festplattenschreibvorgänge, die zur Aufrechterhaltung des Cache-Levels erforderlich sind, was den System-Overhead erhöht.

Der altersbasierte Algorithmus legt fest, wie lange die Schreibvorgänge im Cache verbleiben können, bevor sie auf die Festplatten gespeichert werden können. Die Controller verwenden den altersbasierten Algorithmus, bis der Schwellenwert für den Cache-Spülvorgang erreicht ist. Der Standardwert beträgt 10 Sekunden, dieser Zeitraum wird jedoch nur in Zeiten der Inaktivität gezählt. Sie können den Spülzeitpunkt in System Manager nicht ändern. Stattdessen müssen Sie den Befehl *Set Storage Array* in der Befehlszeilenschnittstelle (CLI) verwenden.

[CAUTION]
====
*Möglicher Datenverlust* -- Wenn Sie die *Write Caching ohne Batterien* Option aktivieren und keine universelle Stromversorgung zum Schutz haben, könnten Sie Daten verlieren. Darüber hinaus könnten Sie Daten verlieren, wenn Sie keine Controller-Batterien haben und Sie die Option *Write Caching ohne Batterien* aktivieren.

====


== Was ist die Cache-Blockgröße?

Der Controller des Storage Arrays ordnet den Cache in „Blöcke“ ein. Dabei handelt es sich um Speicherblöcke, die 8, 16 und 32 KiB groß sein können. Alle Volumes im Storage-System nutzen denselben Cache-Speicherplatz. Daher können die Volumes nur eine Cache-Blockgröße aufweisen.

Applikationen verwenden unterschiedliche Blockgrößen, die wiederum einen Einfluss auf die Storage-Performance haben können. Standardmäßig ist die Blockgröße in System Manager 32 KiB, Sie können den Wert jedoch auf 8, 16, 32 KiBs festlegen. Kleinere Größen sind eine gute Wahl für Dateisysteme oder Datenbankanwendungen. Eine größere Größe ist eine gute Wahl für Applikationen, die eine umfangreiche Datenübertragung, sequenziellen I/O oder eine hohe Bandbreite, wie z. B. Multimedia, erfordern.



== Wann sollte ich Speicherarray-Uhren synchronisieren?

Sie sollten die Controller-Uhren im Speicher-Array manuell synchronisieren, wenn Sie bemerken, dass die in SANtricity System Manager angezeigten Zeitstempel nicht auf die im Management-Client angezeigten Zeitstempel ausgerichtet sind (der Computer, der über den Browser auf SANtricity System Manager zugreift). Diese Aufgabe ist nur erforderlich, wenn NTP (Network Time Protocol) im SANtricity-System-Manager nicht aktiviert ist.

[NOTE]
====
Es wird dringend empfohlen, einen NTP-Server zu verwenden, statt die Uhren manuell zu synchronisieren. NTP synchronisiert die Uhren automatisch mit einem externen Server mithilfe von SNTP (Simple Network Time Protocol).

====
Sie können den Synchronisierungsstatus über das Dialogfeld Speicherarray-Uhren synchronisieren überprüfen, das auf der Seite System verfügbar ist. Wenn die im Dialogfeld angezeigten Zeiten nicht übereinstimmen, führen Sie eine Synchronisierung aus. Sie können dieses Dialogfeld in regelmäßigen Abständen anzeigen, in dem angezeigt wird, ob die Zeitanzeigen der Controller-Uhren auseinander getrieben wurden und nicht mehr synchronisiert sind.
