---
permalink: sm-storage/how-volumes-are-assigned-to-hosts-and-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, assigned, hosts, clusters 
summary: Damit ein Host oder Host-Cluster I/O an ein Volume sendet, müssen Sie das Volume dem Host oder Host-Cluster zuweisen. 
---
= Wie Volumes Hosts und Host-Clustern zugewiesen werden
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Damit ein Host oder Host-Cluster I/O an ein Volume sendet, müssen Sie das Volume dem Host oder Host-Cluster zuweisen.

Sie können einen Host oder Host-Cluster auswählen, wenn Sie ein Volume erstellen oder ein Volume später einem Host oder Host-Cluster zuweisen. Ein Host-Cluster ist eine Gruppe von Hosts. Sie erstellen ein Host-Cluster, damit Sie mehrere Hosts dieselben Volumes ganz einfach zuweisen können.

Das Zuweisen von Volumes zu Hosts ist flexibel und somit an Ihre spezifischen Storage-Anforderungen angepasst.

* *Stand-alone Host, nicht Teil eines Host Clusters* -- Sie können ein Volume einem einzelnen Host zuweisen. Auf das Volume kann nur von einem Host zugegriffen werden.
* *Host Cluster* -- Sie können ein Volume einem Host-Cluster zuweisen. Auf das Volume kann von allen Hosts im Host-Cluster zugegriffen werden.
* *Host innerhalb eines Host-Clusters* -- Sie können ein Volume einem einzelnen Host zuweisen, der Teil eines Host-Clusters ist. Obwohl der Host Teil eines Host Clusters ist, kann das Volume nur vom individuellen Host und nicht von anderen Hosts im Host-Cluster abgerufen werden.


Bei Erstellung von Volumes werden automatisch LUNs (Logical Unit Numbers) zugewiesen. Die LUN dient während I/O-Vorgängen als „Adresse“ zwischen dem Host und dem Controller. Sie können LUNs nach der Erstellung des Volume ändern.
