---
permalink: sm-storage/how-workloads-work.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, application, workloads, volume, 
summary: Wenn Sie ein Volume erstellen, wählen Sie einen Workload aus, um die Storage-Array-Konfiguration für eine bestimmte Applikation anzupassen. 
---
= So funktionieren Workloads in der SANtricity-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie ein Volume erstellen, wählen Sie einen Workload aus, um die Storage-Array-Konfiguration für eine bestimmte Applikation anzupassen.

Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren.



== Erstellen einer Arbeitslast

Sie müssen manuell angeben, wann Sie eine Arbeitslast erstellen möchten, die keiner bestimmten Anwendung zugeordnet ist. Sie müssen auch die Volume-Konfiguration manuell über die Seite „Volumes hinzufügen“ angeben.



== Anzeige von Applikationen und Workloads

Um Anwendungen und Workloads anzuzeigen, starten Sie SANtricity System Manager. Über diese Schnittstelle können Sie die Informationen anzeigen, die mit einem applikationsspezifischen Workload verknüpft sind. Sie haben verschiedene Möglichkeiten:

* Sie können auf der Seite „Volumes“ die Registerkarte *Anwendungen und Workloads* auswählen, um die Volumes des Speicherarrays gruppiert nach Workload und dem Anwendungstyp, dem der Workload zugeordnet ist, anzuzeigen.
* Sie können auf der Seite „Leistung“ die Registerkarte *Applications and workloads* auswählen, um Leistungskennzahlen (Latenz, IOPS und MBs) für logische Objekte anzuzeigen. Die Objekte sind nach Anwendung und zugehörigem Workload gruppiert. Durch das Sammeln dieser Leistungsdaten in regelmäßigen Abständen können Sie Basiswerte ermitteln und Trends analysieren, was hilfreich sein kann, wenn Sie Probleme im Zusammenhang mit der I/O-Leistung untersuchen.

