---
permalink: sm-storage/increase-capacity-of-a-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, capacity, volume 
summary: 'Sie können die gemeldete Kapazität (die gemeldete Kapazität an Hosts) eines Volumes erhöhen, indem Sie die freie Kapazität nutzen, die in dem Pool bzw. der Volume-Gruppe verfügbar ist.' 
---
= Erhöhen Sie die Kapazität eines Volumes im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die gemeldete Kapazität (die gemeldete Kapazität an Hosts) eines Volumes erhöhen, indem Sie die freie Kapazität nutzen, die in dem Pool bzw. der Volume-Gruppe verfügbar ist.

.Bevor Sie beginnen
* Im zugewiesenen Pool bzw. der Volume-Gruppe des Volumes steht genügend freie Kapazität zur Verfügung.
* Das Volume ist optimal und nicht in einem Zustand der Änderung.
* Die maximale gemeldete Kapazität von 256 tib wurde für Thin-Volumes nicht erreicht.
* Im Volume werden keine Hot-Spare-Laufwerke verwendet. (Gilt nur für Volumes in Volume-Gruppen.)



NOTE: Sie können die Volume-Kapazität nur auf bis zu 128 tib gleichzeitig erweitern.

.Über diese Aufgabe
Bedenken Sie zukünftige Kapazitätsanforderungen für andere Volumes in diesem Pool oder Volume-Gruppe. Stellen Sie sicher, dass ausreichend freie Kapazität zur Erstellung von Snapshot-Images, Snapshot-Volumes oder Remote-Spiegelungen zur Verfügung steht.

[NOTE]
====
Eine Erhöhung der Kapazität eines Volumens wird nur auf bestimmten Betriebssystemen unterstützt. Wenn Sie die Volume-Kapazität auf einem nicht unterstützten Host-Betriebssystem erhöhen, kann die erweiterte Kapazität nicht verwendet werden, und Sie können die ursprüngliche Volume-Kapazität nicht wiederherstellen.

====
.Schritte
. Wählen Sie im linken Bereich Menü:Storage[Volumes].
. Wählen Sie das Volume aus, dessen Kapazität Sie erhöhen möchten, und klicken Sie dann auf das Menü:Ellipsen-Symbol[Kapazität erhöhen].
+
Die Seite „Kapazitätserhöhung bestätigen“ wird angezeigt.

. Wählen Sie *Ja*, um fortzufahren.
+
Die Seite „Increase Reported Capacity“ wird angezeigt.

+
Auf dieser Seite werden die aktuell gemeldete Kapazität des Volumes und die im zugehörigen Pool oder der Volume-Gruppe verfügbare freie Kapazität angezeigt.

. Verwenden Sie das Feld *Erhöhen Sie die gemeldete Kapazität durch Hinzufügen von...*, um Kapazität zur aktuell verfügbaren gemeldeten Kapazität hinzuzufügen. Sie können den Kapazitätswert so ändern, dass er entweder in Mebibyte (MiB), Gibibyte (GiB) oder Tebibyte (TiB) angezeigt wird.
. Klicken Sie Auf *Erhöhen*.


.Ergebnisse
* System Manager erhöht die Kapazität des Volumes basierend auf Ihrer Auswahl.
* Wählen Sie Menü:Storage[Operations in Progress], um den Fortschritt der aktuell laufenden Kapazitätserweiterung für das ausgewählte Volume anzuzeigen. Dieser Vorgang kann längere Zeit dauern und die Systemleistung beeinträchtigen.


.Nachdem Sie fertig sind
Nachdem Sie die Volume-Kapazität erweitert haben, müssen Sie die Größe des Dateisystems manuell erhöhen, um sie anzupassen. Wie Sie dies tun, hängt von dem Dateisystem ab, das Sie verwenden. Weitere Informationen finden Sie in der Dokumentation Ihres Host-Betriebssystems.
