---
permalink: sm-storage/initialize-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, initialize, volumes 
summary: Ein Volume wird beim ersten Erstellen automatisch initialisiert. Möglicherweise empfiehlt der Recovery Guru jedoch, ein Volume manuell zu initialisieren, um eine Wiederherstellung nach bestimmten Fehlerbedingungen durchzuführen. Verwenden Sie diese Option nur unter Anleitung des technischen Supports. Sie können ein oder mehrere Volumes für die Initialisierung auswählen. 
---
= Volumes initialisieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Volume wird beim ersten Erstellen automatisch initialisiert. Möglicherweise empfiehlt der Recovery Guru jedoch, ein Volume manuell zu initialisieren, um eine Wiederherstellung nach bestimmten Fehlerbedingungen durchzuführen. Verwenden Sie diese Option nur unter Anleitung des technischen Supports. Sie können ein oder mehrere Volumes für die Initialisierung auswählen.

.Bevor Sie beginnen
* Alle I/O-Vorgänge wurden angehalten.
* Alle Geräte oder Dateisysteme auf den Volumes, die Sie initialisieren möchten, müssen abgehängt werden.
* Das Volume ist optimal und es werden keine Änderungsvorgänge für das Volume ausgeführt.


[CAUTION]
====
Sie können den Vorgang nach dem Start nicht mehr abbrechen. Alle Volume-Daten werden gelöscht. Versuchen Sie diese Operation nur, wenn der Recovery Guru Sie dazu rät. Wenden Sie sich vor Beginn dieses Verfahrens an den technischen Support.

====
.Über diese Aufgabe
Bei der Initialisierung eines Volume bleiben die WWN, Host-Zuweisungen, zugewiesene Kapazität und reservierte Kapazität des Volume erhalten. Zudem werden dieselben Data Assurance (da)-Einstellungen und Sicherheitseinstellungen beibehalten.

Die folgenden Typen von Volumes _kann nicht_ initialisiert werden:

* Basis-Volume eines Snapshot-Volumes
* Primäres Volume in einer Spiegelbeziehung
* Sekundäres Volume in einer Spiegelbeziehung
* Quell-Volume in einer Volume-Kopie
* Ziel-Volume in einer Volume-Kopie
* Volume, für das bereits eine Initialisierung läuft


Dieses Thema bezieht sich nur auf Standard-Volumes, die aus Pools oder Volume-Gruppen erstellt wurden.

.Schritte
. Wählen Sie Menü:Storage[Volumes].
. Wählen Sie ein beliebiges Volume aus, und wählen Sie dann Menü:Mehr[Initialisieren von Volumes].
+
Das Dialogfeld Volumes initialisieren wird angezeigt. In diesem Dialogfeld werden alle Volumes im Speicher-Array angezeigt.

. Wählen Sie ein oder mehrere Volumes aus, die Sie initialisieren möchten, und bestätigen Sie, dass Sie den Vorgang durchführen möchten.


.Ergebnisse
System Manager führt die folgenden Aktionen durch:

* Löscht alle Daten aus den Volumes, die initialisiert wurden.
* Löscht die Blockindizes, was dazu führt, dass nicht geschriebene Blöcke gelesen werden, als ob sie null gefüllt sind (das Volume scheint vollständig leer zu sein).


Wählen Sie MENU:Home[Vorgänge in Bearbeitung anzeigen], um den Fortschritt des Initialisierungsvorgangs anzuzeigen, der derzeit für das ausgewählte Volume ausgeführt wird. Dieser Vorgang kann langwierig sein und die System-Performance beeinträchtigen.
