---
permalink: sm-storage/overview-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remote, storage 
summary: Wenn Sie über die Funktion Remote Storage verfügen, können Sie Daten von einem Remote-Speichersystem importieren. 
---
= Übersicht über die Funktionen von Remote Storage
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie über die Funktion Remote Storage verfügen, können Sie Daten von einem Remote-Speichersystem auf Ihr Speicher-Array importieren.



== Was ist die Remote Storage Funktion?

Die Funktion _Remote Storage_ ermöglicht das Importieren von Daten aus einem Remote Storage-System in ein lokales E-Series Storage-System. Das Remote-System kann ein anderes E-Series System oder ein System eines anderen Anbieters sein. Diese Funktion ist hilfreich, wenn Sie die Datenmigration mit minimalen Ausfallzeiten, z. B. bei Geräte-Upgrades, rationalisieren möchten.


NOTE: Um Remote-Speicher zu verwenden, muss diese Funktion in der Submodell-ID (SMID) aktiviert sein.

Weitere Informationen:

* link:rtv-how-remote-storage-works.html["Funktionsweise von Remote Storage"]
* link:rtv-terminology.html["Remote Storage – Terminologie"]
* link:rtv-remote-storage-requirements.html["Remote-Storage-Anforderungen"]
* link:rtv-remote-storage-volume-requirements.html["Anforderungen für Remote Storage Volumes"]




== Wie importiere ich Daten mit dieser Funktion?

Mit dem Remote Storage Wizard ordnen Sie ein Remote Storage-Gerät (die Quelle für den Datenimport) einem Ziel-Volume auf dem E-Series System zu. Dieser Assistent ist über das Menü:Speicher[Remote-Speicher] verfügbar.

Weitere Informationen:

* link:rtv-import-remote-storage.html["Remote-Speicher importieren"]
* link:rtv-manage-progress-of-remote-volume-import.html["Den Fortschritt des Datenimports managen"]

