---
permalink: sm-storage/remove-member-volumes-from-a-consistency-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, member volume, snapshot, consistency group 
summary: Sie können ein Mitglied-Volume aus einer vorhandenen Snapshot-Konsistenzgruppe entfernen. 
---
= Entfernen eines Mitgliedsvolumes aus einer Snapshot-Konsistenzgruppe im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Mitglied-Volume aus einer vorhandenen Snapshot-Konsistenzgruppe entfernen.

.Über diese Aufgabe
Wenn Sie ein Mitglied-Volume aus einer Snapshot Konsistenzgruppe entfernen, löscht der System Manager automatisch die Snapshot Objekte, die diesem Mitglied-Volume zugeordnet sind.

.Schritte
. Wählen Sie Menü:Storage[Snapshots].
. Klicken Sie auf die Registerkarte *Snapshot Consistency Groups*.
. Erweitern Sie die Snapshot Consistency Group, die Sie ändern möchten, indem Sie das Pluszeichen (+) neben ihr auswählen.
. Wählen Sie das Mitgliedvolume aus, das Sie entfernen möchten, und klicken Sie dann auf *Entfernen*.
. Bestätigen Sie, dass Sie den Vorgang ausführen möchten, und klicken Sie dann auf *Entfernen*.


.Ergebnisse
System Manager führt die folgenden Aktionen durch:

* Löscht alle Snapshot-Images und Snapshot-Volumes, die dem Mitgliedvolume zugeordnet sind.
* Löscht die dem Mitgliedvolume zugeordnete Snapshot-Gruppe.
* Das Mitgliedvolume wird nicht anders geändert oder gelöscht.

