---
permalink: sm-storage/rtv-import-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, import, remote, storage 
summary: Verwenden Sie den Assistenten zum Importieren von Remote Storage, um einen Storage-Import von einem Remote-System auf ein lokales E-Series Storage-System zu initiieren. 
---
= Remote-Speicher importieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie den Assistenten zum Importieren von Remote Storage, um einen Storage-Import von einem Remote-System auf ein lokales E-Series Storage-System zu initiieren.

.Bevor Sie beginnen
* Das E-Series Storage-System muss so konfiguriert sein, dass es mit dem Remote-Storage-System kommunizieren kann.
+
[NOTE]
====
Die Hardwarekonfiguration wird im Benutzerhandbuch zur Remote-Speicherfunktion beschrieben, die im E-Series und im SANtricity Dokumentationszentrum unter verfügbar ist https://docs.netapp.com/us-en/e-series/remote-storage-volumes/setup-remote-volumes-concept.html["Hardware konfigurieren"^], Und im https://www.netapp.com/pdf.html?item=/media/28697-tr-4893-deploy.pdf["Technischer Bericht Zu Remote-Storage"^].

====
* Erfassen Sie für das Remote-Speichersystem die folgenden Informationen:
+
** ISCSI-IQN
** ISCSI-IP-Adressen
** LUN-Nummer des Remote Storage-Geräts (Quell-Volume)


* Erstellen oder wählen Sie für das lokale E-Series Storage-System ein Volume aus, das für den Datenimport verwendet werden soll. Siehe link:create-volumes.html["Volumes erstellen"]. Das Ziel-Volume muss die folgenden Anforderungen erfüllen:
+
** Entspricht der Blockgröße des Remote-Speichergeräts (dem Quell-Volume).
** Verfügt über eine Kapazität, die dem Remote-Speichergerät entspricht oder größer ist.
** Zustand optimal und verfügbar




Eine vollständige Liste der Anforderungen finden Sie unter link:rtv-remote-storage-volume-requirements.html["Anforderungen für Remote Storage-Volumes"].

* *Empfohlen:* Sichern Sie Volumes auf dem Remote-Speichersystem, bevor Sie den Importvorgang starten.


In dieser Aufgabe erstellen Sie eine Zuordnung zwischen dem Remote-Storage-Gerät und einem Volume auf dem lokalen E-Series Storage-System. Wenn Sie die Konfiguration abgeschlossen haben, beginnt der Import.

[NOTE]
====
Da viele Variablen sich auf den Importvorgang und seine Fertigstellungszeit auswirken können, empfehlen wir Ihnen, zuerst kleinere Importe von „`Test`“ durchzuführen. Mit diesen Tests stellen Sie sicher, dass alle Verbindungen wie erwartet funktionieren und dass der Importvorgang in einem angemessenen Zeitraum abgeschlossen wird.

====
.Schritte
. Wählen Sie Menü:Speicher[Remote-Speicher].
. Klicken Sie Auf *Remote Storage Importieren*.
+
Ein Assistent zum Importieren von Remote-Speicher wird angezeigt.

. Geben Sie im Fenster „Quelle konfigurieren“ in *Schritt 1a* die Verbindungsinformationen ein. Wenn Sie eine weitere iSCSI-Verbindung hinzufügen möchten, klicken Sie auf *Weitere IP-Adresse hinzufügen*, um eine zusätzliche IP-Adresse für den Remote-Speicher hinzuzufügen. Wenn Sie fertig sind, klicken Sie auf *Weiter*.
+
.Felddetails
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Name
 a| 
Geben Sie einen Namen für das Remote-Speichergerät ein, um es in der System Manager-Schnittstelle zu identifizieren.

Ein Name kann bis zu 30 Zeichen enthalten und darf nur Buchstaben, Ziffern und die folgenden Sonderzeichen enthalten: Unterstrich (_), Bindestrich (-) und das Hash-Zeichen (#). Ein Name darf keine Leerzeichen enthalten.



 a| 
Eigenschaften der iSCSI-Verbindung
 a| 
Geben Sie die Verbindungseigenschaften des Remote-Speichergeräts ein:

** *ISCSI Qualified Name (IQN)*: Geben Sie den iSCSI-IQN ein.
** *IP-Adresse*: Geben Sie die IPv4-Adresse ein.
** *Port*: Geben Sie die Portnummer ein, die für die Kommunikation zwischen den Quell- und Zielgeräten verwendet werden soll. Standardmäßig ist die Portnummer 3260.


|===
====
+
Nachdem Sie auf *Weiter* geklickt haben, wird der *Schritt 1b* des Bedienfelds Quelle konfigurieren angezeigt.

. Wählen Sie im Feld *LUN* die LUN-Nummer des Remote-Speichergeräts aus, das als Quelle verwendet werden soll, und klicken Sie dann auf *Weiter*.
+
Das Fenster „Ziel konfigurieren“ wird geöffnet und zeigt Volume-Kandidaten an, die als Ziel für den Import dienen sollen. Einige Volumes werden aufgrund von Blockgröße, Kapazität oder Volume-Verfügbarkeit nicht in der Liste der Kandidaten angezeigt.

. Wählen Sie aus der Tabelle ein Ziel-Volume auf dem E-Series Storage-System aus. Verwenden Sie bei Bedarf den Schieberegler, um die Importpriorität zu ändern. Klicken Sie Auf *Weiter*. Bestätigen Sie den Vorgang im nächsten Dialogfeld, indem Sie eingeben `continue`, Und dann auf *Weiter* klicken.
+
Wenn das Ziel-Volume eine Kapazität besitzt, die größer als das Quell-Volume ist, wird diese zusätzliche Kapazität nicht dem mit dem E-Series System verbundenen Host gemeldet. Um die neue Kapazität zu verwenden, müssen Sie auf dem Host nach Abschluss des Importvorgangs eine Dateisystemerweiterung durchführen und die Verbindung trennen.

+
Nachdem Sie die Konfiguration im Dialogfeld bestätigt haben, wird das Fenster Überprüfung angezeigt.

. Überprüfen Sie im Fenster Überprüfung, ob die Einstellungen korrekt sind, und klicken Sie dann auf *Fertig stellen*, um den Import zu starten.
+
Es wird ein weiteres Dialogfeld geöffnet, in dem Sie gefragt werden, ob Sie einen anderen Import starten möchten.

. Klicken Sie bei Bedarf auf *Ja*, um einen anderen Remote-Speicherimport zu erstellen. Wenn Sie auf *Ja* klicken, gelangen Sie zurück zu *Schritt 1a* im Fenster Quelle konfigurieren, wo Sie die vorhandene Konfiguration auswählen oder eine neue hinzufügen können. Wenn Sie keinen weiteren Import erstellen möchten, klicken Sie auf *Nein*, um das Dialogfeld zu schließen.
+
Sobald der Importvorgang beginnt, wird das gesamte Zielvolume mit den kopierten Daten überschrieben. Wenn der Host während dieses Prozesses neue Daten auf das Ziel-Volume schreibt, werden diese neuen Daten wieder an das Remote-Gerät (Quell-Volume) übertragen.

. Zeigen Sie den Fortschritt des Vorgangs im Dialogfeld „Anzeigevorgänge“ im Fenster „Remote-Speicher“ an.


Wie lange der Importvorgang abgeschlossen werden muss, hängt von der Größe des Remote-Speichersystems, der Prioritätseinstellung für den Import und der Menge der I/O-Last auf beiden Storage-Systemen und den zugehörigen Volumes ab.

Nach Abschluss des Imports handelt es sich bei dem lokalen Volume um ein Duplikat des Remote-Speichergeräts.

Wenn Sie bereit sind, die Beziehung zwischen den beiden Volumes zu brechen, wählen Sie im Importobjekt in der Ansicht Operationen in Progress *Disconnect* aus. Sobald die Beziehung getrennt ist, kehrt die Performance des lokalen Volumes wieder in den Normalzustand zurück und wird nicht mehr von der Remote-Verbindung beeinträchtigt.
