---
permalink: sm-storage/rtv-remove-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, remote, storage, 
summary: Nach Abschluss des Imports können Sie ein Remote-Speicherobjekt entfernen, wenn Sie keine Daten mehr zwischen den lokalen und Remote-Geräten kopieren möchten. 
---
= Remote-Storage-Objekt entfernen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nach Abschluss des Imports können Sie ein Remote-Speicherobjekt entfernen, wenn Sie keine Daten mehr zwischen den lokalen und Remote-Geräten kopieren möchten.

Stellen Sie sicher, dass dem Remote-Speicherobjekt, das Sie entfernen möchten, keine Importe zugeordnet sind.

Wenn Sie ein Remote-Speicherobjekt entfernen, werden Verbindungen zwischen den lokalen und den Remote-Geräten entfernt.

.Schritte
. Wählen Sie Menü:Speicher[Remote-Speicher].
. Wählen Sie aus der Liste das Remote-Speicherobjekt aus, das Sie entfernen möchten.
. Klicken Sie Auf *Entfernen*.
+
Das Dialogfeld „Remote-Speicherverbindung bestätigen“ wird angezeigt.

. Bestätigen Sie den Vorgang, indem Sie eingeben `remove` Und dann auf *Entfernen* klicken.
+
Das ausgewählte Remote-Speicherobjekt wird entfernt.


