---
permalink: sm-storage/rtv-modify-connection-settings-for-remote-storage.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, modify, connection, settings, remote, storage 
summary: Über die Option „Einstellungen anzeigen/bearbeiten“ können Sie Verbindungseinstellungen für eine beliebige Remote-Speicherkonfiguration bearbeiten, hinzufügen oder löschen. 
---
= Verbindungseinstellungen für Remote-Speicher ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über die Option „Einstellungen anzeigen/bearbeiten“ können Sie Verbindungseinstellungen für eine beliebige Remote-Speicherkonfiguration bearbeiten, hinzufügen oder löschen.

.Über diese Aufgabe
Änderungen an Verbindungseigenschaften wirken sich auf laufende Importe aus. Um Unterbrechungen zu vermeiden, nehmen Sie nur Änderungen an Verbindungseigenschaften vor, wenn keine Importe ausgeführt werden.

.Schritte
. Wählen Sie Menü:Speicher[Remote-Speicher].
. Wählen Sie in der Liste das Remote-Speicherobjekt aus, das Sie ändern möchten.
. Klicken Sie Auf *Einstellungen Anzeigen/Bearbeiten*.
+
Das Dialogfeld Einstellungen für Remote-Speicher wird angezeigt.

. Klicken Sie auf die Registerkarte *Verbindungseigenschaften*.
+
Die konfigurierten IP-Adressen- und Porteinstellungen für den Remote-Speicherimport werden angezeigt.

. Führen Sie eine der folgenden Aktionen aus:
+
** *Bearbeiten* -- Klicken Sie auf *Bearbeiten* neben dem entsprechenden Zeilenelement für das entfernte Speicherobjekt. Geben Sie die überarbeitete IP-Adresse und/oder Portinformationen in die Felder ein.
** *Hinzufügen* -- Klicken Sie auf *Hinzufügen*, und geben Sie dann die neue IP-Adresse und Port-Informationen in die dafür vorgesehenen Felder ein. Klicken Sie zur Bestätigung auf *Hinzufügen* und dann wird die neue Verbindung in der Liste der Remote-Speicherobjekte angezeigt.
** *Löschen* -- Wählen Sie die gewünschte Verbindung aus der Liste aus und klicken Sie dann auf *Löschen*. Bestätigen Sie den Vorgang, indem Sie eingeben `delete` Klicken Sie im dafür vorgesehenen Feld auf *Löschen*. Die Verbindung wird aus der Liste der Remote-Speicherobjekte entfernt.


. Klicken Sie Auf *Speichern*.
+
Die geänderten Verbindungseinstellungen werden auf das Remote-Speicherobjekt angewendet.


