---
permalink: sm-storage/snapshot-terminology.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, terms 
summary: Erfahren Sie, wie die Snapshot-Bedingungen auf Ihr Storage Array angewendet werden. 
---
= Snapshot Terminologie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie die Snapshot-Bedingungen auf Ihr Storage Array angewendet werden.

[cols="25h,~"]
|===
| Laufzeit | Beschreibung 


 a| 
Snapshots
 a| 
Die Snapshot Funktion dient zum Erstellen und Managen von Images von Volumes.



 a| 
Snapshot Image
 a| 
Ein Snapshot-Image ist eine logische Kopie der Volume-Daten, die zu einem bestimmten Zeitpunkt erfasst werden. Wie bei einem Wiederherstellungspunkt können Sie durch Snapshot Images ein Rollback zu einem bekannten fehlerfreien Datensatz durchführen. Obwohl der Host auf das Snapshot-Image zugreifen kann, kann er nicht direkt lesen oder darauf schreiben.



 a| 
Basis-Volume
 a| 
Ein Basis-Volume ist die Quelle, aus der ein Snapshot Image erstellt wird. Es kann sich um ein Thick- oder Thin-Volume handeln, das in der Regel einem Host zugewiesen ist. Das Basis-Volume kann entweder in einer Volume-Gruppe oder im Laufwerk-Pool gespeichert werden.



 a| 
Snapshot Volume
 a| 
Ein Snapshot-Volume ermöglicht dem Host den Zugriff auf Daten im Snapshot Image. Das Snapshot Volume verfügt über eine eigene reservierte Kapazität, um alle Änderungen am Basis-Volume ohne Beeinträchtigung des ursprünglichen Snapshot Images zu speichern.



 a| 
Snapshot-Gruppe
 a| 
Eine Snapshot-Gruppe ist eine Sammlung von Snapshot Images aus einem einzigen Basis-Volume.



 a| 
Reserviertes Kapazitäts-Volume
 a| 
Ein reserviertes Kapazitäts-Volume erfasst, welche Datenblöcke des Basis-Volumes überschrieben werden und welchen Inhalt diese Blöcke erhalten bleiben.



 a| 
Snapshot Zeitplan
 a| 
Ein Snapshot-Zeitplan ist ein Zeitplan für das Erstellen von automatischen Snapshot-Images. Über den Zeitplan können Sie die Häufigkeit von Bildkreationen steuern.



 a| 
Snapshot Konsistenzgruppe
 a| 
Eine Snapshot Konsistenzgruppe ist eine Sammlung von Volumes, die beim Erstellen eines Snapshot Images als eine Einheit behandelt werden. Jedes dieser Volumes verfügt über ein eigenes Snapshot-Image, jedoch werden alle Bilder zum gleichen Zeitpunkt erstellt.



 a| 
Mitglied-Volume der Snapshot Konsistenzgruppe
 a| 
Jedes Volume, das zu einer Snapshot-Konsistenzgruppe gehört, wird als Mitgliedvolume bezeichnet. Wenn Sie einer Snapshot Konsistenzgruppe ein Volume hinzufügen, erstellt System Manager automatisch eine neue Snapshot-Gruppe, die diesem Mitglied-Volume entspricht.



 a| 
Rollback
 a| 
Ein Rollback ist der Vorgang, bei dem Daten in einem Basis-Volume an einen vorherigen Zeitpunkt zurückgegeben werden.



 a| 
Reservierte Kapazität
 a| 
Reservierte Kapazität ist die zugewiesene physische Kapazität, die für jeden Kopierdienst- und Storage-Objekt verwendet wird. Er ist nicht direkt vom Host lesbar.

|===