---
permalink: sm-storage/ssd-cache-and-volumes.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, ssd, cache, volumes 
summary: 'Sie können ein Volume zu SSD Cache hinzufügen, um die Leseleistung zu verbessern. SSD-Cache besteht aus einer Reihe von Solid-State Disk-Laufwerken (SSD), die Sie in Ihrem Storage-Array logisch gruppieren.' 
---
= SSD Cache und Volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Volume zu SSD Cache hinzufügen, um die Leseleistung zu verbessern. SSD-Cache besteht aus einer Reihe von Solid-State Disk-Laufwerken (SSD), die Sie in Ihrem Storage-Array logisch gruppieren.

[NOTE]
====
Diese Funktion steht nicht auf dem EF600 oder EF300-Storage-System zur Verfügung.

====


== Volumes

Über einfache Volume-I/O-Mechanismen werden Daten in den und aus dem SSD-Cache verschoben. Nachdem Daten im Cache gespeichert und auf den SSDs gespeichert wurden, werden nachfolgende Lesezugriffe auf diese Daten im SSD Cache ausgeführt. Auf das HDD-Volume ist somit kein Zugriff mehr erforderlich.

SSD Cache ist ein sekundärer Cache zur Verwendung mit dem primären Cache im dynamischen Random-Access Memory (DRAM) des Controllers.

* Im primären Cache werden die Daten nach dem Lesen des Hosts im DRAM gespeichert.
* Im SSD Cache werden die Daten aus Volumes kopiert und auf zwei internen RAID-Volumes (eine pro Controller) gespeichert, die bei der Erstellung eines SSD-Caches automatisch erstellt werden.


Die internen RAID-Volumes werden für die interne Cache-Verarbeitung verwendet. Auf diese Volumes kann nicht zugegriffen oder in der Benutzeroberfläche angezeigt werden. Diese beiden Volumes zählen jedoch die Gesamtanzahl der im Storage Array zulässigen Volumes.

[NOTE]
====
Jedes Volume, das der Nutzung des SSD-Caches eines Controllers zugewiesen ist, kann keine automatische Lastverteilung durchführen.

====


== Laufwerkssicherheit

Wenn Sie SSD Cache auf einem Volume verwenden möchten, das auch die Laufwerkssicherheit verwendet (ist sicher aktiviert), müssen die Laufwerksicherheitsfunktionen des Volumes und des SSD-Caches übereinstimmen. Stimmen sie nicht überein, wird das Volume nicht sicher aktiviert.
