---
permalink: sm-storage/view-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, ssd cache, statistics 
summary: Sie können Statistiken für den SSD-Cache anzeigen, z. B. Lese-, Schreib-, Cache-Treffer, Cache-Zuweisung in Prozent, Und Cache-Auslastung in Prozent. 
---
= Anzeigen von SSD-Cache-Statistiken
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Statistiken für den SSD-Cache anzeigen, z. B. Lese-, Schreib-, Cache-Treffer, Cache-Zuweisung in Prozent, Und Cache-Auslastung in Prozent.

Die nominalen Statistiken, bei denen es sich um eine Untergruppe der detaillierten Statistiken handelt, werden im Dialogfeld „View SSD Cache Statistics“ angezeigt. Sie können detaillierte Statistiken für den SSD-Cache nur anzeigen, wenn Sie alle SSD-Statistiken zu A exportieren `.csv` Datei:

Während Sie die Statistiken überprüfen und interpretieren, beachten Sie, dass einige Interpretationen durch die Prüfung einer Kombination von Statistiken abgeleitet werden.

.Schritte
. Wählen Sie Menü:Speicher[Pools & Volume Groups].
. Wählen Sie den SSD-Cache aus, für den Sie Statistiken anzeigen möchten, und klicken Sie dann auf Menü:Mehr[View SSD Cache Statistics].
+
Das Dialogfeld SSD-Cache-Statistiken anzeigen wird angezeigt und zeigt die nominalen Statistiken für den ausgewählten SSD-Cache an.

+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellungen | Beschreibung 


 a| 
Lesezugriffe
 a| 
Zeigt die Gesamtzahl der Host-Lesevorgänge aus den SSD Volumes mit Cache-Aktivierung an. Je mehr das Verhältnis von Lese- zu Schreibzugriffen ist, desto besser ist der Betrieb des Cache.



 a| 
Schreibvorgänge
 a| 
Die Gesamtzahl der Host-Schreibvorgänge auf den SSD-Cache-fähigen Volumes, Je mehr das Verhältnis von Lese- zu Schreibzugriffen ist, desto besser ist der Betrieb des Cache.



 a| 
Cache-Treffer
 a| 
Zeigt die Anzahl der Cache-Treffer an.



 a| 
Cache-Treffer %
 a| 
Zeigt den Prozentsatz von Cache-Treffern an. Diese Zahl leitet sich aus Cache-Hits / (Lese- + Schreibvorgänge) ab. Der Cache-Trefferprozentsatz sollte im Hinblick auf einen effektiven SSD-Cache-Vorgang größer als 50 Prozent sein.



 a| 
Cache-Zuweisung %
 a| 
Zeigt den Prozentsatz des zugewiesenen SSD-Cache-Speichers an, ausgedrückt als Prozentsatz des SSD-Cache-Speichers, der für diesen Controller verfügbar ist und aus zugewiesenen Bytes/verfügbaren Bytes abgeleitet wird.



 a| 
Cache-Auslastung in %
 a| 
Zeigt den Prozentsatz von SSD-Cache-Storage, der Daten von aktivierten Volumes enthält, die in Prozent des zugewiesenen SSD-Cache-Storage angegeben sind. Diese Menge stellt die Auslastung oder Dichte des SSD-Cache dar. Abgeleitet von zugewiesenen Bytes/verfügbaren Bytes.



 a| 
Alle Exportieren
 a| 
Exportiert alle SSD-Cache-Statistiken in ein CSV-Format. Die exportierte Datei enthält alle verfügbaren Statistiken für den SSD-Cache (nominal und detailliert).

|===
====
. Klicken Sie auf *Abbrechen*, um das Dialogfeld zu schließen.

