---
permalink: sm-storage/view-snapshot-image-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, view, snapshot, image, settings 
summary: Sie können die Eigenschaften, den Status, die reservierte Kapazität und die zugehörigen Objekte anzeigen, die jedem Snapshot-Image zugewiesen sind. 
---
= Anzeigen der Einstellungen für Snapshot-Images
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Eigenschaften, den Status, die reservierte Kapazität und die zugehörigen Objekte anzeigen, die jedem Snapshot-Image zugewiesen sind.

Zu den zugehörigen Objekten für ein Snapshot Image zählen das Basis-Volume oder die Snapshot Konsistenzgruppe, für die dieses Snapshot Image ein Wiederherstellungspunkt ist, die zugehörige Snapshot Gruppe und alle aus dem Snapshot Image erstellten Snapshot Volumes. Bestimmen Sie mithilfe der Snapshot-Einstellungen, ob Sie das Snapshot-Image kopieren oder konvertieren möchten.

.Schritte
. Wählen Sie Menü:Storage[Snapshots].
. Klicken Sie auf die Registerkarte *Snapshot Images*.
. Wählen Sie das Snapshot-Bild aus, das Sie anzeigen möchten, und klicken Sie dann auf *Einstellungen anzeigen*.
+
Das Dialogfeld Snapshot-Bildeinstellungen wird angezeigt.

. Zeigen Sie die Einstellungen für das Snapshot-Image an.

