---
permalink: sm-storage/what-is-a-snapshot-image.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, image, 
summary: Ein Snapshot-Image ist eine logische Kopie des Volume-Inhalts, der zu einem bestimmten Zeitpunkt erfasst wurde. Snapshot Images belegen minimalen Speicherplatz. 
---
= Was ist ein Snapshot Image?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Snapshot-Image ist eine logische Kopie des Volume-Inhalts, der zu einem bestimmten Zeitpunkt erfasst wurde. Snapshot Images belegen minimalen Speicherplatz.

Die Snapshot Image-Daten werden wie folgt gespeichert:

* Ein erstelltes Snapshot Image entspricht genau dem Basis-Volume. Sobald der Snapshot erstellt wurde, werden die ursprünglichen Daten für Datenblöcke oder Blöcke auf dem Basis-Volume in die reservierte Snapshot Kapazität kopiert, bevor die neuen Daten auf das Basis-Volume geschrieben werden.
* Nachfolgende Snapshots enthalten nur Datenblöcke, die sich seit dem ersten Snapshot Image geändert haben. Bei jedem folgenden Kopiervorgang werden Originaldaten gespeichert, die im Basis-Volume überschrieben werden, bevor die neuen Daten auf das Basis-Volume geschrieben werden.

