---
permalink: sm-storage/what-is-a-snapshot-group.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, group, 
summary: Eine Snapshot-Gruppe ist eine Sammlung von zeitpunktgenauen Snapshot-Images eines einzelnen verbundenen Basis-Volumes. 
---
= Was ist eine Snapshot Gruppe?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine Snapshot-Gruppe ist eine Sammlung von zeitpunktgenauen Snapshot-Images eines einzelnen verbundenen Basis-Volumes.

System Manager organisiert Snapshot Images in _Snapshot Gruppen_. Snapshot-Gruppen erfordern keine Benutzeraktion, Sie können jedoch jederzeit die reservierte Kapazität einer Snapshot-Gruppe anpassen. Darüber hinaus werden Sie möglicherweise aufgefordert, eine reservierte Kapazität zu erstellen, wenn die folgenden Bedingungen erfüllt sind:

* Jedes Mal, wenn Sie einen Snapshot eines Basis-Volumes erstellen, das noch keine Snapshot-Gruppe besitzt, erstellt System Manager automatisch eine Snapshot-Gruppe. Dadurch wird für das Basis-Volume reservierte Kapazität erstellt, mit dem nachfolgende Snapshot Images gespeichert werden können.
* Jedes Mal, wenn Sie einen Snapshot-Zeitplan für ein Basis-Volume erstellen, erstellt System Manager automatisch eine Snapshot-Gruppe.

