---
permalink: sm-storage/what-does-the-mib-s-graph-show.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mibs, graph, 
summary: Das MiB/s-Diagramm zeigt Statistiken zur Übertragungsgeschwindigkeit in Mebibyte pro Sekunde an. Auf der Startseite werden in diesem Diagramm Statistiken für das Speicher-Array angezeigt. In der logischen Ansicht, der physischen Ansicht und den Registerkarten Applikationen und Workloads der Performance-Ansicht werden in diesem Diagramm Statistiken für das Storage Array, die Volumes, Volume-Gruppen, Pools, Applikationen Und Workloads. 
---
= Was wird im MiB/s-Diagramm angezeigt?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das MiB/s-Diagramm zeigt Statistiken zur Übertragungsgeschwindigkeit in Mebibyte pro Sekunde an. Auf der Startseite werden in diesem Diagramm Statistiken für das Speicher-Array angezeigt. In der logischen Ansicht, der physischen Ansicht und den Registerkarten Applikationen und Workloads der Performance-Ansicht werden in diesem Diagramm Statistiken für das Storage Array, die Volumes, Volume-Gruppen, Pools, Applikationen Und Workloads.

MIB/s ist eine Abkürzung für _Mebibyte pro Sekunde_, bzw. 1,048,576 Byte pro Sekunde. Bewegen Sie den Mauszeiger über einen Punkt im Diagramm, um die folgenden Werte für diesen Zeitpunkt anzuzeigen:

* Die Menge der Daten, die gelesen werden.
* Die Menge der geschriebenen Daten.
* Die kombinierte Gesamtdatenmenge, die gelesen und geschrieben wurde.

