---
permalink: sm-storage/what-is-a-hot-spare-drive.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hot, spare, drive 
summary: Hot Spares fungieren als Standby-Laufwerke in RAID 1-, RAID 5- oder RAID 6-Volume-Gruppen. Es handelt sich dabei um voll funktionsfähige Laufwerke, die keine Daten enthalten. Wenn ein Laufwerk in der Volume-Gruppe ausfällt, rekonstruiert der Controller die Daten vom ausgefallenen Laufwerk automatisch auf eine Hot Spare-Festplatte. 
---
= Was ist eine Hot-Spare-Festplatte?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hot Spares fungieren als Standby-Laufwerke in RAID 1-, RAID 5- oder RAID 6-Volume-Gruppen. Es handelt sich dabei um voll funktionsfähige Laufwerke, die keine Daten enthalten. Wenn ein Laufwerk in der Volume-Gruppe ausfällt, rekonstruiert der Controller die Daten vom ausgefallenen Laufwerk automatisch auf eine Hot Spare-Festplatte.

Wenn ein Laufwerk im Speicher-Array ausfällt, wird das Hot-Spare-Laufwerk automatisch durch das ausgefallene Laufwerk ersetzt, ohne dass ein physischer Austausch erforderlich ist. Wenn das Hot-Spare-Laufwerk verfügbar ist, wenn ein Laufwerk ausfällt, verwendet der Controller Redundanzdaten, um die Daten von dem ausgefallenen Laufwerk auf dem Hot-Spare-Laufwerk zu rekonstruieren.

Ein Hot-Spare-Laufwerk ist nicht einer bestimmten Volume-Gruppe zugewiesen. Stattdessen können Sie ein Hot-Spare-Laufwerk für alle ausgefallenen Laufwerke im Storage-Array mit derselben Kapazität oder kleinerer Kapazität verwenden. Ein Hot-Spare-Laufwerk muss vom gleichen Medientyp (HDD oder SSD) sein wie die Laufwerke, die es schützt.

[NOTE]
====
Hot-Spare-Festplatten werden mit Pools nicht unterstützt. Anstatt Hot-Spare-Festplatten nutzen Pools die freie Kapazität in jedem Laufwerk, das den Pool umfasst.

====