---
permalink: sm-storage/what-are-hosts-and-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, hosts, clusters, server, 
summary: Ein Host ist ein Server, der I/O an ein Volume auf einem Storage-Array sendet. Ein Host-Cluster ist eine Gruppe von Hosts. Sie erstellen ein Host-Cluster, damit Sie mehrere Hosts dieselben Volumes ganz einfach zuweisen können. 
---
= Was sind Hosts und Host Cluster?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Host ist ein Server, der I/O an ein Volume auf einem Storage-Array sendet. Ein Host-Cluster ist eine Gruppe von Hosts. Sie erstellen ein Host-Cluster, damit Sie mehrere Hosts dieselben Volumes ganz einfach zuweisen können.

Sie definieren einen Host separat. Es kann entweder eine unabhängige Einheit sein oder zu einem Host-Cluster hinzugefügt werden. Sie können Volumes einem individuellen Host zuweisen oder ein Host kann Teil eines Host-Clusters sein, der Zugriff auf ein oder mehrere Volumes für andere Hosts im Host-Cluster freigibt.

Das Host-Cluster ist eine logische Einheit, die Sie in SANtricity System Manager erstellen. Sie müssen Hosts zum Host-Cluster hinzufügen, bevor Sie Volumes zuweisen können.
