---
permalink: sm-storage/when-would-i-want-to-use-the-assign-host-later-selection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, offline, volumes, use, assign, host, 
summary: Wenn Sie den Prozess zum Erstellen von Volumes beschleunigen möchten, können Sie den Hostzuordnungsschritt überspringen, damit neu erstellte Volumes offline initialisiert werden. 
---
= Wann soll ich die spätere Auswahl Host zuweisen verwenden?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie den Prozess zum Erstellen von Volumes beschleunigen möchten, können Sie den Hostzuordnungsschritt überspringen, damit neu erstellte Volumes offline initialisiert werden.

Die neu erstellten Volumes müssen initialisiert werden. Das System kann sie mit einem von zwei Modi initialisieren - entweder einem sofortigen verfügbaren Format (IAF)-Hintergrundinitialisierungsprozess oder einem Offline-Prozess.

Wenn Sie ein Volume einem Host zuordnen, ist es erforderlich, dass alle Initialisierungsvolumes in dieser Gruppe in eine Hintergrundinitialisierung übergehen. Durch diesen Hintergrundinitialisierungsprozess können gleichzeitige Host-I/O-Vorgänge erfolgen, was manchmal sehr zeitaufwendig sein kann.

Wenn keines der Volumes einer Volume-Gruppe zugeordnet ist, wird die Offline-Initialisierung durchgeführt. Der Offline-Prozess ist viel schneller als der Hintergrundprozess.
