---
permalink: sm-storage/why-dont-i-see-all-my-volumes-hosts-or-host-clusters.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, volumes, hosts, host clusters, data assurance 
summary: 'Snapshot-Volumes mit einem da-fähigen Basis-Volume können nicht einem Host zugewiesen werden, der nicht Data Assurance (da)-fähig ist. Sie müssen das da auf dem Basis-Volume deaktivieren, bevor ein Snapshot-Volume einem Host zugewiesen werden kann, der nicht über da-fähig ist.“' 
---
= Warum sehe ich nicht alle meine Bände, Hosts oder Host Cluster?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot-Volumes mit einem da-fähigen Basis-Volume können nicht einem Host zugewiesen werden, der nicht Data Assurance (da)-fähig ist. Sie müssen das da auf dem Basisvolume deaktivieren, bevor ein Snapshot-Volume einem Host zugewiesen werden kann, der nicht über da-fähig ist.

Beachten Sie die folgenden Richtlinien für den Host, dem Sie das Snapshot-Volume zuweisen:

* Ein Host ist nicht da-fähig, wenn er über eine I/O-Schnittstelle, die nicht über da-fähig ist, mit dem Speicher-Array verbunden ist.
* Ein Host-Cluster ist nicht da-fähig, wenn es mindestens ein Hostmitglied hat, das nicht da-fähig ist.


[NOTE]
====
Sie können da nicht auf einem Volume deaktivieren, das mit Snapshots (Konsistenzgruppen, Snapshot-Gruppen, Snapshot-Images und Snapshot-Volumes), Volume-Kopien, Und Spiegelungen. Alle zugeordneten Kapazitäts- und Snapshot-Objekte müssen gelöscht werden, bevor das da auf dem Basis-Volume deaktiviert werden kann.

====