---
permalink: sm-storage/why-does-the-data-display-as-zero-in-the-graphs-and-table.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, zero, graphs, table 
summary: Wenn für einen Datenpunkt in den Diagrammen und in der Tabelle eine Null angezeigt wird, bedeutet dies, dass für diesen Zeitpunkt keine I/O-Aktivität für das Objekt vorhanden ist. Dies kann passieren, weil der Host keine I/O-Vorgänge an dieses Objekt einleitet oder es ein Problem mit dem Objekt selbst sein kann. 
---
= Warum werden Daten in den Diagrammen und in der Tabelle als Null angezeigt?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn für einen Datenpunkt in den Diagrammen und in der Tabelle eine Null angezeigt wird, bedeutet dies, dass für diesen Zeitpunkt keine I/O-Aktivität für das Objekt vorhanden ist. Dies kann passieren, weil der Host keine I/O-Vorgänge an dieses Objekt einleitet oder es ein Problem mit dem Objekt selbst sein kann.

Die historischen Daten für das Objekt können weiterhin angezeigt werden. Die Diagramme und die Tabelle zeigen nicht Null-Daten, sobald die I/O-Aktivität für das Objekt beginnt.

In der folgenden Tabelle sind die häufigsten Gründe aufgeführt, warum ein Datenpunktwert für ein bestimmtes Objekt Null sein könnte.

[cols="25h,~"]
|===
| Objekttyp auf Array-Ebene | Ursachendaten werden als Null angezeigt 


 a| 
Datenmenge
 a| 
* Das Volume hatte keine Host-Zuweisung.




 a| 
Volume-Gruppe
 a| 
* Volume-Gruppe wird importiert.
* Volume-Gruppe enthält kein Volume, das einem Host zugewiesen ist. *_und_* Volume-Gruppe enthält keine reservierte Kapazität.




 a| 
Laufwerk
 a| 
* Laufwerk ist ausgefallen.
* Laufwerk wurde entfernt.
* Das Laufwerk befindet sich in einem unbekannten Zustand.




 a| 
Controller
 a| 
* Der Controller ist offline.
* Controller ist ausgefallen.
* Controller wurde entfernt.
* Der Controller befindet sich in einem unbekannten Status.




 a| 
Storage Array erledigen
 a| 
* Das Storage-Array enthält keine Volumes.


|===