---
permalink: sm-storage/why-use-snapshot-images.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, snapshot, images 
summary: Snapshots schützen vor versehentlichem oder böswillig herbeigeführten Verlust oder Beschädigung von Daten und ermöglichen so die Recovery. 
---
= Warum Snapshot-Bilder verwenden?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshots schützen vor versehentlichem oder böswillig herbeigeführten Verlust oder Beschädigung von Daten und ermöglichen so die Recovery.

Wählen Sie ein Basis-Volume oder eine Gruppe von Basis-Volumes aus, eine Snapshot-Konsistenzgruppe genannt, und erfassen Sie dann Snapshot Images auf eine oder mehrere der folgenden Arten:

* Sie können ein Snapshot Image eines einzelnen Basis-Volumes oder eine Snapshot Konsistenzgruppe aus mehreren Basis-Volumes erstellen.
* Sie können Snapshots manuell erstellen oder einen Zeitplan für ein Basis-Volume oder eine Snapshot-Consistency Group erstellen, um periodische Snapshot-Images automatisch zu erfassen.
* Sie können ein Host-zugängliches Snapshot-Volume eines Snapshot-Images erstellen.
* Sie können einen Rollback-Vorgang durchführen, um ein Snapshot-Image wiederherzustellen.


Das System speichert mehrere Snapshot-Images als Wiederherstellungspunkte, mit denen Sie ein Rollback zu bekannten guten Datensätzen zu bestimmten Zeitpunkten durchführen können. Durch die Möglichkeit eines Rollback ist Schutz vor versehentlichem Löschen von Daten und Datenbeschädigung möglich.
