---
permalink: sm-storage/why-do-i-need-reserved-capacity-for-every-member-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, member, volume 
summary: Jedes Mitglied-Volume in einer Snapshot-Konsistenzgruppe muss über seine eigene reservierte Kapazität verfügen, um alle Änderungen, die von der Host-Applikation auf dem Basis-Volume vorgenommen wurden, ohne das referenzierte Snapshot-Image der Konsistenzgruppe zu beeinträchtigen. Die reservierte Kapazität ermöglicht der Host-Applikation den Schreibzugriff auf eine Kopie der Daten im Mitglied-Volume, die als Lese- und Schreibzugriff festgelegt ist. 
---
= Warum brauche ich reservierte Kapazität für jedes Member Volume?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Jedes Mitglied-Volume in einer Snapshot-Konsistenzgruppe muss über seine eigene reservierte Kapazität verfügen, um alle Änderungen, die von der Host-Applikation auf dem Basis-Volume vorgenommen wurden, ohne das referenzierte Snapshot-Image der Konsistenzgruppe zu beeinträchtigen. Die reservierte Kapazität ermöglicht der Host-Applikation den Schreibzugriff auf eine Kopie der Daten im Mitglied-Volume, die als Lese- und Schreibzugriff festgelegt ist.

Ein Snapshot-Image für Konsistenzgruppen ist nicht direkt für Hosts zugänglich. Vielmehr wird das Snapshot-Image verwendet, um nur die Daten zu speichern, die vom Basis-Volume erfasst wurden.

Während der Erstellung eines Snapshot Volume für die Konsistenzgruppe, das als Lesen/Schreiben bezeichnet wird, erstellt System Manager für jedes Mitglied-Volume in der Konsistenzgruppe eine reservierte Kapazität. Diese reservierte Kapazität ermöglicht der Host-Applikation den Schreibzugriff auf eine Kopie der Daten im Snapshot Image der Konsistenzgruppe.
