---
permalink: sm-storage/why-cant-i-choose-another-amount-to-decrease-by.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, decrease, reserved capacity 
summary: Sie können die reservierte Kapazität nur um den Betrag reduzieren, den Sie zur Steigerung verwendet haben. Reservierte Kapazität für Mitglieder-Volumes kann nur in umgekehrter Reihenfolge entfernt werden, in der sie hinzugefügt wurden. 
---
= Warum kann ich nicht eine andere Menge wählen, um zu verringern?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die reservierte Kapazität nur um den Betrag reduzieren, den Sie zur Steigerung verwendet haben. Reservierte Kapazität für Mitglieder-Volumes kann nur in umgekehrter Reihenfolge entfernt werden, in der sie hinzugefügt wurden.

Sie können die reservierte Kapazität für ein Speicherobjekt nicht verringern, wenn eine der folgenden Bedingungen vorliegt:

* Wenn es sich bei dem Storage-Objekt um ein gespiegeltes Paar-Volume handelt.
* Wenn das Storage-Objekt nur ein Volume für die reservierte Kapazität enthält. Das Storage-Objekt muss mindestens zwei Volumes für die reservierte Kapazität enthalten.
* Wenn es sich bei dem Speicherobjekt um ein deaktiviertes Snapshot-Volume handelt.
* Wenn das Speicherobjekt mindestens ein Snapshot-Image enthält.


Sie können Volumes für die reservierte Kapazität nur in der umgekehrten Reihenfolge entfernen, in der sie hinzugefügt wurden.

Sie können die reservierte Kapazität für ein schreibgeschütztes Snapshot-Volume nicht verringern, da ihm keine zugewiesene Kapazität zur Verfügung steht. Nur Snapshot Volumes mit Lese- und Schreibvorgängen erfordern reservierte Kapazität.
