---
permalink: sm-storage/why-are-capacity-alerts-important.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, capacity, alerts, important 
summary: Kapazitätswarnungen geben an, wann Laufwerke zu einem Pool hinzugefügt werden sollen. Ein Pool benötigt ausreichend freie Kapazität, um Storage-Array-Vorgänge erfolgreich durchzuführen. Um diese Vorgänge zu unterbrechen, können Sie System Manager so konfigurieren, dass Warnungen gesendet werden, wenn die freie Kapazität eines Pools einen bestimmten Prozentsatz erreicht oder überschreitet. 
---
= Warum sind Kapazitätswarnungen wichtig?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Kapazitätswarnungen geben an, wann Laufwerke zu einem Pool hinzugefügt werden sollen. Ein Pool benötigt ausreichend freie Kapazität, um Storage-Array-Vorgänge erfolgreich durchzuführen. Um diese Vorgänge zu unterbrechen, können Sie System Manager so konfigurieren, dass Warnungen gesendet werden, wenn die freie Kapazität eines Pools einen bestimmten Prozentsatz erreicht oder überschreitet.

Sie legen diesen Prozentsatz fest, wenn Sie einen Pool mit der Option *Pool Auto-Configuration* oder mit der Option *Pool erstellen* erstellen. Wenn Sie die Option automatisch wählen, bestimmen die Standardeinstellungen automatisch, wann Sie Benachrichtigungen erhalten. Wenn Sie den Pool manuell erstellen möchten, können Sie die Benachrichtigungseinstellungen festlegen oder die Standardeinstellungen übernehmen. Sie können diese Einstellungen später im Menü:Einstellungen[Warnungen] anpassen.

[NOTE]
====
Wenn die freie Kapazität im Pool den angegebenen Prozentsatz erreicht, wird eine Warnmeldung mit der Methode gesendet, die Sie in der Warnungskonfiguration angegeben haben.

====