---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 12.00 
summary: Neue Funktionen im SANtricity OS. 
---
= Was ist neu in SANtricity OS 12.00
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Die folgende Tabelle beschreibt neue Funktionen in SANtricity System Manager 12.00.



== Neue Funktionen in Version 12.00


NOTE: Die SANtricity OS 12.00-Version ist nur mit den neuen EF80 und EF50 All-Flash-Storage-Systemen kompatibel. Wenn Sie SANtricity OS 11.9 oder älter verwenden, beachten Sie bitte link:known-issues.html["Bekannte Probleme"] für eine Liste der neuen Funktionen in früheren Versionen.

[cols="35h,~"]
|===
| Neues Feature | Beschreibung 


 a| 
Neue Speichersystemmodelle – EF80 und EF50 All-Flash-Storage-Systeme
 a| 
Diese Version führt die EF80 und EF50 All-NVMe-Flash-Speichersysteme ein. Die EF80 und EF50 unterstützen 24 NVMe-SSD-Laufwerke und eine Inter-Controller-Mirroring-Karte pro Controller. Die unterstützten NVMe-over-Fabrics-Host-Schnittstellen umfassen NVMe over RoCE, NVMe over IB, NVMe over FC für EF80 und NVMe over FC für EF50. Die unterstützte SCSI-Schnittstelle ist Fibre Channel für beide Systeme. Der EF50 unterstützt bis zu zwei Host-Schnittstellenkarten pro Controller, während der EF80 bis zu drei Host-Schnittstellenkarten pro Controller unterstützt.

NVMe-SSDs mit hoher Kapazität von 30 TB oder 60 TB werden ebenfalls mit der EF80 und EF50 unterstützt. Die EF80 und EF50 können den Dynamic Disk Pool nur nutzen, wenn das Array mit 30-TB- oder 60-TB-Laufwerken bestückt ist.



 a| 
Neue Benutzeroberfläche für SANtricity System Manager
 a| 
Für die neuen EF80 und EF50 Controller wurde die Benutzeroberfläche des SANtricity System Manager überarbeitet, um ein moderneres Erscheinungsbild und Benutzererlebnis zu bieten. Die neue Oberfläche umfasst eine Navigation im linken Bereich und eine verbesserte Bedienbarkeit zur Optimierung von Verwaltungsaufgaben.


NOTE: Die neue Benutzeroberfläche ist derzeit nur für die Speichersysteme EF80 und EF50 mit der SANtricity 12.00-Version verfügbar. Wenn Sie SANtricity 11.9 oder älter verwenden, beachten Sie bitte link:https://docs.netapp.com/us-en/e-series-santricity-119/system-manager/index.html["SANtricity System Manager 11.9"] für Anweisungen zur Nutzung der alten Benutzeroberfläche.



 a| 
Subject Alternative Names (SANs) für Serverzertifikate erlauben jetzt nur noch Buchstaben, Ziffern und Bindestriche
 a| 
Beim Erstellen oder Bearbeiten eines Serverzertifikats im SANtricity System Manager oder Unified Manager sind im Feld „Subject Alternative Names“ (SANs) nun nur noch Buchstaben, Ziffern und Bindestriche zulässig. Diese Änderung erhöht die Sicherheit und gewährleistet die Kompatibilität mit den Industriestandards für SSL/TLS-Zertifikate.



 a| 
Die Segmentgröße von Dynamic Disk Pools beträgt jetzt standardmäßig 32K für SSD- und NVMe-basierte Systeme
 a| 
Für dynamische Festplattenpools auf SSD- und NVMe-basierten Systemen wurde die Standardsegmentgröße auf 32K geändert. Zuvor war die Standardsegmentgröße für dynamische Festplattenpools auf diesen Systemen auf 128K festgelegt. Diese Änderung optimiert die Leistung für Workloads, die eine Mischung aus kleinen und großen E/A-Operationen beinhalten.



 a| 
Skripteditor jetzt im SANtricity System Manager verfügbar
 a| 
Im SANtricity System Manager ist jetzt ein neuer Skripteditor verfügbar. Der Skripteditor ermöglicht es Ihnen, eine Skriptdatei zu erstellen oder zu bearbeiten, eine Skriptdatei auf der lokalen Festplatte der Speichermanagementstation zu speichern oder eine Skriptdatei von der Festplatte zu laden. Der Skripteditor bietet Syntaxprüfung und Befehlsausführungsfunktionen zur Verwaltung Ihres Speichersystems. Weitere Informationen finden Sie unter link:sm-support/use-script-editor.html["Verwendung des Script-Editors"^].

|===