---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.90 
summary: Neue Funktionen im SANtricity OS. 
---
= Neuerungen bei SANtricity OS 11.90
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
In der folgenden Tabelle werden die neuen Funktionen von SANtricity System Manager 11.9 beschrieben.



== Neue Funktionen in Version 11.90R1

[cols="35h,~"]
|===
| Neues Feature | Beschreibung 


 a| 
Neue Speichersystemmodelle – EF300C und EF600C
 a| 
In dieser Version werden die All-Flash-NVMe-Storage-Systeme EF300C und EF600C vorgestellt. Bei den EF300C und EF600C handelt es sich um Flash-Versionen mit hoher Kapazität der vorhandenen EF300 und EF600 Storage-Systeme. NVMe-SSD-Laufwerke mit einer hohen Kapazität von 30 TB oder 60 TB werden von EF300C und EF600C unterstützt. Der EF300C/EF600C ist nur für die Verwendung von Dynamic Disk Pools ohne Legacy-RAID-Unterstützung kompatibel.



 a| 
Unterstützung von 12-GB-SAS-Schnittstellen auf EF4000
 a| 
Der E4000 Controller unterstützt jetzt 12 GB SAS-Host-Schnittstellenkarten.

|===


== Neue Funktionen in Version 11.90

[cols="35h,~"]
|===
| Neues Feature | Beschreibung 


 a| 
Neues Storage-Systemmodell: E4000
 a| 
Mit dieser Version wird das kostengünstige Speichersystem E4000 eingeführt. Die E4000 unterstützt 12 und 60 Laufwerke und eine einzelne Host Interface Card (HIC) pro Controller. In der ersten Version werden Host-Schnittstellenkarten wie iSCSI und Fibre Channel unterstützt. E4000 Storage-Systeme und andere E-Series Storage-Systeme können in Unified Manager angezeigt und gemanagt werden.



 a| 
Höhere Kapazität für Dynamic Disk Pools
 a| 
Die Kapazität von Dynamic Disk Pools (DDP) wurde auf 12 PB erhöht, wenn die Kapazität jedes einzelnen Laufwerks innerhalb des Pools größer als 23 TB ist. Wenn die einzelne Laufwerkskapazität weniger als 23 TB beträgt, beträgt die DDP-Kapazität 6 PB.



 a| 
Die Standardeinstellungen für den Medienscan wurden erhöht
 a| 
Die Standard-Scanrate für Medien wurde auf 120 Tage erhöht.



 a| 
Der private Schlüssel wird jetzt für die externe Schlüsselverwaltung akzeptiert
 a| 
CSR-Datei (Certificate Signing Request), die extern über private und öffentliche Schlüsselpaare generiert wird, kann jetzt über System Manager importiert werden.



 a| 
Die Anmeldesperre ist jetzt für Web Services verfügbar
 a| 
Konfigurierbar nur über die REST-API, eine neue Einstellung für die Anmeldesperre ist jetzt für eingebettete und Proxy-Web-Services verfügbar.

|===