---
permalink: sm-mirroring/change-role-between-volumes-in-a-mirrored-pair.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, role, volumes, mirrored, pair, 
summary: Sie können eine Rollenumkehr zwischen den beiden Volumes in einem gespiegelten Paar durchführen, die an synchroner Spiegelung für administrative Zwecke beteiligt sind oder bei einer Katastrophe im lokalen Storage Array auftritt. 
---
= Ändern Sie die Rolle zwischen Volumes in einem gespiegelten Paar
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine Rollenumkehr zwischen den beiden Volumes in einem gespiegelten Paar, das an der synchronen Spiegelung beteiligt ist, durchführen. Diese Aufgabe kann für administrative Zwecke oder im Falle eines Disasters auf dem lokalen Speicher-Array notwendig sein.

Sie können das primäre Volume entweder auf die sekundäre Rolle zurückstufen oder das sekundäre Volume zur primären Rolle heraufstufen. Alle Hosts, die auf das primäre Volume zugreifen, haben Lese-/Schreibzugriff auf das Volume. Wenn das primäre Volume zum sekundären Volume wird, werden nur durch den primären Controller initiierte Remote-Schreibvorgänge auf das Volume geschrieben.

.Schritte
. Wählen Sie Menü:Speicher[Synchronous Mirroring].
. Wählen Sie das gespiegelte Paar aus, das die Volumes enthält, für die Sie die Rolle ändern möchten, und wählen Sie dann Menü:Mehr[Rolle ändern].
+
Das System zeigt eine Bestätigung an.

. Bestätigen Sie, dass Sie die Rolle der Volumes ändern möchten, und wählen Sie dann *Rolle ändern*.
+
[NOTE]
====
Wenn das lokale Speicher-Array nicht mit dem Remote-Speicher-Array kommunizieren kann, zeigt das System das Dialogfeld Speicher-Array nicht kontaktieren an, wenn eine Rollenänderung angefordert wird, aber das Remote-Speicher-Array kann nicht kontaktiert werden. Klicken Sie auf *Ja*, um die Rollenänderung zu erzwingen.

====


System Manager führt die folgende Aktion durch:

* Wenn das zugehörige Volume im gespiegelten Paar kontaktiert werden kann, ändern sich die Rollen zwischen den Volumes. System Manager befördert das sekundäre Volume im gespiegelten Paar in die primäre Rolle oder deprisiert das primäre Volume im gespiegelten Paar auf die sekundäre Rolle (je nach Auswahl).

