---
permalink: sm-mirroring/what-do-i-need-to-know-before-increasing-my-reserved-capacity-on-a-mirrored-pair-volume.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, reserved, capacity, mirrored, pair, volume, 
summary: Normalerweise sollten Sie die reservierte Kapazität erhöhen, wenn Sie eine Warnung erhalten, dass die reservierte Kapazität eines gespiegelten Paares voll wird. Sie können die reservierte Kapazität nur in Schritten von 8 gib erhöhen. 
---
= Was muss ich wissen, bevor ich meine reservierte Kapazität auf einem gespiegelten Paar-Volume erhöhen kann?
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Normalerweise sollten Sie die reservierte Kapazität erhöhen, wenn Sie eine Warnung erhalten, dass die reservierte Kapazität eines gespiegelten Paares voll wird. Sie können die reservierte Kapazität nur in Schritten von 8 gib erhöhen.

Bei asynchronen Spiegelungsvorgängen beträgt die reservierte Kapazität normalerweise 20 Prozent des Basis-Volumes. Wählen Sie eine größere Kapazität für reservierte Kapazität, wenn eine oder beide Bedingungen vorliegen:

* Sie beabsichtigen, das gespiegelte Paar für einen langen Zeitraum zu halten.
* Ein großer Prozentsatz an Datenblöcken ändert sich auf dem primären Volume aufgrund von hoher I/O-Aktivität. Mithilfe von historischen Performance-Daten oder anderen Betriebssystem-Utilities können Sie typische I/O-Aktivitäten für das primäre Volume ermitteln.


Sie können die reservierte Kapazität für ein gespiegeltes Paar erhöhen, indem Sie eine der folgenden Aktionen durchführen:

* Passen Sie den Kapazitätsprozentsatz für ein gespiegeltes Paar-Volumen an, indem Sie Menü:Speicher[Pools und Volumes Groups] auswählen und dann auf die Registerkarte *Reservierte Kapazität* klicken.
* Erstellen Sie ein neues Volume mithilfe von freier Kapazität, die in einem Pool oder einer Volume-Gruppe verfügbar ist.
+
Wenn in einem Pool oder einer Volume-Gruppe keine freie Kapazität vorhanden ist, können Sie nicht konfigurierte Kapazität in Form von nicht verwendeten Laufwerken zu einem Pool oder einer Volume-Gruppe hinzufügen.


