---
permalink: sm-mirroring/why-would-i-update-my-remote-storage-arrays-ip-address.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, update, remote, ip, address, 
summary: Sie aktualisieren die IP-Adresse Ihres Remote-Speicher-Arrays, wenn sich die IP-Adresse eines iSCSI-Ports ändert und das lokale Speicher-Array nicht mit dem Remote-Speicher-Array kommunizieren kann. 
---
= Warum sollte ich die IP-Adresse meines Remote-Speicherarrays aktualisieren?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie aktualisieren die IP-Adresse des Remote-Speicher-Arrays, wenn sich die IP-Adresse eines iSCSI-Ports ändert und das lokale Speicher-Array nicht mit dem Remote-Speicher-Array kommunizieren kann.

Beim Einrichten einer asynchronen Spiegelbeziehung mit einer iSCSI-Verbindung speichern sowohl die lokalen als auch die Remote-Speicher-Arrays einen Datensatz der IP-Adresse des Remote-Speicher-Arrays in der Konfiguration zur asynchronen Spiegelung. Wenn sich die IP-Adresse eines iSCSI-Ports ändert, tritt auf dem Remote-Speicher-Array, das versucht, diesen Port zu verwenden, ein Kommunikationsfehler auf.

Das Speicher-Array mit der geänderten IP-Adresse sendet eine Nachricht an jedes Remote-Speicher-Array, das mit den Spiegelungskonsistency Groups verknüpft ist, die für die Spiegelung über eine iSCSI-Verbindung konfiguriert sind. Speicher-Arrays, die diese Meldung erhalten, aktualisieren automatisch ihre Remote-Ziel-IP-Adresse.

Wenn das Speicher-Array mit der geänderten IP-Adresse seine Array-übergreifende Meldung nicht an ein Remote-Speicher-Array senden kann, sendet das System eine Warnmeldung über das Verbindungsproblem. Verwenden Sie die Option Remote IP-Adresse aktualisieren, um die Verbindung zum lokalen Speicher-Array wiederherzustellen.
