---
permalink: sm-mirroring/why-cant-i-increase-reserved-capacity-with-my-requested-amount.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, increase, reserved, capacity, 
summary: Sie können die reservierte Kapazität nur in Schritten von 4 gib erhöhen. 
---
= Warum kann ich die reservierte Kapazität nicht mit meinem angeforderten Betrag erhöhen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die reservierte Kapazität nur in Schritten von 4 gib erhöhen.

Lesen Sie sich die folgenden Richtlinien durch:

* Sie müssen über ausreichende freie Kapazitäten im Pool oder Volume-Gruppe verfügen, damit diese bei Bedarf erweitert werden kann.
+
Wenn auf einem Pool oder Volume-Gruppen keine freie Kapazität vorhanden ist, können Sie einem Pool oder einer Volume-Gruppe nicht zugewiesene Kapazität in Form nicht verwendeter Laufwerke hinzufügen.

* Das Volume im Pool oder in der Volume-Gruppe muss den optimalen Status aufweisen und darf sich nicht in einem bestimmten Zustand befinden.
* Freie Kapazität muss im Pool bzw. in der Volume-Gruppe vorhanden sein, mit der die Kapazität erhöht werden soll.


Bei asynchronen Spiegelungsvorgängen beträgt die reservierte Kapazität in der Regel 20 Prozent des Basis-Volumes. Verwenden Sie einen höheren Prozentsatz, wenn Sie glauben, dass das Basis-Volume viele Änderungen durchlaufen wird oder wenn die geschätzte Lebensdauer des Kopierservice eines Storage-Objekts sehr lang sein wird.
