---
permalink: sm-interface/administrator-password-protection.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, admin password 
summary: Sie müssen das Speicher-Array mit einem Administratorkennwort konfigurieren, um es vor unbefugtem Zugriff zu schützen. 
---
= Passwortschutz verwalten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen das Speicher-Array mit Kennwörtern konfigurieren, um es vor unbefugtem Zugriff zu schützen.



== Kennwörter festlegen und ändern

Wenn Sie System Manager zum ersten Mal starten, werden Sie aufgefordert, ein Administratorpasswort festzulegen. Jeder Benutzer mit dem Admin-Passwort kann Konfigurationsänderungen am Speicher-Array vornehmen, z. B. Objekte oder Einstellungen hinzufügen, ändern oder entfernen. Informationen zum Festlegen des Admin-Passworts während des ersten Startvorgangs finden Sie unter link:../san-getstarted/access-sam.html["Greifen Sie Auf System Manager Zu"].

Aus Sicherheitsgründen können Sie nur fünf Mal versuchen, ein Passwort einzugeben, bevor das Speicherarray den Status „Sperre“ eingibt. In diesem Zustand weist das Speicherarray nachfolgende Passwortversuche zurück. Sie müssen 10 Minuten warten, bis das Speicherarray auf einen „normalen“ Zustand zurückgesetzt wird, bevor Sie erneut versuchen, ein Passwort einzugeben.

Zusätzlich zum Admin-Passwort enthält das Speicher-Array vordefinierte Benutzerprofile mit einer oder mehreren Rollen, die ihnen zugeordnet sind. Weitere Informationen finden Sie unter link:../sm-settings/permissions-for-mapped-roles.html["Berechtigungen für zugeordnete Rollen"]. Die Benutzerprofile und Zuordnungen können nicht geändert werden. Es können nur Passwörter geändert werden. Wenn Sie das Admin-Passwort oder andere Benutzerpasswörter ändern möchten, finden Sie weitere Informationen unter link:../sm-settings/change-passwords.html["Passwörter ändern"].



== Geben Sie Passwörter nach Sitzungszeitungen erneut ein

Das System fordert Sie zur Eingabe des Passworts nur einmal während einer einzigen Verwaltungssitzung auf. Eine Sitzung läuft jedoch nach 30 Minuten Inaktivität ab. Zu diesem Zeitpunkt müssen Sie das Passwort erneut eingeben. Wenn ein anderer Benutzer, der dasselbe Speicher-Array von einem anderen Management-Client aus verwaltet, das Passwort während der Sitzung ändert, werden Sie beim nächsten Versuch eines Konfigurationsvorgangs oder einer Ansicht aufgefordert, ein Passwort einzugeben.

Sie können das Sitzungszeitlimit ändern oder Sitzungszeitüberschreitungen komplett deaktivieren. Siehe link:../sm-settings/manage-session-timeouts-sam.html["Verwalten von Sitzungszeitungen"].



== Entfernen Sie Laufwerke oder Kennwortschutz

Wenn Sie passwortgeschützte Laufwerke entfernen oder den Kennwortschutz deaktivieren möchten, beachten Sie Folgendes:

* *Wenn Sie Laufwerke mit Kennwortschutz entfernen* -- wird das Passwort auf einem reservierten Bereich jedes Laufwerks im Speicher-Array gespeichert. Wenn Sie alle Laufwerke aus einem Speicher-Array entfernen, funktioniert das Kennwort nicht mehr. Um diese Bedingung zu beheben, installieren Sie eines der Originallaufwerke erneut in das Speicher-Array.
* *Wenn Sie den Passwortschutz entfernen möchten* -- Wenn Sie keine Befehle mehr passwortgeschützt haben möchten, geben Sie das aktuelle Administratorpasswort ein und lassen Sie die neuen Passwortfelder leer.


[CAUTION]
====
Wenn Konfigurationsbefehle auf einem Storage-Array ausgeführt werden, kann dies zu ernsthaften Schäden und Datenverlusten führen. Aus diesem Grund sollten Sie immer ein Administratorkennwort für Ihr Speicherarray festlegen. Verwenden Sie ein langes Administratorkennwort mit mindestens 15 alphanumerischen Zeichen, um die Sicherheit zu erhöhen.

====