---
permalink: sm-interface/faq-storage-system-setup.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= FAQ zur Speichersystemeinrichtung für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Was ist, wenn ich nicht alle meine Hardwarekomponenten sehe?

Wenn im Dialogfeld Hardware überprüfen nicht alle Hardwarekomponenten angezeigt werden, kann dies bedeuten, dass ein Festplatten-Shelf nicht ordnungsgemäß verbunden ist oder dass ein inkompatibles Shelf im Speicher-Array installiert ist.

Vergewissern Sie sich, dass alle Laufwerk-Shelfs ordnungsgemäß angeschlossen sind. Wenn Sie unsicher sind, welche Laufwerkseinschübe kompatibel sind, wenden Sie sich an den technischen Support.



== Was passiert, wenn ich nicht alle meine Hosts sehe?

Wenn Sie die verbundenen Hosts nicht sehen, ist die automatische Erkennung fehlgeschlagen, die Hosts sind nicht ordnungsgemäß angeschlossen oder es sind derzeit keine Hosts angeschlossen.

Sie können Hosts später konfigurieren, sobald Sie die Einrichtung durchgeführt haben. Sie können Hosts wie folgt manuell erstellen:

* Sie können Hosts manuell erstellen und die entsprechenden Host-Port-IDs zuordnen, indem Sie zu MENU:Storage[Hosts] wechseln. Hosts, die manuell erstellt wurden, werden auch im Assistenten * Initial Setup* angezeigt.
* Ziel und Host müssen für den Host-Port-Typ (z. B. iSCSI oder NVMe over RoCE) konfiguriert werden und eine Session für den Storage, der eingerichtet wurde, bevor die automatische Erkennung funktioniert.




== Wie kann ich anhand der Identifizierung von Applikationen mein Storage-Array managen?

Wenn Sie Applikationen identifizieren, empfiehlt SANtricity System Manager automatisch eine Volume-Konfiguration, die den Storage basierend auf dem Applikationstyp optimiert.

Die Optimierung von Volumes durch Applikation ermöglicht einen effizienteren Storage-Betrieb. Merkmale wie I/O-Typ, Segmentgröße, Controller-Eigentümer und Lese- und Schreib-Cache sind in der Volume-Konfiguration enthalten. Zusätzlich können Sie Performance-Daten nach Applikation und Workload anzeigen, um Latenz, IOPS und MiB/s der Applikationen und der zugehörigen Workloads zu bewerten.



== Was ist ein Workload?

Für einige Applikationen im Netzwerk, z. B. SQL Server oder Exchange, können Sie einen Workload definieren, der den Storage für die jeweilige Applikation optimiert.

Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren. Bei einigen Applikationen konfiguriert das System den Workload so, dass er Volumes mit ähnlichen zugrunde liegenden Volume-Merkmalen enthält. Diese Volume-Merkmale werden basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Wenn Sie beispielsweise einen Workload erstellen, der eine Microsoft SQL Server Applikation unterstützt und anschließend Volumes für diesen Workload erstellt, werden die zugrunde liegenden Volume-Merkmale zur Unterstützung von Microsoft SQL Server optimiert.

Während der Volume-Erstellung werden Sie aufgefordert, Fragen zur Verwendung eines Workloads zu beantworten. Wenn Sie beispielsweise Volumes für Microsoft Exchange erstellen, werden Sie gefragt, wie viele Mailboxen Sie benötigen, wie viele Mailboxen Ihre durchschnittlichen Anforderungen an die Mailbox-Kapazität sind und wie viele Kopien der Datenbank Sie benötigen. Das System erstellt anhand dieser Informationen eine optimale Volume-Konfiguration für Sie, die Sie nach Bedarf bearbeiten können.



== Wie konfiguriere ich die Bereitstellungsmethode für AutoSupport?

Um Konfigurationsaufgaben für AutoSupport-Bereitstellungsmethoden aufzurufen, gehen Sie zu menu:Support[Support Center] und klicken Sie dann auf die Registerkarte *AutoSupport*.

Die folgenden Protokolle werden unterstützt: HTTPS und SMTP.



== Woher weiß ich, ob ich die empfohlene Pool-Konfiguration akzeptieren sollte?

Ob Sie die empfohlene Poolkonfiguration akzeptieren, hängt von einigen Faktoren ab.

Ermitteln Sie den Storage-Typ, der Ihre Anforderungen am besten erfüllt, indem Sie folgende Fragen beantworten:

* Bevorzugen Sie mehrere Pools mit geringerer Kapazität, anstatt die größten Pools möglich?
* Bevorzugen Sie RAID-Volume-Gruppen statt Pools?
* Möchten Sie Ihre Laufwerke lieber manuell bereitstellen, anstatt eine Konfiguration für Sie zu empfehlen?


Wenn Sie eine dieser Fragen mit Ja beantwortet haben, sollten Sie die empfohlene Poolkonfiguration ablehnen.



== Der SANtricity System Manager hat keine Hosts erkannt. Was mache ich?

Wenn Sie die verbundenen Hosts nicht sehen, ist die automatische Erkennung fehlgeschlagen, die Hosts sind nicht ordnungsgemäß angeschlossen oder es sind derzeit keine Hosts angeschlossen.

Sie können Hosts später konfigurieren, sobald Sie die Einrichtung durchgeführt haben. Sie können Hosts wie folgt manuell erstellen:

* Sie können Hosts manuell erstellen und die entsprechenden Host-Port-IDs zuordnen, indem Sie zu MENU:Storage[Hosts] wechseln. Hosts, die manuell erstellt wurden, werden auch im Assistenten * Initial Setup* angezeigt.
* Ziel und Host müssen für den Host-Port-Typ (z. B. iSCSI oder NVMe over RoCE) konfiguriert werden und eine Session für den Storage, der eingerichtet wurde, bevor die automatische Erkennung funktioniert.

