---
permalink: sm-interface/operations-in-progress.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, operations in progress 
summary: Auf der Seite „Vorgänge in Bearbeitung“ können Sie eine Liste von lang laufenden Vorgängen anzeigen, die derzeit ausgeführt werden oder sich in einem Status „ausgesetzt“, „angehalten“ oder „fehlgeschlagen“ befinden. Sie können bei bestimmten Arten von Operationen Maßnahmen ergreifen. 
---
= Erfahren Sie mehr über die Seite „Laufende Vorgänge“ des SANtricity System Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite „Vorgänge in Bearbeitung“ können Sie eine Liste von lang laufenden Vorgängen anzeigen, die derzeit ausgeführt werden oder sich in einem Status „ausgesetzt“, „angehalten“ oder „fehlgeschlagen“ befinden. Sie können bei bestimmten Arten von Operationen Maßnahmen ergreifen.

Lange laufende Vorgänge können die Systemleistung beeinträchtigen. Bei einigen Vorgängen haben Sie die Möglichkeit, den Vorgang zu beenden oder dessen Priorität zu ändern, damit zuerst mehr wichtige Vorgänge abgeschlossen werden.

Die Vorgänge, die auf der Seite „Vorgänge in Bearbeitung“ angezeigt werden, umfassen Folgendes:

[cols="1a,1a,1a"]
|===
| Betrieb | Möglicher Status des Vorgangs | Maßnahmen, die Sie ergreifen können 


 a| 
Volume-Kopien
 a| 
Abgeschlossen
 a| 
Löschen



 a| 
Volume-Kopien
 a| 
In Bearbeitung
 a| 
* Priorität ändern
* Hör Auf




 a| 
Volume-Kopien
 a| 
Ausstehend
 a| 
Löschen



 a| 
Volume-Kopien
 a| 
Fehlgeschlagen
 a| 
* Löschen
* Erneut kopieren




 a| 
Volume-Kopien
 a| 
Angehalten
 a| 
* Löschen
* Erneut kopieren




 a| 
Volume-Erstellung (nur Thick Pool Volumes über 64 tib)
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Volume-Löschen (nur Thick Pool Volumes über 64 tib)
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Erste Synchronisierung der asynchronen Spiegelgruppe
 a| 
In Bearbeitung
 a| 
Aussetzen



 a| 
Erste Synchronisierung der asynchronen Spiegelgruppe
 a| 
Ausgesetzt
 a| 
Fortsetzen



 a| 
Synchrones Spiegeln
 a| 
In Bearbeitung
 a| 
Aussetzen



 a| 
Synchrones Spiegeln
 a| 
Ausgesetzt
 a| 
Fortsetzen



 a| 
Rollback von Snapshot Images
 a| 
In Bearbeitung
 a| 
Abbrechen



 a| 
Rollback von Snapshot Images
 a| 
Ausstehend
 a| 
Abbrechen



 a| 
Rollback von Snapshot Images
 a| 
Angehalten
 a| 
* Abbrechen
* Fortsetzen




 a| 
Evakuierung der Laufwerke
 a| 
In Bearbeitung
 a| 
Abbrechen (abhängig vom Evakuierungstyp der Antriebe)



 a| 
Hinzufügen von Kapazitäten für den Pool oder die Volume-Gruppe
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Ändern Sie einen RAID-Level für ein Volume
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Reduktion der Kapazität für einen Pool
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Thin Volume-Rückgewinnung
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Prüfen Sie die verbleibende Zeit für einen IAF-Betrieb (Instant Availability Format) für Pool Volumes
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Prüfen Sie die Datenredundanz einer Volume-Gruppe
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Defragmentieren einer Volume-Gruppe
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Initialisieren Sie ein Volume
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Höhere Kapazität für ein Volume
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Ändern Sie die Segmentgröße für ein Volume
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Laufwerkskopie
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Datenrekonstruktion
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Copyback
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Laufwerk Löschen
 a| 
In Bearbeitung
 a| 
_None_



 a| 
Remote Storage-Import
 a| 
In Bearbeitung
 a| 
* Priorität ändern
* Hör Auf




 a| 
Remote Storage-Import
 a| 
Angehalten
 a| 
* Fortsetzen
* Trennen Sie Die Verbindung




 a| 
Remote Storage-Import
 a| 
Fehlgeschlagen
 a| 
* Fortsetzen
* Trennen Sie Die Verbindung




 a| 
Remote Storage-Import
 a| 
Abgeschlossen
 a| 
Trennen Sie Die Verbindung

|===