---
permalink: sm-interface/overview-interface-sam.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Sie navigieren in der Hauptschnittstelle, um auf System Manager Funktionen und Aufgaben zuzugreifen. 
---
= Erfahren Sie mehr über die SANtricity System Manager-Schnittstelle
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity System Manager ist eine webbasierte Schnittstelle, über die Sie Storage Array in einer einzigen Ansicht verwalten können.



== Homepage

Die Startseite enthält eine Dashboard-Ansicht für die tägliche Verwaltung Ihres Speicherarrays. Wenn Sie sich bei System Manager anmelden, wird die Startseite der erste Bildschirm angezeigt.

Die Dashboard-Ansicht umfasst drei Übersichtsbereiche, die wichtige Informationen über den Zustand und die Integrität Ihres Storage Arrays enthalten. Weitere Informationen finden Sie im Übersichtsbereich.

[cols="25h,~"]
|===
| Werden | Beschreibung 


 a| 
Leistung
 a| 
Im Bereich Performance können Sie die Ressourcennutzung im Laufe der Zeit vergleichen und gegenüberstellen. Sie können die Performance-Kennzahlen eines Storage-Arrays für Reaktionszeit (IOPS), Übertragungsraten (MiB/s) und die Menge der genutzten Verarbeitungskapazität (CPU) anzeigen.



 a| 
Kapazität
 a| 
Im Bereich Kapazität wird eine Diagrammansicht der zugewiesenen Kapazität, der freien Speicherkapazität und der nicht zugewiesenen Speicherkapazität im Speicher-Array angezeigt.



 a| 
Storage-Hierarchie
 a| 
Der Bereich Speicherhierarchie bietet eine organisierte Ansicht der verschiedenen Hardwarekomponenten und Speicherobjekte, die von Ihrem Speicher-Array verwaltet werden. Klicken Sie auf den Dropdown-Pfeil, um eine bestimmte Aktion für die Hardwarekomponente oder das Storage-Objekt auszuführen.

|===


== Benachrichtigungsbereich

Der Benachrichtigungsbereich ist über das Glockensymbol in der oberen Ecke des Fensters zugänglich. Der Benachrichtigungsbereich zeigt Problembenachrichtigungen an, die den Status des Speichersystems und seiner Komponenten anzeigen. Zusätzlich werden in diesem Bereich automatische Warnmeldungen angezeigt, die Ihnen bei der Fehlerbehebung helfen können, bevor sich Probleme auf andere Bereiche Ihrer Speicherumgebung auswirken.



== Schnittstelleneinstellungen

Sie können die Anzeigeeinstellungen und andere Einstellungen über die Hauptschnittstelle ändern.



== Benutzeranmeldungen und Passwörter

Der aktuell im System angemeldete Benutzer wird in den Benutzereinstellungen angezeigt.

Weitere Informationen zu Benutzern und Kennwörtern finden Sie unter:

* link:administrator-password-protection.html["Legen Sie den Schutz des Admin-Passworts fest"]
* link:../sm-settings/change-passwords.html["Passwörter ändern"]

