---
permalink: sm-interface/view-storage-hierarchy.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, storage hierarchy 
summary: Die Speicherhierarchie auf der Hauptschnittstelle bietet eine organisierte Ansicht der verschiedenen Hardwarekomponenten und Speicherobjekte, die von Ihrem Speicher-Array verwaltet werden. 
---
= Speicherhierarchie anzeigen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Speicherhierarchie auf der Hauptschnittstelle bietet eine organisierte Ansicht der verschiedenen Hardwarekomponenten und Speicherobjekte, die von Ihrem Speicher-Array verwaltet werden.

Um die Storage-Hierarchie anzuzeigen, wechseln Sie zur Startseite und klicken Sie auf den Dropdown-Pfeil für eine Storage-Array-Komponente oder ein Storage-Objekt. Ein Storage Array besteht aus einer Sammlung sowohl physischer als auch logischer Komponenten.



== Physische Komponenten

Die physischen Komponenten eines Storage-Arrays werden in dieser Tabelle beschrieben.

[cols="25h,~"]
|===
| Komponente | Beschreibung 


 a| 
Controller
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Sie steuert die Laufwerke und implementiert die Funktionen von System Manager.



 a| 
Shelf
 a| 
Ein Shelf ist ein Gehäuse, das in einem Schrank oder Rack installiert ist. Er enthält die Hardwarekomponenten für das Storage-Array. Es gibt zwei Typen von Shelfs: Ein Controller-Shelf und ein Festplatten-Shelf. Ein Controller Shelf enthält Controller und Laufwerke. Ein Festplatten-Shelf enthält ein-/Ausgabemodule (IOMs) und Laufwerke.

[NOTE]
====
Wenn Ihr Storage-Array unterschiedliche Medientypen oder Schnittstellentypen enthält, wird für jeden Laufwerkstyp ein Festplatten-Shelf angezeigt.

====


 a| 
Laufwerk
 a| 
Ein Laufwerk ist ein elektromagnetisches mechanisches Gerät oder ein Solid State-Speichergerät, das die physischen Speichermedien für Daten bereitstellt.



 a| 
Host
 a| 
Ein Host ist ein Server, der I/O an ein Volume auf einem Storage-Array sendet.



 a| 
Host Bus Adapter (HBA)
 a| 
Ein Host Bus Adapter (HBA) ist eine Platine, die sich auf einem Host befindet und einen oder mehrere Host-Ports enthält.



 a| 
Host-Port
 a| 
Ein Host Port ist ein Port an einem Host Bus Adapter (HBA), der die physische Verbindung zu einem Controller bereitstellt und für I/O-Vorgänge genutzt wird.



 a| 
Management- Client
 a| 
Ein Management-Client ist der Computer, auf dem ein Browser zum Zugriff auf System Manager installiert ist.

|===


== Logische Komponenten

Die Laufwerke im Speicher-Array stellen die physische Speicherkapazität für Daten bereit. Mit System Manager lässt sich die physische Kapazität in logischen Komponenten wie Pools, Volume-Gruppen und Volumes konfigurieren. Diese Komponenten sind die Tools, mit denen Sie Daten im Storage Array konfigurieren, speichern, warten und erhalten. In dieser Tabelle werden die logischen Komponenten eines Speicherarrays beschrieben.

[cols="25h,~"]
|===
| Komponente | Beschreibung 


 a| 
Pool
 a| 
Ein Pool ist eine Reihe von Laufwerken, die logisch gruppiert sind. Mit einem Pool können Sie ein oder mehrere Volumes erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einem Pool oder einer Volume-Gruppe.)



 a| 
Volume-Gruppe
 a| 
Eine Volume-Gruppe ist ein Container für Volumes mit gemeinsamen Merkmalen. Eine Volume-Gruppe verfügt über eine definierte Kapazität und einen RAID-Level. Sie können eine Volume-Gruppe verwenden, um ein oder mehrere Volumes zu erstellen, auf die ein Host zugreifen kann. (Sie erstellen Volumes entweder aus einer Volume-Gruppe oder aus einem Pool.)



 a| 
Datenmenge
 a| 
Ein Volume ist ein Container, in dem Applikationen, Datenbanken und Filesysteme Daten speichern. Dies ist die logische Komponente, die erstellt wird, damit der Host auf den Speicher des Speicherarrays zugreifen kann.



 a| 
Logical Unit Number (LUN)
 a| 
Eine Logical Unit Number (LUN) ist die Nummer, die dem Adressraum zugewiesen ist, den ein Host für den Zugriff auf ein Volume verwendet. Das Volume wird dem Host als Kapazität in Form einer LUN präsentiert.

Jeder Host verfügt über seinen eigenen LUN-Adressraum. Daher kann dieselbe LUN von unterschiedlichen Hosts für den Zugriff auf verschiedene Volumes verwendet werden.

|===