---
permalink: sm-interface/what-are-the-keyboard-shortcuts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, keyboard shortcuts 
summary: Sie können mit der Tastatur alleine durch den System Manager navigieren. 
---
= Was sind die Tastenkombinationen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können in SANtricity System Manager nur über die Tastatur navigieren.



== Gesamtnavigation

[cols="1a,1a"]
|===
| Aktion | Tastenkombination 


 a| 
Zum nächsten Element wechseln.
 a| 
Registerkarte



 a| 
Zum vorherigen Element wechseln.
 a| 
Umschalt + Tab



 a| 
Wählen Sie ein Element aus.
 a| 
Eingabe



 a| 
Dropdown-Liste: Zum nächsten oder vorherigen Element verschieben.
 a| 
Pfeil nach unten oder nach oben



 a| 
Kontrollkästchen - Wählen Sie ein Element aus.
 a| 
Leertaste



 a| 
Optionsfelder: Wechseln zwischen den Elementen.
 a| 
Pfeil nach unten oder nach oben



 a| 
Erweiterbarer Text – Erweiterung oder Vertragselement.
 a| 
Eingabe

|===


== Tabellennavigation

[cols="1a,1a"]
|===
| Aktion | Tastenkombination 


 a| 
Wählen Sie eine Zeile aus.
 a| 
Um eine Zeile auszuwählen, drücken Sie die Eingabetaste



 a| 
Blättern Sie nach oben oder unten.
 a| 
Pfeil nach unten/Pfeil nach oben oder Bild nach unten/Bild nach oben



 a| 
Ändern Sie die Sortierreihenfolge einer Spalte.
 a| 
Um eine Spaltenüberschrift auszuwählen, drücken Sie die Eingabetaste

|===


== Kalendernavigation

[cols="1a,1a"]
|===
| Aktion | Tastenkombination 


 a| 
Zum vorherigen Monat wechseln.
 a| 
Bild Nach Oben



 a| 
Zum nächsten Monat wechseln.
 a| 
Bild Nach Unten



 a| 
Wechseln Sie zum Vorjahr.
 a| 
Strg + Bild Nach Oben



 a| 
Gehen Sie zum nächsten Jahr.
 a| 
Strg + Bild Nach Unten



 a| 
Öffnen Sie die Datumauswahl, falls sie geschlossen ist.
 a| 
Control + Home



 a| 
Wechseln Sie zum aktuellen Monat.
 a| 
Steuerung / Befehl + Home



 a| 
Zum vorherigen Tag wechseln.
 a| 
Steuerung / Befehl + Links



 a| 
Gehen Sie zum nächsten Tag.
 a| 
Steuerung / Befehl + Rechts



 a| 
Wechseln Sie zur vorherigen Woche.
 a| 
Steuerung / Befehl + Nach Oben



 a| 
Gehen Sie zur nächsten Woche.
 a| 
Steuerung / Befehl + Nach Unten



 a| 
Wählen Sie das fokussierte Datum aus.
 a| 
Eingabe



 a| 
Schließen Sie die Datumsauswahl, und löschen Sie das Datum.
 a| 
Steuerung / Befehl + Ende



 a| 
Schließen Sie die Datumsauswahl ohne Auswahl.
 a| 
Flucht

|===