---
permalink: sm-hardware/configure-dns-server-addresses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, dns, server, addresses, 
summary: 'Mit dem Domain Name System (DNS) werden vollständig qualifizierte Domain-Namen für die Controller und ein NTP-Server (Network Time Protocol) aufgelöst. Die Management-Ports auf dem Speicher-Array können IPv4- oder IPv6-Protokolle gleichzeitig unterstützen.' 
---
= Konfigurieren Sie DNS-Serveradressen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Mit dem Domain Name System (DNS) werden vollständig qualifizierte Domain-Namen für die Controller und ein NTP-Server (Network Time Protocol) aufgelöst. Die Management-Ports auf dem Speicher-Array können IPv4- oder IPv6-Protokolle gleichzeitig unterstützen.

.Bevor Sie beginnen
* Ein DNS-Server muss in Ihrem Netzwerk installiert und konfiguriert sein.
* Sie kennen die Adresse des primären DNS-Servers und einen optionalen Backup-DNS-Server. Bei diesen Adressen können es sich um IPv4-Adressen oder IPv6-Adressen handeln.


In diesem Verfahren wird beschrieben, wie Sie eine primäre DNS-Serveradresse und eine DNS-Backup-Adresse angeben. Der Backup-DNS-Server kann optional so konfiguriert werden, dass er verwendet wird, wenn ein primärer DNS-Server ausfällt.

[NOTE]
====
Wenn Sie bereits die Management-Ports des Storage-Arrays mit DHCP (Dynamic Host Configuration Protocol) konfiguriert haben und ein oder mehrere DNS- oder NTP-Server mit dem DHCP-Setup verbunden sind, müssen Sie DNS oder NTP nicht manuell konfigurieren. In diesem Fall sollte das Speicher-Array bereits automatisch die DNS/NTP-Serveradressen erhalten haben. Sie sollten jedoch weiterhin die folgenden Anweisungen befolgen, um das Dialogfeld zu öffnen und sicherzustellen, dass die richtigen Adressen erkannt werden.

====
.Schritte
. Wählen Sie *Hardware*.
. Wenn die Grafik die Laufwerke anzeigt, klicken Sie auf *Zurück zum Regal anzeigen*.
+
Die Grafik ändert sich, um die Controller anstelle der Laufwerke anzuzeigen.

. Wählen Sie den zu konfigurierenden Controller aus.
+
Das Kontextmenü des Controllers wird angezeigt.

. Wählen Sie *DNS-Server konfigurieren*.
+
Das Dialogfeld DNS-Server konfigurieren wird geöffnet.

. Wählen Sie eine der folgenden Optionen:
+
** *DNS-Serveradressen werden automatisch vom DHCP-Server abgerufen* -- die erkannten DNS-Serveradressen werden angezeigt.
+
[NOTE]
====
Wenn das Speicherarray auf eine statische DNS-Adresse eingestellt ist, werden keine DNS-Server angezeigt.

====
** *DNS-Server-Adressen manuell angeben* -- Geben Sie eine primäre DNS-Server-Adresse und eine Backup-DNS-Server-Adresse ein. Der Backup-Server ist optional. (Diese Adressfelder werden angezeigt, nachdem Sie das Optionsfeld ausgewählt haben.) Bei diesen Adressen können es sich um IPv4-Adressen oder IPv6-Adressen handeln.


. Klicken Sie Auf *Speichern*.
. Wiederholen Sie diese Schritte für den anderen Controller.


Die DNS-Konfiguration wird auf der Registerkarte Controllereinstellungen *DNS/NTP* angezeigt.
