---
permalink: sm-hardware/faq-storage-controller.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= Speichercontroller-FAQ für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Was ist Auto-Negotiation?

Die automatische Aushandlung ist die Möglichkeit einer Netzwerkschnittstelle, ihre eigenen Verbindungsparameter (Geschwindigkeit und Duplex) automatisch mit einer anderen Netzwerkschnittstelle zu koordinieren.

Die automatische Aushandlung ist in der Regel die bevorzugte Einstellung für die Konfiguration von Management-Ports. Wenn die Aushandlung jedoch fehlschlägt, können falsch aufeinander abgestimmte Einstellungen der Netzwerkschnittstelle die Netzwerkleistung erheblich beeinträchtigen. In Fällen, in denen diese Bedingung nicht akzeptabel ist, sollten Sie die Einstellungen der Netzwerkschnittstelle manuell auf eine korrekte Konfiguration einstellen. Die automatische Aushandlung wird durch die Ethernet-Management-Ports des Controllers durchgeführt. Die automatische Aushandlung wird nicht von den iSCSI-Host-Bus-Adaptern durchgeführt.

[NOTE]
====
Wenn die automatische Aushandlung fehlschlägt, versucht der Controller, eine Verbindung bei 10BASE-T, Halbduplex, herzustellen. Dies ist der kleinste gemeinsame Nenner.

====


== Was ist eine statusfreie IPv6-Adressenkonfiguration?

Bei einer statusfreien automatischen Konfiguration erhalten Hosts keine Adressen und andere Konfigurationsinformationen von einem Server.

Die statusfreie automatische Konfiguration in IPv6 bietet Link-lokale Adressen, Multicasting und das Neighbor Discovery-Protokoll (ND). IPv6 kann die Schnittstellen-ID einer Adresse aus der zugrunde liegenden Datenverbindungslayer-Adresse generieren.

Eine statusfreie automatische Konfiguration und eine statusorientierte automatische Konfiguration ergänzen sich gegenseitig. Beispielsweise kann der Host statusfreie Auto-Konfiguration verwenden, um seine eigenen Adressen zu konfigurieren, aber verwenden Sie Stateful Auto-Configuration, um andere Informationen abzurufen. Die zustandsorientierte automatische Konfiguration ermöglicht Hosts, Adressen und andere Konfigurationsinformationen von einem Server abzurufen. Internet Protocol Version 6 (IPv6) definiert auch eine Methode, bei der alle IP-Adressen in einem Netzwerk gleichzeitig neu nummeriert werden können. IPv6 definiert eine Methode für Geräte im Netzwerk, um ihre IP-Adresse und andere Parameter automatisch ohne Server zu konfigurieren.

Geräte führen die folgenden Schritte durch, wenn eine statusfreie automatische Konfiguration verwendet wird:

. *Generieren Sie eine Link-local-Adresse* -- das Gerät erzeugt eine Link-local-Adresse, die 10 Bit, gefolgt von 54 Nullen und gefolgt von der 64-Bit-Schnittstellen-ID hat.
. *Testen Sie die Einzigartigkeit einer Link-local-Adresse* -- der Knoten testet, um sicherzustellen, dass die von ihm erzeugte Link-local-Adresse nicht bereits im lokalen Netzwerk verwendet wird. Der Knoten sendet mithilfe des ND-Protokolls eine „Neighbor“-Aufforderung. Das lokale Netzwerk wartet auf eine Meldung zur Anzeige des Nachbarn, die darauf hinweist, dass bereits ein anderes Gerät die Link-local-Adresse verwendet. In diesem Fall muss entweder eine neue Link-local-Adresse generiert werden, oder die automatische Konfiguration schlägt fehl, und eine andere Methode muss verwendet werden.
. *Zuweisen einer Link-lokalen Adresse* -- Wenn das Gerät den Eindeutigkeit-Test übergibt, weist das Gerät seiner IP-Schnittstelle die Link-lokale Adresse zu. Die Link-local Adresse kann für die Kommunikation im lokalen Netzwerk, aber nicht über das Internet verwendet werden.
. *Kontaktieren Sie den Router* -- der Knoten versucht, sich an einen lokalen Router zu wenden, um weitere Informationen zum Fortsetzen der Konfiguration zu erhalten. Dieser Kontakt wird entweder durch Abhören von regelmäßig von Routern gesendeten Routern-Werbemitteilungen oder durch Senden einer bestimmten Router-Nachricht ausgeführt, um einen Router um Informationen darüber zu bitten, was als Nächstes zu tun ist.
. *Anweisungen zum Knoten geben* -- der Router gibt dem Knoten Anweisungen, wie mit der automatischen Konfiguration fortzufahren. Alternativ teilt der Router dem Host mit, wie die globale Internetadresse ermittelt werden soll.
. *Konfigurieren Sie die globale Adresse* -- der Host konfiguriert sich mit seiner weltweit einzigartigen Internetadresse. Diese Adresse wird in der Regel aus einem Netzwerkpräfix gebildet, das dem Host vom Router bereitgestellt wird.




== Was soll ich wählen – DHCP oder manuelle Konfiguration?

Die Standardmethode für die Netzwerkkonfiguration ist DHCP (Dynamic Host Configuration Protocol). Verwenden Sie diese Option immer, wenn Ihr Netzwerk keinen DHCP-Server hat.



== Was ist ein DHCP-Server?

Dynamic Host Configuration Protocol (DHCP) ist ein Protokoll, das die Aufgabe der Zuweisung einer IP-Adresse (Internet Protocol) automatisiert.

Jedem Gerät, das mit einem TCP/IP-Netzwerk verbunden ist, muss eine eindeutige IP-Adresse zugewiesen werden. Zu diesen Geräten gehören die Controller in Ihrem Speicher-Array.

Ohne DHCP gibt ein Netzwerkadministrator diese IP-Adressen manuell ein. Wenn ein Client TCP/IP-Vorgänge starten muss, sendet der Client eine Anforderung für Adressinformationen aus. Der DHCP-Server erhält die Anforderung, weist eine neue Adresse für eine bestimmte Zeitspanne, die als Leasing-Zeitraum bezeichnet wird, zu und sendet die Adresse an den Client. Bei DHCP kann ein Gerät bei jeder Verbindung mit dem Netzwerk eine andere IP-Adresse haben. In einigen Systemen kann sich die IP-Adresse des Geräts auch dann ändern, wenn das Gerät noch angeschlossen ist.



== Wie konfiguriere ich meinen DHCP-Server?

Sie müssen einen DHCP-Server (Dynamic Host Configuration Protocol) konfigurieren, damit die Controller im Speicher-Array statische IP-Adressen (Internet Protocol) verwenden können.

Die IP-Adressen, die Ihrem DHCP-Server zugewiesen werden, sind im Allgemeinen dynamisch und können sich ändern, da sie über einen Leasingzeitraum verfügen, der abgelaufen ist. Einige Geräte, zum Beispiel Server und Router, müssen statische Adressen verwenden. Die Controller im Speicher-Array benötigen auch statische IP-Adressen.

Informationen zum Zuweisen statischer Adressen finden Sie in der Dokumentation für Ihren DHCP-Server.



== Warum muss ich die Controller-Netzwerkkonfiguration ändern?

Sie müssen die Netzwerkkonfiguration für jeden Controller festlegen: IP-Adresse (Internet Protocol), Subnetzmaske (Subnetzmaske) und Gateway – wenn Sie Out-of-Band-Management verwenden.

Sie können die Netzwerkkonfiguration mithilfe eines DHCP-Servers (Dynamic Host Configuration Protocol) festlegen. Wenn Sie keinen DHCP-Server verwenden, müssen Sie die Netzwerkkonfiguration manuell eingeben.



== Wo erhalte ich die Netzwerkkonfiguration?

Sie können die IP-Adresse (Internet Protocol), die Subnetzmaske (Subnetzmaske) und Gateway-Informationen von Ihrem Netzwerkadministrator abrufen.

Sie benötigen diese Informationen, wenn Sie Ports auf den Controllern konfigurieren.



== Was sind ICMP PING Antworten?

Internet Control Message Protocol (ICMP) ist eines der Protokolle der TCP/IP-Suite.

Der `ICMP echo request` Und das(`ICMP echo reply` Nachrichten sind allgemein bekannt als `ping` Nachrichten. `Ping` Ist ein Fehlerbehebungstool, das von Systemadministratoren verwendet wird, um die Verbindung zwischen Netzwerkgeräten manuell zu testen und auch auf Netzwerkverzögerung und Paketverlust zu testen. Der `ping` Befehl sendet ein `ICMP echo request` Auf ein Gerät im Netzwerk, und das Gerät reagiert sofort mit ein(`ICMP echo reply`. Manchmal erfordert die Netzwerksicherheitsrichtlinie eines Unternehmens `ping` (`ICMP echo reply`Auf allen Geräten zu deaktivieren, um sie durch unbefugte Personen schwieriger zu entdecken.



== Wann sollte ich die Portkonfiguration aktualisieren?

Aktualisieren Sie den DHCP-Server jederzeit, wenn der Server geändert oder aktualisiert wird, und die für das aktuelle Speicher-Array und das Speicherarray, das Sie verwenden möchten, relevanten DHCP-Informationen wurden geändert.

Aktualisieren Sie insbesondere die Portkonfiguration oder den iSNS-Server vom DHCP-Server, wenn Sie wissen, dass der DHCP-Server unterschiedliche Adressen zugewiesen.

[NOTE]
====
Die Aktualisierung einer Portkonfiguration ist für alle iSCSI-Verbindungen an diesem Port destruktiv.

====


== Was soll ich nach dem Konfigurieren der Management-Ports tun?

Wenn Sie die IP-Adresse für das Speicher-Array geändert haben, möchten Sie möglicherweise die Ansicht des globalen Arrays in SANtricity Unified Manager aktualisieren.

Um die Ansicht des globalen Arrays in Unified Manager zu aktualisieren, öffnen Sie die Schnittstelle und gehen Sie zum Menü:Verwalten[Entdecken].

Wenn Sie noch den SANtricity-Speicher-Manager verwenden, gehen Sie zum Enterprise Management-Fenster (EMW), wo Sie die neue IP-Adresse entfernen und erneut hinzufügen müssen.



== Warum befindet sich das Storage-System im nicht optimalen Modus?

Ein Speichersystem im nicht optimalen Modus ist auf einen ungültigen Konfigurationsstatus des Systems zurückzuführen. Trotz dieses Status wird der normale I/O-Zugriff auf vorhandene Volumes vollständig unterstützt, der SANtricity System Manager untersagt jedoch einige Vorgänge.

Ein Storage-System könnte aus einem der folgenden Gründe auf eine ungültige Systemkonfiguration überführen:

* Der Controller ist nicht mehr konform, möglicherweise weil er einen falschen Untermodell-ID-Code (SMID) hat oder die Obergrenze der Premium-Features überschritten hat.
* Es wird ein interner Servicevorgang ausgeführt, z. B. ein Download der Laufwerk-Firmware.
* Der Controller hat den Paritätsfehlerschwellenwert überschritten und tritt gesperrt auf.
* Eine allgemeine Sperrbedingung ist aufgetreten.

