---
permalink: sm-hardware/what-is-auto-negotiation.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, auto, negotiation, network, interface, 
summary: 'Die automatische Aushandlung ist die Möglichkeit einer Netzwerkschnittstelle, ihre eigenen Verbindungsparameter (Geschwindigkeit und Duplex) automatisch mit einer anderen Netzwerkschnittstelle zu koordinieren.' 
---
= Was ist Auto-Negotiation?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die automatische Aushandlung ist die Möglichkeit einer Netzwerkschnittstelle, ihre eigenen Verbindungsparameter (Geschwindigkeit und Duplex) automatisch mit einer anderen Netzwerkschnittstelle zu koordinieren.

Die automatische Aushandlung ist in der Regel die bevorzugte Einstellung für die Konfiguration von Management-Ports. Wenn die Aushandlung jedoch fehlschlägt, können falsch aufeinander abgestimmte Einstellungen der Netzwerkschnittstelle die Netzwerkleistung erheblich beeinträchtigen. In Fällen, in denen diese Bedingung nicht akzeptabel ist, sollten Sie die Einstellungen der Netzwerkschnittstelle manuell auf eine korrekte Konfiguration einstellen. Die automatische Aushandlung wird durch die Ethernet-Management-Ports des Controllers durchgeführt. Die automatische Aushandlung wird nicht von den iSCSI-Host-Bus-Adaptern durchgeführt.

[NOTE]
====
Wenn die automatische Aushandlung fehlschlägt, versucht der Controller, eine Verbindung bei 10BASE-T, Halbduplex, herzustellen. Dies ist der kleinste gemeinsame Nenner.

====