---
permalink: sm-hardware/what-are-battery-learn-cycles.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, battery, learn, cycle, 
summary: Ein Lernzyklus ist ein automatischer Zyklus zum Kalibrieren der intelligenten Akkuanzeige. 
---
= Was sind Akkulaufläufe?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Lernzyklus ist ein automatischer Zyklus zum Kalibrieren der intelligenten Akkuanzeige.

Ein Lernzyklus besteht aus folgenden Phasen:

* Kontrollierte Batterieentladung
* Ruheperiode
* Laden


Die Batterien werden bis zu einem vorgegebenen Schwellenwert entladen. In dieser Phase wird die Batteriehuchte kalibriert.

Für einen Lernzyklus sind die folgenden Parameter erforderlich:

* Vollständig aufgeladene Batterien
* Keine überhitzten Batterien


Lernzyklen für Duplex-Controller-Systeme werden gleichzeitig ausgeführt. Für Controller mit Sicherungsstrom aus mehr als einer Batterie oder einer Reihe von Batteriezellen treten nacheinander Lernzyklen auf.

Die Lernzyklen werden in regelmäßigen Abständen, zur gleichen Zeit und am selben Tag der Woche, automatisch gestartet. Das Intervall zwischen den Zyklen wird in Wochen beschrieben.

[NOTE]
====
Ein Lernzyklus kann mehrere Stunden in Anspruch nehmen.

====