---
permalink: sm-hardware/what-are-icmp-ping-responses.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, icmp, ping, responses, message, protocol, 
summary: 'Internet Control Message Protocol (ICMP) ist eines der Protokolle der TCP/IP-Suite.' 
---
= Was sind ICMP PING Antworten?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Internet Control Message Protocol (ICMP) ist eines der Protokolle der TCP/IP-Suite.

Der `ICMP echo request` Und das(`ICMP echo reply` Nachrichten sind allgemein bekannt als `ping` Nachrichten. `Ping` Ist ein Fehlerbehebungstool, das von Systemadministratoren verwendet wird, um die Verbindung zwischen Netzwerkgeräten manuell zu testen und auch auf Netzwerkverzögerung und Paketverlust zu testen. Der `ping` Befehl sendet ein `ICMP echo request` Auf ein Gerät im Netzwerk, und das Gerät reagiert sofort mit ein(`ICMP echo reply`. Manchmal erfordert die Netzwerksicherheitsrichtlinie eines Unternehmens `ping` (`ICMP echo reply`Auf allen Geräten zu deaktivieren, um sie durch unbefugte Personen schwieriger zu entdecken.
