---
permalink: sm-hardware/why-is-the-storage-system-in-non-optimal-mode.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, non-optimal, mode, 
summary: Ein Speichersystem im nicht optimalen Modus ist auf einen ungültigen Konfigurationsstatus des Systems zurückzuführen. Trotz dieses Status wird ein normaler I/O-Zugriff auf vorhandene Volumes vollständig unterstützt. System Manager untersagt jedoch einige Operationen. 
---
= Warum befindet sich das Storage-System im nicht optimalen Modus?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ein Speichersystem im nicht optimalen Modus ist auf einen ungültigen Konfigurationsstatus des Systems zurückzuführen. Trotz dieses Status wird ein normaler I/O-Zugriff auf vorhandene Volumes vollständig unterstützt. System Manager untersagt jedoch einige Operationen.

Ein Storage-System könnte aus einem der folgenden Gründe auf eine ungültige Systemkonfiguration überführen:

* Der Controller ist nicht mehr konform, möglicherweise weil er einen falschen Untermodell-ID-Code (SMID) hat oder die Obergrenze der Premium-Features überschritten hat.
* Es wird ein interner Servicevorgang ausgeführt, z. B. ein Download der Laufwerk-Firmware.
* Der Controller hat den Paritätsfehlerschwellenwert überschritten und tritt gesperrt auf.
* Eine allgemeine Sperrbedingung ist aufgetreten.

