---
permalink: um-manage/discover-multiple-arrays.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, discover, multiple, storage, arrays 
summary: Sie erkennen mehrere Arrays, um alle Speicher-Arrays im Subnetz zu erkennen, in dem sich der Verwaltungsserver befindet, und um automatisch die ermittelten Arrays zu Ihrer Verwaltungsdomäne hinzuzufügen. 
---
= Erkennung mehrerer Storage-Arrays
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie erkennen mehrere Arrays, um alle Speicher-Arrays im Subnetz zu erkennen, in dem sich der Verwaltungsserver befindet, und um automatisch die ermittelten Arrays zu Ihrer Verwaltungsdomäne hinzuzufügen.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das die Berechtigungen für den Sicherheitsadministrator enthält.
* Das Speicher-Array muss ordnungsgemäß eingerichtet und konfiguriert sein.
* Passwörter für das Storage-Array müssen mithilfe der Kachel „System Manager Access Management“ eingerichtet werden.
* Um nicht vertrauenswürdige Zertifikate zu lösen, müssen Sie vertrauenswürdige Zertifikatdateien von einer Zertifizierungsstelle (CA) haben, und die Zertifikatdateien sind auf Ihrem lokalen System verfügbar.


Das Erkennen von Arrays ist ein mehrstufiges Verfahren.



== Schritt 1: Geben Sie die Netzwerkadresse ein

Sie geben einen Netzwerkaddress Range ein, um im lokalen Subnetzwerk zu suchen. Jedes erfolgreich erreichte Speicher-Array wird auf der Seite Erkennung angezeigt und kann Ihrer Management-Domäne hinzugefügt werden.

Wenn Sie den Ermittlungsvorgang aus irgendeinem Grund beenden möchten, klicken Sie auf *Erkennung stoppen*.

.Schritte
. Wählen Sie auf der Seite Verwalten die Option *Hinzufügen/Entdecken*.
+
Das Dialogfeld Hinzufügen/Entdecken wird angezeigt.

. Wählen Sie das Optionsfeld *Alle Speicher-Arrays in einem Netzwerkbereich* aus.
. Geben Sie die Startnetzwerkadresse und die Endung der Netzwerkadresse ein, um im lokalen Teilnetzwerk zu suchen, und klicken Sie dann auf *Erkennung starten*.
+
Der Erkennungsvorgang wird gestartet. Dieser Erkennungsvorgang kann mehrere Minuten dauern. Die Tabelle auf der Seite „Entdecken“ wird bei der Erkennung der Speicher-Arrays ausgefüllt.

+
[NOTE]
====
Wenn keine verwaltbaren Arrays erkannt werden, überprüfen Sie, ob die Speicher-Arrays ordnungsgemäß mit Ihrem Netzwerk verbunden sind und die zugewiesenen Adressen innerhalb der Reichweite liegen. Klicken Sie auf *Neue Ermittlungsparameter*, um zur Seite Hinzufügen/Entdecken zurückzukehren.

====
. Überprüfen Sie die Liste der erkannten Speicher-Arrays.
. Aktivieren Sie das Kontrollkästchen neben einem beliebigen Speicher-Array, das Sie Ihrer Management-Domäne hinzufügen möchten, und klicken Sie dann auf *Weiter*.
+
Unified Manager führt eine Überprüfung der Anmeldeinformationen für jedes Array durch, das Sie der Management-Domäne hinzufügen. Möglicherweise müssen Sie alle selbstsignierten Zertifikate und nicht vertrauenswürdigen Zertifikate, die mit diesem Array verknüpft sind, auflösen.

. Klicken Sie auf *Weiter*, um mit dem nächsten Schritt im Assistenten fortzufahren.




== Schritt 2: Lösen Sie selbst signierte Zertifikate während der Ermittlung

Während der Bestandsaufnahme überprüft das System, ob die Speicher-Arrays Zertifikate von einer vertrauenswürdigen Quelle verwenden.

.Schritte
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie den Verbindungen zu den erkannten Speicherarrays vertrauen, fahren Sie mit der nächsten Karte im Assistenten fort. Die selbstsignierten Zertifikate werden als vertrauenswürdig markiert und die Speicher-Arrays werden zu Unified Manager hinzugefügt.
** Wenn Sie den Verbindungen zu den Speicher-Arrays nicht vertrauen, wählen Sie *Abbrechen* und validieren Sie die Sicherheitszertifikatstrategie jedes Speicherarrays, bevor Sie eine dieser Verbindungen zu Unified Manager hinzufügen.


. Klicken Sie auf *Weiter*, um mit dem nächsten Schritt im Assistenten fortzufahren.




== Schritt 3: Lösen Sie nicht vertrauenswürdige Zertifikate während der Ermittlung

Nicht vertrauenswürdige Zertifikate treten auf, wenn ein Speicher-Array versucht, eine sichere Verbindung zu Unified Manager herzustellen, die Verbindung jedoch nicht als sicher bestätigt werden kann. Während der Array-Ermittlung können Sie nicht vertrauenswürdige Zertifikate auflösen, indem Sie ein Zertifikat (CA-Zertifikat) importieren, das von einem vertrauenswürdigen Dritten ausgestellt wurde.

Möglicherweise müssen Sie zusätzliche vertrauenswürdige CA-Zertifikate installieren, wenn eine der folgenden Optionen zutrifft:

* Sie haben kürzlich ein Speicher-Array hinzugefügt.
* Ein oder beide Zertifikate sind abgelaufen.
* Ein oder beide Zertifikate werden widerrufen.
* Ein oder beide Zertifikate fehlen ein Stammzertifikat oder ein Zwischenzertifikat.


.Schritte
. Aktivieren Sie das Kontrollkästchen neben einem beliebigen Speicherarray, für das Sie nicht vertrauenswürdige Zertifikate auflösen möchten, und wählen Sie dann die Schaltfläche **Importieren**.
+
Es wird ein Dialogfeld zum Importieren der vertrauenswürdigen Zertifikatdateien geöffnet.

. Klicken Sie auf *Durchsuchen*, um die Zertifikatdateien für die Speicher-Arrays auszuwählen.
+
Die Dateinamen werden im Dialogfeld angezeigt.

. Klicken Sie Auf *Import*.
+
Die Dateien werden hochgeladen und validiert.

+
[NOTE]
====
Jedes Speicherarray mit nicht vertrauenswürdigen Zertifikatproblemen, die nicht gelöst wurden, wird Unified Manager nicht hinzugefügt.

====
. Klicken Sie auf *Weiter*, um mit dem nächsten Schritt im Assistenten fortzufahren.




== Schritt 4: Geben Sie Passwörter ein

Sie müssen die Passwörter für die Speicher-Arrays eingeben, die Sie Ihrer Management-Domäne hinzufügen möchten.

.Schritte
. Geben Sie das Passwort für jedes Speicher-Array ein, das Sie zu Unified Manager hinzufügen möchten.
. *Optional:* Speicher-Arrays einer Gruppe zuordnen: Wählen Sie aus der Dropdown-Liste die gewünschte Gruppe aus, die mit den ausgewählten Speicher-Arrays verknüpft werden soll.
. Klicken Sie Auf *Fertig Stellen*.


Die Speicher-Arrays werden Ihrer Management-Domäne hinzugefügt und der ausgewählten Gruppe zugeordnet (falls angegeben).

[NOTE]
====
Es kann mehrere Minuten dauern, bis Unified Manager eine Verbindung zu den angegebenen Storage-Arrays hergestellt hat.

====