---
permalink: um-manage/how-upgrades-work.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrades, 
summary: Sie können Unified Manager verwenden, um ein Upgrade der SANtricity OS Software auf mehreren Storage Arrays desselben Typs auf eine neuere Version durchzuführen. 
---
= Wie Upgrades funktionieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager verwenden, um ein Upgrade der SANtricity OS Software auf mehreren Storage Arrays desselben Typs auf eine neuere Version durchzuführen.



== Workflow-Upgrade

Die folgenden Schritte bieten einen grundlegenden Workflow zur Durchführung von Software-Upgrades:

. Sie laden die aktuelle SANtricity OS-Softwaredatei von der Support-Website herunter (ein Link ist im Unified Manager auf der Seite *Support* verfügbar). Speichern Sie die Datei auf dem Management-Host-System (dem Host, auf dem Sie in einem Browser auf Unified Manager zugreifen), und entpacken Sie die Datei anschließend.
. In Unified Manager laden Sie die Softwaredatei des SANtricity-Betriebssystems und die NVSRAM-Datei in das Repository (ein Bereich des Web-Services-Proxyservers, auf dem Dateien gespeichert sind). Sie können Dateien entweder über das Menü:Upgrade Center[Upgrade SANtricity OS Software oder über Upgrade Center > Software-Repository verwalten] hinzufügen.
. Nachdem die Dateien in das Repository geladen wurden, können Sie die Datei auswählen, die für das Upgrade verwendet werden soll. Wählen Sie auf der Seite Software Upgrade SANtricity OS (Menü:Upgrade Center [Upgrade SANtricity OS Software]) die Software-Datei SANtricity OS und die NVSRAM-Datei aus. Nach Auswahl einer Softwaredatei wird auf dieser Seite eine Liste kompatibler Speicher-Arrays angezeigt. Anschließend wählen Sie die Speicher-Arrays aus, die Sie mit der neuen Software aktualisieren möchten. (Sie können nicht inkompatible Arrays auswählen.)
. Anschließend können Sie eine sofortige Softwareübertragung und -Aktivierung starten oder die Dateien zu einem späteren Zeitpunkt für die Aktivierung aktivieren. Während des Upgrades führt Unified Manager die folgenden Aufgaben aus:
+
.. Durchführung einer Integritätsprüfung für die Speicher-Arrays, um festzustellen, ob Bedingungen vorhanden sind, die das Upgrade möglicherweise verhindern. Wenn Arrays die Integritätsprüfung nicht bestanden haben, können Sie das jeweilige Array überspringen und das Upgrade für die anderen fortsetzen. Alternativ können Sie den gesamten Prozess beenden und die Arrays, die nicht bestanden haben, beheben.
.. Überträgt die Upgrade-Dateien an jeden Controller.
.. Bootet die Controller neu und aktiviert die neue SANtricity OS Software, die jeweils einen Controller umfasst. Während der Aktivierung wird die vorhandene SANtricity OS-Datei durch die neue Datei ersetzt.
+
[NOTE]
====
Sie können auch angeben, dass die Software zu einem späteren Zeitpunkt aktiviert wird.

====






== Sofortiges oder stufenweise Upgrade

Sie können das Upgrade sofort aktivieren oder es für einen späteren Zeitpunkt aktivieren. Aus folgenden Gründen können Sie sich später aktivieren:

* *Tageszeit* -- die Aktivierung der Software kann eine lange Zeit dauern, so dass Sie möglicherweise warten möchten, bis I/O-Lasten leichter sind. Je nach I/O-Last und Cache-Größe kann ein Controller-Upgrade in der Regel zwischen 15 und 25 Minuten dauern. Die Controller starten neu und führen einen Failover während der Aktivierung durch. Dadurch kann die Performance bis zum Abschluss des Upgrades unter Umständen niedriger sein als üblich.
* *Paketyp* -- möglicherweise möchten Sie die neue Software und Firmware auf einem Speicher-Array testen, bevor Sie die Dateien auf anderen Speicher-Arrays aktualisieren.


Um die stufenweise Software zu aktivieren, gehen Sie zum Menü:Support[Upgrade Center] und klicken Sie im Bereich SANtricity OS-Controller-Software-Upgrade auf *Aktivieren*.



== Zustandsprüfung

Eine Integritätsprüfung wird im Rahmen des Upgrade-Prozesses ausgeführt, Sie können aber auch vor dem Start eine Integritätsprüfung separat durchführen (siehe Menü:Upgrade Center [Health Check vor dem Upgrade]).

Bei der Integritätsprüfung werden alle Storage-Systemkomponenten bewertet, um sicherzustellen, dass das Upgrade fortgesetzt werden kann. Die folgenden Bedingungen können das Upgrade verhindern:

* Ausgefallene zugewiesene Laufwerke
* Hot Spares werden verwendet
* Unvollständige Volume-Gruppen
* Exklusive Vorgänge ausgeführt
* Fehlende Volumes
* Controller befindet sich im Status „nicht optimal“
* Übermäßige Anzahl von Ereignisprotokollereignissen
* Fehler bei der Validierung der Konfigurationsdatenbank
* Laufwerke mit alten Versionen von DACstore

