---
permalink: um-manage/import-autosupport-settings.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, import, autosupport, settings 
summary: Sie können eine AutoSupport-Konfiguration von einem Speicher-Array in andere Speicher-Arrays importieren. Dieser Batch-Betrieb spart Zeit, wenn Sie mehrere Arrays im Netzwerk konfigurieren müssen. 
---
= AutoSupport-Einstellungen importieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können eine AutoSupport-Konfiguration von einem Speicher-Array in andere Speicher-Arrays importieren. Dieser Batch-Betrieb spart Zeit, wenn Sie mehrere Arrays im Netzwerk konfigurieren müssen.

.Bevor Sie beginnen
* AutoSupport ist in System Manager für das Storage-Array konfiguriert, das als Quelle verwendet werden soll (Menü:Support[Support Center]).
* Die vorhandene Konfiguration für die Ziel-Speicher-Arrays wird in System Manager gesichert (Menü:Einstellungen[System > Speicherarray-Konfiguration speichern]).


.Über diese Aufgabe
Zu den importierten Einstellungen gehören die separaten Funktionen (Basic AutoSupport, AutoSupport OnDemand und Remote Diagnostics), das Wartungsfenster, die Bereitstellungsmethode, Und dem Versandplan.

.Schritte
. Klicken Sie auf der Seite Verwalten auf *Einstellungen importieren*.
+
Der Assistent für Importeinstellungen wird geöffnet.

. Wählen Sie im Dialogfeld Einstellungen auswählen die Option *AutoSupport* aus und klicken Sie dann auf *Weiter*.
+
Zum Auswählen des Quell-Arrays wird ein Dialogfeld geöffnet.

. Wählen Sie im Dialogfeld Quelle auswählen das Array mit den Einstellungen aus, die Sie importieren möchten, und klicken Sie dann auf *Weiter*.
. Wählen Sie im Dialogfeld Ziele auswählen ein oder mehrere Arrays aus, um die neuen Einstellungen zu erhalten.
+
[NOTE]
====
Speicher-Arrays mit Firmware unter 8.50 stehen nicht zur Auswahl. Darüber hinaus wird ein Array nicht in diesem Dialogfeld angezeigt, wenn Unified Manager nicht mit dem Array kommunizieren kann (z. B. wenn es offline ist oder wenn es über Zertifikat-, Kennwort- oder Netzwerkprobleme verfügt).

====
. Klicken Sie Auf *Fertig Stellen*.
+
Auf der Seite Operationen werden die Ergebnisse des Importvorgangs angezeigt. Wenn der Vorgang fehlschlägt, können Sie auf die Zeile klicken, um weitere Informationen anzuzeigen.



.Ergebnisse
Die Ziel-Storage-Arrays sind nun mit denselben AutoSupport-Einstellungen wie das Quell-Array konfiguriert.
