---
permalink: um-manage/manage-repository.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, manage, software, repository 
summary: Das Software-Repository enthält alle Softwaredateien, die dem Web Services Proxy zugeordnet sind. 
---
= Software-Repository managen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Software-Repository enthält alle Softwaredateien, die dem Web Services Proxy zugeordnet sind.

Wenn Sie die Datei nicht sehen, die Sie verwenden möchten, können Sie mithilfe der Option Software-Repository verwalten eine oder mehrere SANtricity-Betriebssystemdateien auf das Hostsystem importieren, auf dem der Webservices-Proxy und Unified Manager ausgeführt werden. Sie können auch festlegen, dass eine oder mehrere SANtricity OS-Dateien gelöscht werden sollen, die im Software-Repository verfügbar sind.

Wenn Sie SANtricity OS-Dateien hinzufügen, stellen Sie sicher, dass die Betriebssystemdateien auf Ihrem lokalen System verfügbar sind.

.Schritte
. Wählen Sie in der Hauptansicht *Verwalten* und dann Menü:Upgrade Center[Software-Repository verwalten].
+
Das Dialogfeld Software-Repository verwalten wird angezeigt.

. Führen Sie eine der folgenden Aktionen aus:
+
[cols="25h,~"]
|===
| Option | Tun Sie das 


 a| 
Importieren
 a| 
.. Klicken Sie Auf *Import.*
.. Klicken Sie auf *Durchsuchen* und navigieren Sie dann zu dem Speicherort, an dem die Betriebssystemdateien gespeichert werden sollen.
+
Betriebssystemdateien haben einen ähnlichen Dateinamen wie `N2800-830000-000.dlp`.

.. Wählen Sie eine oder mehrere Betriebssystemdateien aus, die Sie hinzufügen möchten, und klicken Sie dann auf *Import*.




 a| 
Löschen
 a| 
.. Wählen Sie eine oder mehrere Betriebssystemdateien aus, die Sie aus dem Software-Repository entfernen möchten.
.. Klicken Sie Auf *Löschen*.


|===


Wenn Sie den Import ausgewählt haben, werden die Dateien hochgeladen und validiert. Wenn Sie „Löschen“ ausgewählt haben, werden die Dateien aus dem Software-Repository entfernt.
