---
permalink: um-manage/overview-upgrade-center-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, center 
summary: Im Upgrade Center können Sie SANtricity OS Software und NVSRAM Upgrades für mehrere Storage Arrays managen. 
---
= Übersicht zum Upgrade Center
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Upgrade Center können Sie SANtricity OS Software und NVSRAM Upgrades für mehrere Storage Arrays managen.



== Wie funktionieren Upgrades?

Sie laden die neueste Betriebssystemsoftware herunter und aktualisieren dann ein oder mehrere Arrays.



=== Workflow-Upgrade

Die folgenden Schritte ermöglichen einen grundlegenden Workflow bei der Durchführung von Software-Upgrades.

. Sie laden die aktuelle SANtricity OS Softwaredatei von der Support-Website herunter. (Auf der Support-Seite ist ein Link von Unified Manager verfügbar) Speichern Sie die Datei auf dem Management-Host-System (dem Host, auf dem Sie in einem Browser auf Unified Manager zugreifen), und entpacken Sie die Datei anschließend.
. In Unified Manager laden Sie die Softwaredatei des SANtricity-Betriebssystems und die NVSRAM-Datei in das Repository (ein Bereich des Web-Services-Proxyservers, auf dem Dateien gespeichert sind). Sie können Dateien entweder über das Menü:Upgrade Center[Upgrade SANtricity OS Software oder über Upgrade Center > Software-Repository verwalten] hinzufügen.
. Nachdem die Dateien in das Repository geladen wurden, können Sie die Datei auswählen, die für das Upgrade verwendet werden soll. Wählen Sie auf der Seite Software Upgrade SANtricity OS (Menü:Upgrade Center [Upgrade SANtricity OS Software]) die Software-Datei SANtricity OS und die NVSRAM-Datei aus. Nach Auswahl einer Softwaredatei wird auf dieser Seite eine Liste kompatibler Speicher-Arrays angezeigt. Anschließend wählen Sie die Speicher-Arrays aus, die Sie mit der neuen Software aktualisieren möchten. (Sie können nicht inkompatible Arrays auswählen.)
. Anschließend können Sie eine sofortige Softwareübertragung und -Aktivierung starten oder die Dateien zu einem späteren Zeitpunkt für die Aktivierung aktivieren. Während des Upgrades führt Unified Manager die folgenden Aufgaben aus:
+
.. Durchführung einer Integritätsprüfung für die Speicher-Arrays, um festzustellen, ob Bedingungen vorhanden sind, die das Upgrade möglicherweise verhindern. Wenn Arrays die Integritätsprüfung nicht bestanden haben, können Sie das jeweilige Array überspringen und das Upgrade für die anderen fortsetzen. Alternativ können Sie den gesamten Prozess beenden und die Arrays, die nicht bestanden haben, beheben.
.. Überträgt die Upgrade-Dateien an jeden Controller.
.. Bootet die Controller neu und aktiviert die neue SANtricity OS Software, die jeweils einen Controller umfasst. Während der Aktivierung wird die vorhandene SANtricity OS-Datei durch die neue Datei ersetzt.
+
[NOTE]
====
Sie können auch angeben, dass die Software zu einem späteren Zeitpunkt aktiviert wird.

====






=== Sofortiges oder stufenweise Upgrade

Sie können das Upgrade sofort aktivieren oder es für einen späteren Zeitpunkt aktivieren. Aus folgenden Gründen können Sie sich später aktivieren:

* *Tageszeit* -- die Aktivierung der Software kann eine lange Zeit dauern, so dass Sie möglicherweise warten möchten, bis I/O-Lasten leichter sind. Je nach I/O-Last und Cache-Größe kann ein Controller-Upgrade in der Regel zwischen 15 und 25 Minuten dauern. Die Controller starten neu und führen einen Failover während der Aktivierung durch. Dadurch kann die Performance bis zum Abschluss des Upgrades unter Umständen niedriger sein als üblich.
* *Paketyp* -- möglicherweise möchten Sie die neue Software und Firmware auf einem Speicher-Array testen, bevor Sie die Dateien auf anderen Speicher-Arrays aktualisieren.


Um die stufenweise Software zu aktivieren, gehen Sie zum Menü:Support[Upgrade Center] und klicken Sie im Bereich SANtricity OS-Controller-Software-Upgrade auf *Aktivieren*.



=== Zustandsprüfung

Eine Integritätsprüfung wird im Rahmen des Upgrade-Prozesses ausgeführt, Sie können aber auch vor dem Start eine Integritätsprüfung separat durchführen (siehe Menü:Upgrade Center [Health Check vor dem Upgrade]).

Bei der Integritätsprüfung werden alle Storage-Systemkomponenten bewertet, um sicherzustellen, dass das Upgrade fortgesetzt werden kann. Die folgenden Bedingungen können das Upgrade verhindern:

* Ausgefallene zugewiesene Laufwerke
* Hot Spares werden verwendet
* Unvollständige Volume-Gruppen
* Exklusive Vorgänge ausgeführt
* Fehlende Volumes
* Controller befindet sich im Status „nicht optimal“
* Übermäßige Anzahl von Ereignisprotokollereignissen
* Fehler bei der Validierung der Konfigurationsdatenbank
* Laufwerke mit alten Versionen von DACstore




== Was muss ich vor einem Upgrade beachten?

Vor dem Upgrade mehrerer Storage-Arrays sollten Sie die wichtigsten Überlegungen in Ihrer Planung durchgehen.



=== Aktuelle Versionen

Sie können die aktuellen Softwareversionen des SANtricity Betriebssystems von der Seite Verwalten von Unified Manager für jedes erkannte Storage-Array anzeigen. Die Version wird in der Spalte SANtricity OS Software angezeigt. Die Informationen zu Controller-Firmware und NVSRAM finden Sie in einem Popup-Dialogfeld, wenn Sie in den einzelnen Zeilen auf die SANtricity OS-Version klicken.



=== Andere Komponenten müssen aktualisiert werden

Im Rahmen des Upgrades müssen Sie eventuell auch den Multipath-/Failover-Treiber oder den HBA-Treiber des Hosts aktualisieren, damit der Host korrekt mit den Controllern interagieren kann.

Informationen zur Kompatibilität finden Sie im https://imt.netapp.com/matrix/#welcome["NetApp Interoperabilitätsmatrix"^]. Lesen Sie auch die Verfahren in den Express-Leitfäden für Ihr Betriebssystem. Express-Leitfäden finden Sie im https://docs.netapp.com/us-en/e-series/index.html["E-Series und SANtricity Dokumentation"^].



=== Dual-Controller

Wenn ein Storage-Array zwei Controller enthält und ein Multipath-Treiber installiert ist, kann das Storage-Array die I/O-Verarbeitung während des Upgrades fortsetzen. Während des Upgrades erfolgt der folgende Vorgang:

. Controller A Failover aller LUNs zu Controller B
. Das Upgrade erfolgt bei Controller A
. Controller A nimmt seine LUNs und alle Controller B LUNs wieder auf.
. Upgrade erfolgt auf Controller B.


Nach Abschluss des Upgrades müssen Sie Volumes möglicherweise manuell zwischen den Controllern neu verteilen, um sicherzustellen, dass die Volumes wieder zum korrekten Controller zurückkehren.
