---
permalink: um-manage/remove-storage-arrays-from-group.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, remove, storage, arrays, group 
summary: Sie können ein oder mehrere verwaltete Speicher-Arrays aus einer Gruppe entfernen, wenn Sie sie nicht mehr aus einer bestimmten Speichergruppe verwalten möchten. 
---
= Entfernen Sie Speicher-Arrays aus der Gruppe
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein oder mehrere verwaltete Speicher-Arrays aus einer Gruppe entfernen, wenn Sie sie nicht mehr aus einer bestimmten Speichergruppe verwalten möchten.

.Über diese Aufgabe
Das Entfernen von Speicher-Arrays aus einer Gruppe hat keinerlei Auswirkungen auf das Speicher-Array oder seine Daten. Wenn das Storage Array von System Manager gemanagt wird, können Sie es weiterhin mit Ihrem Browser verwalten. Wenn ein Speicher-Array versehentlich aus einer Gruppe entfernt wird, kann es erneut hinzugefügt werden.

.Schritte
. Wählen Sie auf der Seite Verwalten die Option MENU:Gruppen verwalten[Speicher-Arrays aus Gruppe entfernen].
. Wählen Sie im Dropdown-Menü die Gruppe aus, die die zu entfernenden Speicher-Arrays enthält, und klicken Sie dann auf das Kontrollkästchen neben jedem Speicher-Array, das Sie aus der Gruppe entfernen möchten.
. Klicken Sie Auf *Entfernen*.

