---
permalink: um-manage/storage-array-groups.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, storage, array, groups 
summary: Sie können Ihre physische und virtualisierte Infrastruktur managen, indem Sie eine Reihe von Storage-Arrays gruppieren. Möglicherweise möchten Sie Storage-Arrays gruppieren, um die Ausführung von Überwachungs- oder Reporting-Aufgaben zu erleichtern. 
---
= Erfahren Sie mehr über Speicher-Array-Gruppen im SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Ihre physische und virtualisierte Infrastruktur managen, indem Sie eine Reihe von Storage-Arrays gruppieren. Möglicherweise möchten Sie Storage-Arrays gruppieren, um die Ausführung von Überwachungs- oder Reporting-Aufgaben zu erleichtern.



== Typen von Speicherarraygruppen

* *Alle Gruppen*
+
Die Gruppe Alle ist die Standardgruppe und umfasst alle Speicher-Arrays, die in Ihrem Unternehmen entdeckt wurden. Auf die Gruppe Alle kann über die Hauptansicht zugegriffen werden.

* *Vom Benutzer erstellte Gruppe*
+
Eine vom Benutzer erstellte Gruppe enthält die Speicher-Arrays, die Sie manuell auswählen, um dieser Gruppe hinzuzufügen. Auf von Benutzern erstellte Gruppen kann über die Hauptansicht zugegriffen werden.


