---
permalink: um-manage/upgrade-controller-firmware.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, upgrade, os, operating system 
summary: Aktualisieren Sie ein oder mehrere Storage-Arrays mit der neuesten Software und NVSRAM, um sicherzustellen, dass Sie über alle neuesten Funktionen und Fehlerbehebungen verfügen. Der NVSRAM-Controller ist eine Controller-Datei, die die Standardeinstellungen für die Controller angibt. 
---
= Upgrade von SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aktualisieren Sie ein oder mehrere Storage-Arrays mit der neuesten Software und NVSRAM, um sicherzustellen, dass Sie über alle neuesten Funktionen und Fehlerbehebungen verfügen. Der NVSRAM-Controller ist eine Controller-Datei, die die Standardeinstellungen für die Controller angibt.

.Bevor Sie beginnen
* Die neuesten Dateien des SANtricity Betriebssystems sind auf dem Host-System verfügbar, auf dem der SANtricity Web Services Proxy und Unified Manager ausgeführt werden.
* Sie wissen, ob Sie Ihr Software-Upgrade jetzt oder später aktivieren möchten.
+
Aus folgenden Gründen können Sie sich später aktivieren:

+
** *Tageszeit* -- die Aktivierung der Software kann eine lange Zeit dauern, so dass Sie möglicherweise warten möchten, bis I/O-Lasten leichter sind. Der Failover der Controller während der Aktivierung ist möglich, sodass die Performance bis zum Abschluss des Upgrades unter Umständen niedriger ist als üblich.
** *Art des Pakets* -- möglicherweise möchten Sie die neue Betriebssystemsoftware auf einem Speicher-Array testen, bevor Sie die Dateien auf anderen Speicher-Arrays aktualisieren.




++++

[NOTE]
====
Risiko eines Datenverlusts oder einer Beschädigung des Storage Arrays: Nehmen Sie während des Upgrades keine Änderungen am Storage Array vor. Halten Sie den Strom für das Speicher-Array aufrecht.

====
.Schritte
. Wenn Ihr Storage Array nur einen Controller oder einen Multipath-Treiber enthält, beenden Sie die I/O-Aktivitäten des Storage Arrays, um Applikationsfehler zu vermeiden. Wenn Ihr Storage Array über zwei Controller verfügt und Sie einen Multipath-Treiber installiert haben, müssen Sie die I/O-Aktivität nicht stoppen.
. Wählen Sie in der Hauptansicht *Verwalten* aus, und wählen Sie dann ein oder mehrere Speicher-Arrays aus, die Sie aktualisieren möchten.
. Wählen Sie MENU:Upgrade Center[Upgrade SANtricity OS Software].
+
Die Seite SANtricity OS-Software aktualisieren wird angezeigt.

. Laden Sie das neueste Software-Paket für SANtricity OS von der NetApp Support-Website auf Ihren lokalen Computer herunter.
+
.. Klicken Sie auf *Neue Datei zum Software-Repository hinzufügen*.
.. Klicken Sie auf den Link, um die neuesten *SANtricity OS Downloads* zu finden.
.. Klicken Sie auf den Link *Letzte Version herunterladen*.
.. Folgen Sie den restlichen Anweisungen, um die SANtricity OS-Datei und die NVSRAM-Datei auf Ihren lokalen Computer herunterzuladen.


+
[NOTE]
====
In Version 8.42 und höher ist digital signierte Firmware erforderlich. Wenn Sie versuchen, nicht signierte Firmware herunterzuladen, wird ein Fehler angezeigt und der Download wird abgebrochen.

====
. Wählen Sie die Betriebssystemsoftware und die NVSRAM-Datei aus, die Sie zum Aktualisieren der Controller verwenden möchten:
+
.. Wählen Sie aus der Dropdown-Liste *Select a SANtricity OS Software file* die Betriebssystemdatei aus, die Sie auf Ihren lokalen Rechner heruntergeladen haben.
+
Wenn mehrere Dateien verfügbar sind, werden die Dateien vom neuesten Datum bis zum ältesten Datum sortiert.

+
[NOTE]
====
Das Software-Repository enthält alle Softwaredateien, die dem Web Services Proxy zugeordnet sind. Wenn die Datei nicht angezeigt wird, die Sie verwenden möchten, klicken Sie auf den Link *Neue Datei zum Software-Repository hinzufügen*, um zu dem Speicherort zu navigieren, an dem sich die Betriebssystemdatei befindet, die Sie hinzufügen möchten.

====
.. Wählen Sie im Dropdown-Menü *Select an NVSRAM file* die gewünschte Controllerdatei aus.
+
Wenn es mehrere Dateien gibt, werden die Dateien vom neuesten Datum bis zum ältesten Datum sortiert.



. Überprüfen Sie in der Tabelle kompatibler Speicher-Arrays die Speicherarrays, die mit der ausgewählten Betriebssystemsoftware kompatibel sind, und wählen Sie dann die Arrays aus, die aktualisiert werden sollen.
+
** Die Speicherarrays, die Sie in der Ansicht Verwalten ausgewählt haben und mit der ausgewählten Firmware-Datei kompatibel sind, werden standardmäßig in der Tabelle kompatible Speicherarrays ausgewählt.
** Die Speicher-Arrays, die nicht mit der ausgewählten Firmware-Datei aktualisiert werden können, können in der kompatiblen Speicher-Array-Tabelle nicht wie im Status *inkompatibel* angegeben ausgewählt werden.


. *Optional:* um die Software-Datei auf die Speicher-Arrays zu übertragen, ohne sie zu aktivieren, wählen Sie das Kontrollkästchen *Betriebssystemsoftware auf die Speicher-Arrays übertragen, als bereitgestellt markieren und zu einem späteren Zeitpunkt aktivieren*.
. Klicken Sie Auf *Start*.
. Je nachdem, ob Sie jetzt oder später aktiviert haben, führen Sie einen der folgenden Schritte aus:
+
** Geben Sie *TRANSFER* ein, um zu bestätigen, dass Sie die vorgeschlagenen Betriebssystemversionen auf den Arrays übertragen möchten, die Sie für die Aktualisierung ausgewählt haben, und klicken Sie dann auf *Transfer*.
+
Um die übertragene Software zu aktivieren, wählen Sie MENU:Upgrade Center[Staged OS Software aktivieren].

** Geben Sie *UPGRADE* ein, um zu bestätigen, dass Sie die vorgeschlagenen Betriebssystemversionen auf den Arrays übertragen und aktivieren möchten, die Sie aktualisieren möchten, und klicken Sie dann auf *Upgrade*.
+
Das System überträgt die Softwaredatei auf jedes Speicherarray, das Sie für die Aktualisierung ausgewählt haben, und aktiviert diese Datei durch einen Neustart.



+
Während des Aktualisierungsvorgangs treten folgende Aktionen auf:

+
** Im Rahmen des Upgrades wird eine Integritätsprüfung vor dem Upgrade ausgeführt. Bei der Integritätsprüfung vor dem Upgrade werden alle Komponenten des Storage Arrays bewertet, um sicherzustellen, dass das Upgrade fortgesetzt werden kann.
** Wenn eine Integritätsprüfung für ein Speicherarray fehlschlägt, wird das Upgrade abgebrochen. Sie können auf die Ellipsen (...) klicken und *Protokoll speichern* wählen, um die Fehler zu überprüfen. Sie können auch den Fehler der Integritätsprüfung überschreiben und dann auf *Weiter* klicken, um mit dem Upgrade fortzufahren.
** Sie können den Upgrade-Vorgang nach der Integritätsprüfung vor dem Upgrade abbrechen.


. *Optional:* nach Abschluss des Upgrades sehen Sie eine Liste der für ein bestimmtes Speicherarray aktualisierten Versionen, indem Sie auf die Ellipsen (...) klicken und dann *Protokoll speichern* wählen.
+
Die Datei wird im Ordner Downloads für Ihren Browser mit dem Namen gespeichert `upgrade_log-<date>.json`.


