---
permalink: um-manage/why-would-i-change-this-percentage-um.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, percentage 
summary: 'Die reservierte Kapazität ist normalerweise 20 % des Basis-Volumes für asynchrone Spiegelungsvorgänge. In der Regel ist diese Kapazität ausreichend.' 
---
= Warum sollte ich diesen Prozentsatz ändern?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die reservierte Kapazität ist normalerweise 20 % des Basis-Volumes für asynchrone Spiegelungsvorgänge. In der Regel ist diese Kapazität ausreichend.

Die benötigte Kapazität ist abhängig von Häufigkeit und Größe der I/O-Schreibvorgänge auf dem Basis-Volume und wie lange Sie den Kopierdienst des Storage-Objekts verwenden möchten. Im Allgemeinen wählen Sie einen größeren Prozentsatz für die reservierte Kapazität aus, wenn eine oder beide Bedingungen vorhanden sind:

* Wenn sich der Kopierdienst eines bestimmten Storage-Objekts sehr lange Lebensdauer hat.
* Wenn sich ein großer Prozentsatz an Datenblöcken auf dem Basis-Volume aufgrund von hoher I/O-Aktivität ändert. Mithilfe von historischen Performance-Daten oder anderen Betriebssystem-Dienstprogrammen können Sie die typischen I/O-Aktivitäten für das Basis-Volume ermitteln.

