---
permalink: sm-settings/access-management-with-saml.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, access management, saml 
summary: 'Für die Zugriffsverwaltung können Administratoren die in das Array integrierten Funktionen der Security Assertion Markup Language (SAML) 2.0 verwenden.' 
---
= Zugriffsverwaltung mit SAML im SANtricity System Manager konfigurieren
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Für die Zugriffsverwaltung können Administratoren die in das Array integrierten Funktionen der Security Assertion Markup Language (SAML) 2.0 verwenden.



== Konfigurationsworkflow

Die SAML-Konfiguration funktioniert wie folgt:

. Ein Administrator meldet sich bei System Manager mit einem Benutzerprofil an, das die Berechtigungen für Sicherheitsadministrator enthält.
+
[NOTE]
====
Der `admin` Der Benutzer hat vollständigen Zugriff auf alle Funktionen in System Manager.

====
. Der Administrator wechselt zur Registerkarte *SAML* unter Zugriffsverwaltung.
. Ein Administrator konfiguriert die Kommunikation mit dem Identity Provider (IdP). Ein IdP ist ein externes System, mit dem Anmeldeinformationen von einem Benutzer angefordert werden und festgestellt wird, ob der Benutzer erfolgreich authentifiziert wurde. Zum Konfigurieren der Kommunikation mit dem Storage-Array lädt der Administrator die IdP-Metadatendatei aus dem IdP-System herunter und lädt die Datei anschließend mit System Manager zum Hochladen auf das Storage-Array ein.
. Ein Administrator stellt eine Vertrauensbeziehung zwischen dem Dienstanbieter und dem IdP her. Ein Dienstanbieter steuert die Benutzerautorisierung. In diesem Fall fungiert der Controller im Speicher-Array als Service Provider. Zum Konfigurieren der Kommunikation verwendet der Administrator System Manager zum Exportieren einer Service-Provider-Metadatendatei für jeden Controller. Aus dem IdP-System importiert der Administrator diese Metadatendateien in das IdP.
+
[NOTE]
====
Administratoren sollten außerdem sicherstellen, dass das IdP die Möglichkeit unterstützt, eine Name-ID bei der Authentifizierung zurückzugeben.

====
. Der Administrator ordnet die Rollen des Storage-Arrays den in IdP definierten Benutzerattributen zu. Dazu verwendet der Administrator System Manager zum Erstellen der Zuordnungen.
. Der Administrator testet die SSO-Anmeldung an der IdP-URL. Dieser Test stellt sicher, dass das Storage-Array und das IdP kommunizieren können.
+
[CAUTION]
====
Sobald SAML aktiviert ist, können Sie sie über die Benutzeroberfläche nicht deaktivieren oder die IdP-Einstellungen bearbeiten. Wenn Sie die SAML-Konfiguration deaktivieren oder bearbeiten müssen, wenden Sie sich an den technischen Support, um Hilfe zu erhalten.

====
. In System Manager aktiviert der Administrator SAML für das Storage-Array.
. Benutzer melden sich mit ihren SSO-Anmeldedaten am System an.




== Vereinfachtes

Bei der Verwendung von SAML zur Authentifizierung können Administratoren die folgenden Managementaufgaben ausführen:

* Neue Rollenzuordnungen ändern oder erstellen
* Exportieren Sie die Dateien von Dienstanbietern




== Zugriffsbeschränkungen

Wenn SAML aktiviert ist, können Benutzer Speicher für dieses Array nicht über Unified Manager oder die alte Storage Manager-Schnittstelle ermitteln oder managen.

Außerdem können die folgenden Clients nicht auf Services und Ressourcen des Speicherarrays zugreifen:

* Enterprise Management-Fenster (EMW)
* Software Developer Kits (SDK)-Clients
* In-Band-Clients
* Melden Sie sich mithilfe des standardmäßigen REST-API-Endpunkts an




=== Eingeschränkte Konnektivität bei aktivierter SAML-Funktion

Die folgenden Speicher-Array-Funktionen verfügen nur über eine begrenzte Konnektivität mit der JSON-Web-Token-Authentifizierung, wenn SAML aktiviert ist.

* Befehlszeilenschnittstelle (CLI)
* REST-API-Clients für die HTTP-Standardauthentifizierung

