---
permalink: sm-settings/change-local-user-passwords-settings.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, local, user, password, settings, 
summary: Sie können die erforderliche Mindestlänge für alle neuen oder aktualisierten lokalen Benutzerpasswörter im Speicher-Array festlegen. Sie können lokalen Benutzern auch ohne Eingabe eines Kennworts den Zugriff auf das Speicher-Array erlauben. 
---
= Ändern Sie die Einstellungen für das lokale Benutzerpasswort
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die erforderliche Mindestlänge für alle neuen oder aktualisierten lokalen Benutzerpasswörter im Speicher-Array festlegen. Sie können lokalen Benutzern auch ohne Eingabe eines Kennworts den Zugriff auf das Speicher-Array erlauben.

.Bevor Sie beginnen
Sie müssen als lokaler Administrator angemeldet sein, der Root-Admin-Berechtigungen enthält.

.Über diese Aufgabe
Beachten Sie die folgenden Richtlinien, wenn Sie die Mindestlänge für lokale Benutzerpasswörter festlegen:

* Die Einstellung von Änderungen wirkt sich nicht auf vorhandene lokale Benutzerpasswörter aus.
* Die Mindestlänge für lokale Benutzerpasswörter muss zwischen 0 und 30 Zeichen liegen.
* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Mindestlängeneinstellung erfüllen oder überschreiten.
* Legen Sie keine Mindestlänge für das Passwort fest, wenn lokale Benutzer ohne Eingabe eines Kennworts auf das Speicher-Array zugreifen möchten.


.Schritte
. Wählen Sie Menü:Einstellungen[Zugriffsverwaltung].
. Wählen Sie die Registerkarte * Lokale Benutzerrollen* aus.
. Wählen Sie die Schaltfläche *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld Einstellungen für das lokale Benutzerpasswort wird geöffnet.

. Führen Sie einen der folgenden Schritte aus:
+
** Um lokalen Benutzern den Zugriff auf das Speicher-Array zu ermöglichen, ohne ein Passwort einzugeben, deaktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens sein“.
** Um eine Mindestkennwortlänge für alle lokalen Benutzerpasswörter festzulegen, aktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens sein“ und verwenden Sie dann das Spinner-Feld, um die erforderliche Mindestlänge für alle lokalen Benutzerpasswörter festzulegen.
+
Neue lokale Benutzerpasswörter müssen die aktuelle Einstellung erfüllen oder überschreiten.



. Klicken Sie Auf *Speichern*.

