---
permalink: sm-settings/change-passwords.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, passwords, user, passwords, 
summary: Sie können die Benutzerpasswörter für jedes Benutzerprofil in Access Management ändern. 
---
= Passwörter im SANtricity System Manager ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Benutzerpasswörter für jedes Benutzerprofil in Access Management ändern.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, der Root-Admin-Berechtigungen enthält.
* Sie müssen das lokale Administratorkennwort kennen.


.Über diese Aufgabe
Beachten Sie bei der Auswahl eines Passworts die folgenden Richtlinien:

* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Einstellung für ein Mindestpasswort erfüllen oder überschreiten (unter „Einstellungen anzeigen/bearbeiten“).
* Bei Passwörtern wird die Groß-/Kleinschreibung berücksichtigt.
* Nachgestellte Leerzeichen werden nicht von Kennwörtern entfernt, wenn sie eingestellt sind. Achten Sie darauf, Leerzeichen einzugeben, wenn diese im Passwort enthalten waren.
* Um die Sicherheit zu erhöhen, verwenden Sie mindestens 15 alphanumerische Zeichen, und ändern Sie das Passwort häufig.


[NOTE]
====
Durch Ändern des Passworts in System Manager wird es auch in der Befehlszeilenschnittstelle (CLI) geändert. Außerdem führen Kennwortänderungen dazu, dass die aktive Sitzung des Benutzers beendet wird.

====
.Schritte
. Wählen Sie Menü:Einstellungen[Zugriffsverwaltung].
. Wählen Sie die Registerkarte * Lokale Benutzerrollen* aus.
. Wählen Sie einen Benutzer aus der Tabelle aus.
+
Die Schaltfläche Kennwort ändern steht zur Verfügung.

. Wählen Sie *Passwort Ändern*.
+
Das Dialogfeld Kennwort ändern wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestkennwortlänge festgelegt ist, können Sie das Kontrollkästchen aktivieren, damit der ausgewählte Benutzer ein Kennwort für den Zugriff auf das Speicher-Array eingeben muss. Anschließend können Sie das neue Passwort für den ausgewählten Benutzer eingeben.
. Geben Sie Ihr lokales Administratorpasswort ein und klicken Sie dann auf *Ändern*.


.Ergebnisse
Wenn der Benutzer derzeit angemeldet ist, wird die aktive Sitzung des Benutzers durch die Kennwortänderung beendet.
