---
permalink: sm-settings/change-default-host-type.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, change, default, host, type, 
summary: Verwenden Sie die Einstellung Standardbetriebssystem ändern, um den Standardhosttyp auf Speicherarray-Ebene zu ändern. Im Allgemeinen ändern Sie den Standard-Hosttyp, bevor Sie Hosts mit dem Speicher-Array verbinden oder wenn Sie zusätzliche Hosts verbinden. 
---
= Standard-Hosttyp im SANtricity System Manager ändern
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Verwenden Sie die Einstellung Standardbetriebssystem ändern, um den Standardhosttyp auf Speicherarray-Ebene zu ändern. Im Allgemeinen ändern Sie den Standard-Hosttyp, bevor Sie Hosts mit dem Speicher-Array verbinden oder wenn Sie zusätzliche Hosts verbinden.

.Über diese Aufgabe
Beachten Sie folgende Richtlinien:

* Wenn alle Hosts, die Sie eine Verbindung zum Storage Array herstellen möchten, dasselbe Betriebssystem (homogene Host-Umgebung) verwenden möchten, ändern Sie den Host-Typ entsprechend dem Betriebssystem.
* Falls Hosts mit verschiedenen Betriebssystemen vorhanden sind, für die eine Verbindung zum Storage Array (heterogene Host-Umgebung) geplant ist, ändern Sie den Host-Typ so, dass er mit der Mehrheit der Betriebssysteme der Hosts übereinstimmt.
+
Wenn Sie beispielsweise acht verschiedene Hosts mit dem Speicher-Array verbinden und sechs dieser Hosts ein Windows-Betriebssystem ausführen, müssen Sie Windows als Standardbetriebssystem auswählen.

* Wenn der Großteil der angeschlossenen Hosts eine Mischung verschiedener Betriebssysteme hat, ändern Sie den Hosttyp auf Werkseinstellung.
+
Wenn Sie beispielsweise acht verschiedene Hosts mit dem Storage-Array verbinden und zwei dieser Hosts ein Windows-Betriebssystem ausführen, werden drei unter einem VMware Betriebssystem ausgeführt. Und weitere drei führen ein Linux-Betriebssystem aus. Sie müssen als Standard-Host-Betriebssystem Factory Default auswählen.



.Schritte
. Wählen Sie Menü:Einstellungen[System].
. Blättern Sie nach unten zu *zusätzliche Einstellungen*, und klicken Sie dann auf *Standardbetriebssystemtyp ändern*.
. Wählen Sie den Host-Betriebssystem-Typ aus, den Sie als Standard verwenden möchten.
. Klicken Sie Auf *Ändern*.

