---
permalink: sm-settings/configure-login-banner.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, login, banner, 
summary: Sie können ein Login-Banner erstellen, das Benutzern angezeigt wird, bevor sie Sitzungen in SANtricity System Manager einrichten. Das Banner kann einen Hinweishinweisen und eine Einwilligungsmeldung enthalten. 
---
= Login-Banner im SANtricity System Manager konfigurieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Login-Banner erstellen, das Benutzern angezeigt wird, bevor sie Sitzungen in SANtricity System Manager einrichten. Das Banner kann einen Hinweishinweisen und eine Einwilligungsmeldung enthalten.

.Über diese Aufgabe
Wenn Sie ein Banner erstellen, wird es vor dem Anmeldebildschirm in einem Dialogfeld angezeigt.

.Schritte
. Wählen Sie Menü:Einstellungen[System].
. Wählen Sie im Abschnitt Allgemein die Option *Anmelde-Banner konfigurieren* aus.
+
Das Dialogfeld Anmelde-Banner konfigurieren wird geöffnet.

. Geben Sie den Text ein, der im Anmeldebanner angezeigt werden soll.
+
[NOTE]
====
Verwenden Sie keine HTML- oder andere Markup-Tags zum Formatieren.

====
. Klicken Sie Auf *Speichern*.


.Ergebnisse
Wenn sich Benutzer beim nächsten Mal bei System Manager anmelden, wird der Text in einem Dialogfeld geöffnet. Benutzer müssen auf *OK* klicken, um mit dem Anmeldebildschirm fortzufahren.
