---
permalink: sm-settings/configure-syslog-server-for-audit-logs.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, syslog, server, audit, logs, 
summary: Wenn Sie Auditprotokolle auf einem externen Syslog-Server archivieren möchten, können Sie die Kommunikation zwischen diesem Server und dem Speicher-Array konfigurieren. Nach der Verbindungsherstellung werden Audit-Protokolle automatisch auf dem Syslog-Server gespeichert. 
---
= Syslog-Server für Audit-Protokolle konfigurieren
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie Auditprotokolle auf einem externen Syslog-Server archivieren möchten, können Sie die Kommunikation zwischen diesem Server und dem Speicher-Array konfigurieren. Nach der Verbindungsherstellung werden Audit-Protokolle automatisch auf dem Syslog-Server gespeichert.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden die Zugriffsverwaltungsfunktionen nicht angezeigt.
* Die Syslog-Serveradresse, das Protokoll und die Portnummer müssen verfügbar sein. Bei der Serveradresse kann es sich um einen vollständig qualifizierten Domänennamen, eine IPv4-Adresse oder eine IPv6-Adresse handeln.
* Wenn Ihr Server ein sicheres Protokoll verwendet (z. B. TLS), muss auf Ihrem lokalen System ein Zertifikat für Zertifizierungsstellen (CA) verfügbar sein. CA-Zertifikate identifizieren Website-Eigentümer für sichere Verbindungen zwischen Servern und Clients.


.Schritte
. Wählen Sie Menü:Einstellungen[Zugriffsverwaltung].
. Wählen Sie auf der Registerkarte Audit Log die Option *Configure Syslog Servers* aus.
+
Das Dialogfeld Configure Syslog Servers wird geöffnet.

. Klicken Sie Auf *Hinzufügen*.
+
Das Dialogfeld Syslog Server hinzufügen wird geöffnet.

. Geben Sie Informationen für den Server ein, und klicken Sie dann auf *Hinzufügen*.
+
** *Server-Adresse* -- Geben Sie einen vollständig qualifizierten Domänennamen, eine IPv4-Adresse oder eine IPv6-Adresse ein.
** *Protokoll* -- Wählen Sie aus der Dropdown-Liste ein Protokoll aus (z. B. TLS, UDP oder TCP).
** *Zertifikat hochladen (optional)* -- Wenn Sie das TLS-Protokoll ausgewählt haben und noch kein signiertes CA-Zertifikat hochgeladen haben, klicken Sie auf *Durchsuchen*, um eine Zertifikatdatei hochzuladen. Audit-Protokolle werden nicht ohne vertrauenswürdiges Zertifikat auf einem Syslog-Server archiviert.
+
[NOTE]
====
Wenn das Zertifikat später ungültig wird, schlägt der TLS-Handshake fehl. Als Ergebnis wird eine Fehlermeldung in das Auditprotokoll geschrieben und Meldungen werden nicht mehr an den Syslog-Server gesendet. Um dieses Problem zu lösen, müssen Sie das Zertifikat auf dem Syslog-Server beheben und dann zum Menü:Einstellungen[Audit-Protokoll > Syslog-Server konfigurieren > Alle testen] wechseln.

====
** *Port* -- Geben Sie die Portnummer für den Syslog-Empfänger ein. Nachdem Sie auf *Hinzufügen* geklickt haben, wird das Dialogfeld Configure Syslog Servers geöffnet und der konfigurierte Syslog Server auf der Seite angezeigt.


. Um die Serververbindung mit dem Speicher-Array zu testen, wählen Sie *Alle testen*.


.Ergebnisse
Nach der Konfiguration werden alle neuen Audit-Protokolle an den Syslog-Server gesendet. Frühere Protokolle werden nicht übertragen.
