---
permalink: sm-settings/edit-user-names-for-snmp-traps.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, edit, user, settings, snmpv3, traps, 
summary: Sie können Benutzerdefinitionen für SNMPv3-Traps bearbeiten. 
---
= Benutzereinstellungen für SNMPv3-Traps im SANtricity System Manager bearbeiten
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Benutzerdefinitionen für SNMPv3-Traps bearbeiten.

.Bevor Sie beginnen
Für den SNMPv3-Trap muss ein Benutzer erstellt werden.

.Schritte
. Wählen Sie Menü:Einstellungen[Alarme].
. Wählen Sie die Registerkarte *SNMP* aus.
+
Die Trap-Ziele und Benutzernamen werden in der Tabelle angezeigt.

. Um eine Benutzerdefinition zu bearbeiten, wählen Sie den Benutzer in der Tabelle aus und klicken dann auf *Benutzer konfigurieren*.
. Klicken Sie im Dialogfeld auf *Einstellungen anzeigen/bearbeiten*.
. Bearbeiten Sie folgende Informationen:
+
** *Benutzername* -- Ändern Sie den Namen, der den Benutzer identifiziert, der bis zu 31 Zeichen lang sein kann.
** *Engine ID* -- Wählen Sie die Engine-ID aus, die zur Generierung von Authentifizierungs- und Verschlüsselungsschlüsseln für Nachrichten verwendet wird, und müssen in der Verwaltungsdomäne eindeutig sein. In den meisten Fällen sollten Sie *Lokal* wählen. Wenn Sie eine nicht-Standardkonfiguration haben, wählen Sie *Benutzerdefiniert* aus. Ein weiteres Feld wird angezeigt, in dem Sie die autoritative Engine-ID als Hexadezimalstring eingeben müssen, wobei eine gerade Anzahl von Zeichen zwischen 10 und 32 Zeichen lang ist.
** *Authentifizierungsdaten* -- Wählen Sie ein Authentifizierungsprotokoll, das die Identität der Benutzer sicherstellt. Geben Sie dann ein Authentifizierungspasswort ein, das erforderlich ist, wenn das Authentifizierungsprotokoll festgelegt oder geändert wird. Das Passwort muss zwischen 8 und 128 Zeichen lang sein.
** *Datenschutzhinweise* -- Wählen Sie ein Datenschutzprotokoll, das zur Verschlüsselung der Inhalte von Nachrichten verwendet wird. Geben Sie dann ein Datenschutzkennwort ein, das erforderlich ist, wenn das Datenschutzprotokoll festgelegt oder geändert wird. Das Passwort muss zwischen 8 und 128 Zeichen lang sein.




.Ergebnisse
Auf der Registerkarte SNMP der Seite Meldungen werden die aktualisierten Einstellungen angezeigt.
