---
permalink: sm-settings/permissions-for-mapped-roles.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, permissions, mapped, roles, 
summary: 'Die auf dem Storage-Array erzwungenen RBAC-Funktionen (rollenbasierte Zugriffssteuerung) umfassen vordefinierte Benutzerprofile, die mit einer oder mehreren zugewiesenen Rollen ausgestattet sind. Jede Rolle umfasst Berechtigungen für den Zugriff auf Aufgaben in SANtricity System Manager.' 
---
= Erfahren Sie mehr über Berechtigungen für zugeordnete Rollen im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die auf dem Storage-Array erzwungenen RBAC-Funktionen (rollenbasierte Zugriffssteuerung) umfassen vordefinierte Benutzerprofile, die mit einer oder mehreren zugewiesenen Rollen ausgestattet sind. Jede Rolle umfasst Berechtigungen für den Zugriff auf Aufgaben in SANtricity System Manager.

Auf Benutzerprofile und zugeordnete Rollen kann über das Menü:Einstellungen[Zugriffsmanagement > Lokale Benutzerrollen] in der Benutzeroberfläche eines System Managers zugegriffen werden.

Die Rollen ermöglichen Benutzern den Zugriff auf Aufgaben wie folgt:

* *Storage Admin* -- Vollzugriff auf die Speicherobjekte (z. B. Volumes und Disk Pools), aber kein Zugriff auf die Sicherheitskonfiguration.
* *Security Admin* -- Zugriff auf die Sicherheitskonfiguration in Access Management, Zertifikatverwaltung, Audit Log Management und die Möglichkeit, die alte Management-Schnittstelle (Symbol) ein- oder auszuschalten.
* *Support Admin* -- Zugriff auf alle Hardware-Ressourcen auf dem Speicher-Array, Ausfalldaten, MEL-Ereignisse und Controller-Firmware-Upgrades. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
* *Monitor* -- schreibgeschützter Zugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.


Wenn ein Benutzer über keine Berechtigungen für eine bestimmte Aufgabe verfügt, ist diese Aufgabe entweder ausgegraut oder wird nicht in der Benutzeroberfläche angezeigt.
