---
permalink: sm-settings/remove-directory-server.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, directory, server, 
summary: Um die Verbindung zwischen einem Verzeichnisserver und dem Speicher-Array zu unterbrechen, können Sie die Serverinformationen von der Seite Zugriffsverwaltung entfernen. Sie möchten diese Aufgabe möglicherweise ausführen, wenn Sie einen neuen Server konfiguriert haben und den alten dann entfernen möchten. 
---
= Verzeichnisserver im SANtricity System Manager entfernen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Verbindung zwischen einem Verzeichnisserver und dem Speicher-Array zu unterbrechen, können Sie die Serverinformationen von der Seite Zugriffsverwaltung entfernen. Sie möchten diese Aufgabe möglicherweise ausführen, wenn Sie einen neuen Server konfiguriert haben und den alten dann entfernen möchten.

.Bevor Sie beginnen
Sie müssen mit einem Benutzerprofil angemeldet sein, das Sicherheitsadministratorberechtigungen enthält. Andernfalls werden die Zugriffsverwaltungsfunktionen nicht angezeigt.

.Über diese Aufgabe
Nach Abschluss dieser Aufgabe werden alle aktiven Benutzersitzungen beendet. Nur Ihre aktuelle Benutzersitzung bleibt erhalten.

.Schritte
. Wählen Sie Menü:Einstellungen[Zugriffsverwaltung].
. Wählen Sie die Registerkarte *Directory Services* aus.
. Wählen Sie in der Liste den Verzeichnisserver aus, den Sie löschen möchten.
. Klicken Sie Auf *Entfernen*.
+
Das Dialogfeld Verzeichnisserver entfernen wird geöffnet.

. Typ `remove` Klicken Sie im Feld auf *Entfernen*.
+
Die Konfigurationseinstellungen des Verzeichnisservers, die Berechtigungseinstellungen und Rollenzuordnungen werden entfernt. Benutzer können sich nicht mehr mit Anmeldeinformationen von diesem Server anmelden.


