---
permalink: sm-settings/remove-community-name-for-snmp-traps.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, remove, communities, snmpv2c, traps, 
summary: Sie können einen Community-Namen für SNMPv2c-Traps entfernen. 
---
= Entfernen Sie Communities für SNMPv2c-Traps im SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Community-Namen für SNMPv2c-Traps entfernen.

.Schritte
. Wählen Sie Menü:Einstellungen[Alarme].
. Wählen Sie die Registerkarte *SNMP* aus.
+
Die Trap-Ziele und Community-Namen werden auf der Seite *Alerts* angezeigt.

. Wählen Sie * Communities Konfigurieren*.
+
Das Dialogfeld „Communities konfigurieren“ wird geöffnet.

. Wählen Sie den Community-Namen aus, den Sie löschen möchten, und klicken Sie auf das Symbol *Entfernen* (X) ganz rechts.
+
Wenn Trap-Ziele mit diesem Community-Namen verknüpft sind, werden im Dialogfeld Community entfernen bestätigen die betroffenen Trap-Zieladressen angezeigt.

. Bestätigen Sie den Vorgang, und klicken Sie dann auf *Entfernen*.


.Ergebnisse
Der Community-Name und das zugehörige Trap-Ziel werden von der Seite Alerts entfernt.
