---
permalink: sm-settings/what-do-i-need-to-know-about-mapping-storage-array-roles.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, mapping, roles, 
summary: Bevor Sie Gruppen zu Rollen zuordnen, lesen Sie die folgenden Richtlinien durch. 
---
= Was muss ich über die Zuordnung von Speicher-Array-Rollen wissen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie Gruppen zu Rollen zuordnen, lesen Sie die folgenden Richtlinien durch.

Die integrierten RBAC-Funktionen (rollenbasierte Zugriffssteuerung) des Storage-Arrays umfassen folgende Rollen:

* *Storage Admin* -- Vollzugriff auf die Speicherobjekte (z. B. Volumes und Disk Pools), aber kein Zugriff auf die Sicherheitskonfiguration.
* *Security Admin* -- Zugriff auf die Sicherheitskonfiguration in Access Management, Zertifikatverwaltung, Audit Log Management und die Möglichkeit, die alte Management-Schnittstelle (Symbol) ein- oder auszuschalten.
* *Support Admin* -- Zugriff auf alle Hardware-Ressourcen auf dem Speicher-Array, Ausfalldaten, MEL-Ereignisse und Controller-Firmware-Upgrades. Kein Zugriff auf Speicherobjekte oder die Sicherheitskonfiguration.
* *Monitor* -- schreibgeschützter Zugriff auf alle Speicherobjekte, aber kein Zugriff auf die Sicherheitskonfiguration.




== Verzeichnisdienste

Wenn Sie einen LDAP-Server (Lightweight Directory Access Protocol) und Verzeichnisdienste verwenden, stellen Sie sicher, dass:

* Ein Administrator hat im Verzeichnisdienst Benutzergruppen definiert.
* Sie kennen die Gruppen-Domain-Namen für die LDAP-Benutzergruppen. Reguläre Ausdrücke werden unterstützt. Diese speziellen regulären Ausdruckszeichen müssen mit einem umgekehrten Schrägstrich entgangen werden (`\`) Wenn sie nicht Teil eines regulären Ausdrucksmusters sind:
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* Die Überwachungsrolle ist für alle Benutzer, einschließlich des Administrators, erforderlich. Der System Manager funktioniert ohne die vorhandene Monitorrolle nicht ordnungsgemäß für alle Benutzer.




== SAML

Wenn Sie die im Speicher-Array integrierten SAML-Funktionen (Security Assertion Markup Language) verwenden, stellen Sie sicher, dass:

* Ein IdP-Administrator (Identity Provider) hat im IdP-System Benutzerattribute und Gruppenmitgliedschaften konfiguriert.
* Sie kennen die Namen der Gruppenmitgliedschaft.
* Sie kennen den Attributwert für die zu zugeordnete Gruppe. Reguläre Ausdrücke werden unterstützt. Diese speziellen regulären Ausdruckszeichen müssen mit einem umgekehrten Schrägstrich entgangen werden (`\`) Wenn sie nicht Teil eines regulären Ausdrucksmusters sind:
+
[listing]
----
\.[]{}()<>*+-=!?^$|
----
* Die Überwachungsrolle ist für alle Benutzer, einschließlich des Administrators, erforderlich. Der System Manager funktioniert ohne die vorhandene Monitorrolle nicht ordnungsgemäß für alle Benutzer.

