---
permalink: sm-settings/what-is-cache-flushing.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, cache, flushing, 
summary: Wenn die Menge der nicht geschriebenen Daten im Cache eine bestimmte Ebene erreicht, schreibt der Controller regelmäßig Cache-Daten auf ein Laufwerk. Dieser Schreibvorgang wird als Spülung bezeichnet. 
---
= Was wird Cachespülung?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die Menge der nicht geschriebenen Daten im Cache eine bestimmte Ebene erreicht, schreibt der Controller regelmäßig Cache-Daten auf ein Laufwerk. Dieser Schreibvorgang wird als „Spülen“ bezeichnet.

Der Controller verwendet zwei Algorithmen für das Spülen von Cache: Bedarfsbasiert und altersbasiert. Der Controller verwendet einen bedarfsorientierten Algorithmus, bis die Menge der im Cache gespeicherten Daten unter den Schwellenwert für die Cache-Spülung fällt. Standardmäßig beginnt ein Flush, wenn 80 Prozent des Caches verwendet werden.

In System Manager können Sie den Schwellenwert für „`Start Demand Cache Flush`“ festlegen, um den in Ihrer Umgebung verwendeten I/O-Typ optimal zu unterstützen. In einer Umgebung, in der hauptsächlich Schreibvorgänge ausgeführt werden, sollten Sie den „`Start Demand Cache Flush`“-Prozentsatz hoch einstellen, um die Wahrscheinlichkeit zu erhöhen, dass neue Schreibanforderungen durch den Cache verarbeitet werden können, ohne auf die Festplatte gehen zu müssen. Eine Einstellung mit hohem Prozentsatz begrenzt die Anzahl der Cache-Flushes, so dass mehr Daten im Cache verbleiben, was die Wahrscheinlichkeit von mehr Cache-Treffern erhöht.

In einer Umgebung, in der der I/O unregelmäßig ist (bei sprunghaften Datenanbrüchen), können Sie geringe Cache-Schreibvorgänge verwenden, sodass das System häufig zwischen Datenstoßweisen den Cache-Speicher stürzt. In einer vielfältigen I/O-Umgebung, die eine Vielzahl von Lasten verarbeitet, oder wenn die Lasttypen unbekannt sind, setzen Sie den Schwellenwert auf 50 Prozent als guter Mittelweg. Wenn Sie einen Startprozentsatz unter 80 Prozent wählen, können Sie eine verminderte Leistung feststellen, da die Daten für einen Host-Lesevorgang möglicherweise nicht verfügbar sind. Wird ein niedrigerer Prozentsatz ausgewählt, erhöht sich auch die Anzahl der Festplattenschreibvorgänge, die zur Aufrechterhaltung des Cache-Levels erforderlich sind, was den System-Overhead erhöht.

Der altersbasierte Algorithmus legt fest, wie lange die Schreibvorgänge im Cache verbleiben können, bevor sie auf die Festplatten gespeichert werden können. Die Controller verwenden den altersbasierten Algorithmus, bis der Schwellenwert für den Cache-Spülvorgang erreicht ist. Der Standardwert beträgt 10 Sekunden, dieser Zeitraum wird jedoch nur in Zeiten der Inaktivität gezählt. Sie können den Spülzeitpunkt in System Manager nicht ändern. Stattdessen müssen Sie den Befehl *Set Storage Array* in der Befehlszeilenschnittstelle (CLI) verwenden.

[CAUTION]
====
*Möglicher Datenverlust* -- Wenn Sie die *Write Caching ohne Batterien* Option aktivieren und keine universelle Stromversorgung zum Schutz haben, könnten Sie Daten verlieren. Darüber hinaus könnten Sie Daten verlieren, wenn Sie keine Controller-Batterien haben und Sie die Option *Write Caching ohne Batterien* aktivieren.

====