---
permalink: sm-settings/what-is-host-connectivity-reporting.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, host, connectivity, reporting, 
summary: Wenn die Berichterstellung für die Host-Konnektivität aktiviert ist, überwacht das Storage-Array fortlaufend die Verbindung zwischen den Controllern und den konfigurierten Hosts und warnt anschließend, wenn die Verbindung unterbrochen wird. 
---
= Was ist die Berichterstellung über Host-Konnektivität?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn die Berichterstellung für die Host-Konnektivität aktiviert ist, überwacht das Storage-Array fortlaufend die Verbindung zwischen den Controllern und den konfigurierten Hosts und warnt anschließend, wenn die Verbindung unterbrochen wird.

Es kann zu Unterbrechungen der Verbindung kommen, wenn ein lockeres, beschädigtes oder fehlendes Kabel oder ein anderes Problem mit dem Host vorliegt. In diesen Situationen öffnet das System möglicherweise eine Recovery Guru Nachricht:

* *Host Redundancy Lost* -- wird geöffnet, wenn einer der Controller nicht mit dem Host kommunizieren kann.
* *Host-Typ falsch* -- öffnet sich, wenn der Host-Typ auf dem Speicher-Array falsch angegeben ist, was zu Failover-Problemen führen kann.


Möglicherweise möchten Sie die Berichterstellung für die Host-Konnektivität deaktivieren, wenn das Neubooten eines Controllers länger dauern kann als das Verbindungs-Timeout. Wenn Sie diese Funktion deaktivieren, werden Recovery Gurus-Nachrichten unterdrückt.

[NOTE]
====
Durch das Deaktivieren der Berichterstellung für Hostkonnektivität wird auch der automatische Lastausgleich deaktiviert, der die Nutzung von Controller-Ressourcen überwacht und ausgeglichen. Wenn Sie jedoch die Berichterstellung für Hostkonnektivität erneut aktivieren, wird die automatische Lastausgleichfunktion nicht automatisch wieder aktiviert.

====