---
permalink: sm-settings/what-do-i-need-to-know-before-unlocking-secure-drives.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, unlocking, secure, drives, 
summary: Um die Daten von einem sicheren Laufwerk zu entsperren, müssen Sie seinen Sicherheitsschlüssel importieren. 
---
= Was muss ich wissen, bevor sichere Laufwerke entsperrt werden?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um die Daten von einem sicheren Laufwerk zu entsperren, müssen Sie seinen Sicherheitsschlüssel importieren.

Beachten Sie vor dem Entsperren von sicheren Laufwerken die folgenden Richtlinien:

* Das Speicherarray muss bereits einen Sicherheitsschlüssel haben. Die migrierten Laufwerke werden erneut auf das Ziel-Storage-Array übertragen.
* Bei den zu migrierenden Laufwerken müssen Sie die Sicherheitsschlüsselkennung und den Passphrase kennen, der der Sicherheitsschlüsseldatei entspricht.
* Die Sicherheitsschlüsseldatei muss auf dem Management-Client verfügbar sein (das System mit einem Browser, der zum Zugriff auf System Manager verwendet wird).
* Wenn Sie ein gesperrtes NVMe-Laufwerk zurücksetzen, müssen Sie die Sicherheits-ID des Laufwerks eingeben. Um die Sicherheits-ID zu finden, müssen Sie das Laufwerk physisch entfernen und die PSID-Zeichenfolge (maximal 32 Zeichen) auf dem Laufwerketikett suchen. Stellen Sie sicher, dass das Laufwerk neu installiert ist, bevor Sie den Vorgang starten.

