---
permalink: sm-settings/which-external-management-tools-may-be-affected-by-this-change.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, external, management, tools, 
summary: Wenn Sie bestimmte Änderungen in System Manager vornehmen, z. B. das Wechseln der Managementoberfläche oder die Verwendung von SAML für eine Authentifizierungsmethode, sind einige externe Tools und Funktionen möglicherweise von der Verwendung eingeschränkt. 
---
= Welche externen Verwaltungstools können von dieser Änderung betroffen sein?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie bestimmte Änderungen in SANtricity System Manager vornehmen, wie z. B. das Wechseln der Managementoberfläche oder die Verwendung von SAML für eine Authentifizierungsmethode, sind die Verwendung einiger externer Tools und Funktionen möglicherweise eingeschränkt.



== Managementoberfläche

Tools, die direkt mit der älteren Managementoberfläche (Symbol), z. B. SANtricity SMI-S Provider oder OnCommand Insight (OCI), kommunizieren, funktionieren nur, wenn die Einstellung für die ältere Managementoberfläche aktiviert ist. Darüber hinaus können Sie keine alten CLI-Befehle verwenden oder Spiegelungsvorgänge durchführen, wenn diese Einstellung deaktiviert ist.

Weitere Informationen erhalten Sie vom technischen Support.



== SAML-Authentifizierung

Wenn SAML aktiviert ist, können die folgenden Clients nicht auf Storage-Array-Services und -Ressourcen zugreifen:

* Enterprise Management-Fenster (EMW)
* Befehlszeilenschnittstelle (CLI)
* Software Developer Kits (SDK)-Clients
* In-Band-Clients
* REST-API-Clients für die HTTP-Standardauthentifizierung
* Melden Sie sich mithilfe des standardmäßigen REST-API-Endpunkts an


Weitere Informationen erhalten Sie vom technischen Support.
