---
permalink: sm-settings/which-registration-methods-are-automatically-supported-for-iscsi.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, registration, methods,  automatically, supported, iscsi, 
summary: 'Die iSCSI-Implementierung unterstützt entweder die iSCSI-Ermittlungsmethode (Internet Storage Name Service, iSNS) oder die Verwendung des Befehls Send Targets.' 
---
= Welche Registrierungsmethoden werden für iSCSI automatisch unterstützt?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die iSCSI-Implementierung unterstützt entweder die iSCSI-Ermittlungsmethode (Internet Storage Name Service, iSNS) oder die Verwendung des Befehls Send Targets.

Die iSNS-Methode ermöglicht die iSNS-Erkennung zwischen den Initiatoren (iSCSI-Hosts) und den Zielen (den Controllern). Sie registrieren den Zielcontroller, um dem iSNS-Server den iSCSI-qualifizierten Namen (IQN) und die Portinformationen des Controllers bereitzustellen.

Wenn Sie iSNS nicht konfigurieren, kann der iSCSI-Host den Befehl Ziele senden während einer iSCSI-Erkennungssitzung senden. Als Antwort gibt der Controller die Portinformationen zurück (z. B. Ziel-IQN, Port-IP-Adresse, Listening-Port und Ziel-Portgruppe). Diese Ermittlungsmethode ist nicht erforderlich, wenn Sie iSNS verwenden, da der Host-Initiator die Ziel-IPs vom iSNS-Server abrufen kann.
