---
permalink: sm-settings/why-are-timestamps-inconsistent-between-the-array-and-alerts.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, timestamps, inconsistent, array, alerts, 
summary: 'Wenn das Speicher-Array Warnungen sendet, ist es für die Zeitzone des Zielservers oder Hosts, der die Warnungen empfängt, nicht korrekt. Stattdessen verwendet das Speicher-Array die lokale Zeit (GMT), um den Zeitstempel zu erstellen, der für den Warnungsdatensatz verwendet wird. Aufgrund dessen sind möglicherweise Inkonsistenzen zwischen den Zeitstempel für das Storage-Array und dem Server oder Host, der eine Meldung empfängt, zu erkennen.' 
---
= Warum sind Zeitstempel zwischen dem Array und Warnungen uneinheitlich?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn das Speicher-Array Warnungen sendet, ist es für die Zeitzone des Zielservers oder Hosts, der die Warnungen empfängt, nicht korrekt. Stattdessen verwendet das Speicher-Array die lokale Zeit (GMT), um den Zeitstempel zu erstellen, der für den Warnungsdatensatz verwendet wird. Aufgrund dessen sind möglicherweise Inkonsistenzen zwischen den Zeitstempel für das Storage-Array und dem Server oder Host, der eine Meldung empfängt, zu erkennen.

Da das Speicherarray beim Senden von Warnungen nicht richtig für die Zeitzone ist, ist der Zeitstempel für die Warnungen GMT-relative, der einen Zeitzonenversatz von Null hat. Um einen Zeitstempel zu berechnen, der Ihrer lokalen Zeitzone angemessen ist, sollten Sie Ihren Stundenversatz von GMT bestimmen und diesen Wert dann von den Zeitstempel hinzufügen oder abziehen.

[NOTE]
====
Um dieses Problem zu vermeiden, konfigurieren Sie NTP (Network Time Protocol) auf Ihren Speicher-Array-Controllern. NTP stellt sicher, dass die Controller immer mit der richtigen Zeit synchronisiert werden.

====