---
permalink: sm-support/configure-autosupport-delivery-method.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, configure, autosupport, ASUP, delivery, method 
summary: Die AutoSupport-Funktion unterstützt die HTTPS- und SMTP-Protokolle für die Bereitstellung von Dispatches an den technischen Support. 
---
= Konfigurieren der AutoSupport-Bereitstellungsmethode
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die AutoSupport-Funktion unterstützt die HTTPS- und SMTP-Protokolle für die Bereitstellung von Dispatches an den technischen Support.

.Bevor Sie beginnen
* Die AutoSupport-Funktion muss aktiviert sein. Sie sehen, ob die Funktion auf der Seite AutoSupport aktiviert ist.
* Ein DNS-Server muss in Ihrem Netzwerk installiert und konfiguriert sein. Die DNS-Server-Adresse muss in System Manager konfiguriert sein (diese Aufgabe ist auf der Seite Hardware verfügbar).


.Über diese Aufgabe
Überprüfen Sie die verschiedenen Protokolle:

* *HTTPS* -- ermöglicht es Ihnen, sich direkt mit dem Ziel-Server des technischen Supports über HTTPS zu verbinden. Wenn Sie AutoSupport OnDemand oder Remote-Diagnose aktivieren möchten, muss die AutoSupport-Bereitstellungsmethode auf HTTPS gesetzt werden.
* *E-Mail* -- ermöglicht Ihnen, einen E-Mail-Server als Liefermethode für das Senden von AutoSupport-Entsendungen zu verwenden.


[NOTE]
====
*Unterschiede zwischen den Methoden HTTPS und Email*. Die E-Mail-Versandmethode, die SMTP verwendet, weist einige wichtige Unterschiede zur HTTPS-Bereitstellungsmethode auf. Erstens ist die Größe der Dispatches für die E-Mail-Methode auf 5 MB begrenzt, was bedeutet, dass einige ASUP Datensammlungen nicht versendet werden. Zweitens ist die AutoSupport OnDemand-Funktion nur für die HTTPS-Bereitstellungsmethode verfügbar.

====
.Schritte
. Wählen Sie MENU:Support[Support Center > AutoSupport].
. Wählen Sie *AutoSupport-Bereitstellungsmethode konfigurieren*.
+
Es wird ein Dialogfeld angezeigt, in dem die Versandmethoden aufgeführt sind.

. Wählen Sie die gewünschte Liefermethode aus, und wählen Sie dann die Parameter für diese Bereitstellungsmethode aus. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie HTTPS ausgewählt haben, wählen Sie einen der folgenden Bereitstellungsparameter aus:
+
*** *Direkt* -- dieser Lieferparameter ist die Standardauswahl. Wenn Sie diese Option wählen, können Sie mithilfe des HTTPS-Protokolls eine direkte Verbindung zum technischen Supportsystem des Ziels herstellen.
*** *Über Proxy Server* -- mit dieser Option können Sie die HTTP Proxy-Serverdetails angeben, die für die Verbindung mit dem technischen Zielunterstützungssystem erforderlich sind. Sie müssen die Host-Adresse und die Portnummer angeben. Sie müssen jedoch nur die Details zur Host-Authentifizierung (Benutzername und Passwort) eingeben, falls erforderlich.
*** *Über Proxy Auto-Configuration Script (PAC)* -- Geben Sie den Speicherort einer PAC-Skriptdatei (Proxy Auto-Configuration) an. Mit einer PAC-Datei kann das System automatisch den entsprechenden Proxyserver auswählen, um eine Verbindung mit dem technischen Zielunterstützungssystem herzustellen.


** Wenn Sie E-Mail ausgewählt haben, geben Sie die folgenden Informationen ein:
+
*** Die E-Mail-Server-Adresse als vollständig qualifizierter Domain-Name, IPv4-Adresse oder IPv6-Adresse.
*** Die E-Mail-Adresse, die im Feld „von“ der AutoSupport-Entsendmail angezeigt wird.
*** *Optional; wenn Sie einen Konfigurationstest durchführen möchten*: Die E-Mail-Adresse, an der eine Bestätigung gesendet wird, wenn das AutoSupport-System den Testversand erhält.
*** Wenn Sie Nachrichten verschlüsseln möchten, wählen Sie *SMTPS* oder *STARTTLS* für den Verschlüsselungstyp aus, und wählen Sie dann die Portnummer für verschlüsselte Nachrichten aus. Wählen Sie andernfalls * Keine*.
*** Geben Sie bei Bedarf einen Benutzernamen und ein Kennwort für die Authentifizierung mit dem ausgehenden Absender und dem E-Mail-Server ein.




. Wenn Sie eine Firewall haben, die die Bereitstellung dieser ASUP-Einsendungen blockiert, fügen Sie der Whitelist die folgende URL hinzu: `\https://support.netapp.com/put/AsupPut/`
. Klicken Sie auf *Testkonfiguration*, um die Verbindung zum Server des technischen Supports mit den angegebenen Lieferparametern zu testen. Wenn Sie die AutoSupport On-Demand-Funktion aktiviert haben, testet das System auch die Verbindung für die AutoSupport OnDemand-Entsendungsbereitstellung.
+
Wenn der Konfigurationstest fehlschlägt, überprüfen Sie Ihre Konfigurationseinstellungen, und führen Sie den Test erneut aus. Wenden Sie sich an den technischen Support, wenn der Test weiterhin fehlschlägt.

. Klicken Sie Auf *Speichern*.

