---
permalink: sm-support/faq-autosupport.html 
sidebar: sidebar 
keywords:  
summary: Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen. 
---
= AutoSupport FAQ für SANtricity System Manager
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Diese FAQ kann Ihnen helfen, wenn Sie nur nach einer schnellen Antwort auf eine Frage suchen.



== Welche Daten sammle ich?

Die AutoSupport-Funktion und die manuelle Support-Datenerfassung bieten Möglichkeiten zum Erfassen von Daten in einem Kunden-Support Bundle zur Remote-Fehlerbehebung und Problemanalyse durch den technischen Support.

Das Customer Support Bundle sammelt alle Arten von Informationen zum Storage Array in einer einzigen komprimierten Datei. Die erfassten Informationen umfassen physische Konfiguration, logische Konfiguration, Versionsinformationen, Ereignisse, Log-Dateien, Und Performance-Daten. Die Informationen werden nur vom technischen Support verwendet, um Probleme mit dem Storage-Array zu lösen.



== Was zeigt mir unlesbare Sektoren Daten?

Sie können detaillierte Daten über unlesbare Sektoren anzeigen, die auf den Laufwerken in Ihrem Speicher-Array erkannt wurden.

Das unlesbare Sektoren-Log zeigt zuerst den zuletzt unlesbaren Sektor an. Das Protokoll enthält die folgenden Informationen zu den Volumes, die die unlesbaren Sektoren enthalten. Die Felder sind sortischbar.

[cols="25h,~"]
|===
| Feld | Beschreibung 


 a| 
Betroffenes Volume
 a| 
Zeigt die Beschriftung des Volumens an. Wenn ein fehlendes Volume unlesbare Sektoren enthält, wird für das fehlende Volume die World Wide Identifier angezeigt.



 a| 
Logical Unit Number (LUN)
 a| 
Zeigt die LUN für das Volume. Wenn auf dem Volume keine LUN vorhanden ist, wird im Dialogfeld „NA“ angezeigt.



 a| 
Zugewiesen Zu
 a| 
Zeigt die Hosts oder Host-Cluster, die Zugriff auf das Volume haben. Wenn ein Host, Host-Cluster oder sogar ein Standardcluster auf das Volume nicht zugreifen kann, wird im Dialogfeld „NA“ angezeigt.

|===
Um weitere Informationen zu den unlesbaren Sektoren zu erhalten, klicken Sie auf das Pluszeichen (+) neben einem Volume.

[cols="25h,~"]
|===
| Feld | Beschreibung 


 a| 
Datum/Uhrzeit
 a| 
Zeigt das Datum und die Uhrzeit an, zu der der unlesbare Sektor erkannt wurde.



 a| 
Logische Block-Adresse Des Volume
 a| 
Zeigt die logische Blockadresse (LBA) des Volumes an.



 a| 
Position Des Laufwerks
 a| 
Zeigt das Festplatten-Shelf, die Schublade (wenn Ihr Festplatten-Shelf Schubladen aufweist) und den Auflageort des Laufwerks an.



 a| 
Logische Blockadresse Des Laufwerks
 a| 
Zeigt die LBA des Laufwerks an.



 a| 
Fehlertyp
 a| 
Zeigt einen der folgenden Fehlertypen an:

* *Physical* -- Ein Fehler beim physischen Medium.
* *Logisch* -- Ein Lesefehler an anderer Stelle im Stripe, der unlesbare Daten verursacht. Zum Beispiel ein unlesbarer Sektor aufgrund von Medienfehlern an anderer Stelle im Volumen.
* * Inkonsistente* -- inkonsistente Redundanzdaten.
* *Data Assurance* -- Ein Data Assurance-Fehler.


|===


== Was ist ein Gesundheitsbild?

Ein Systemzustand-Image ist ein Rohdaten-Dump des Prozessorspeichers des Controllers, mit dem der technische Support ein Problem mit einem Controller diagnostizieren kann.

Die Firmware generiert automatisch ein Systemzustand-Image, wenn bestimmte Fehler erkannt werden. Bei bestimmten Fehlerbehebungsszenarios kann der technische Support anfordern, dass Sie die Datei für das Systemzustand abrufen und an sie senden.



== Was tun die AutoSupport-Funktionen?

Die AutoSupport Funktion besteht aus drei separaten Funktionen, die separat aktiviert werden können.

* *Basic AutoSupport* -- ermöglicht Ihrem Speicherarray die automatische Erfassung und Übermittlung von Daten an den technischen Support.
* *AutoSupport OnDemand* -- ermöglicht technischen Support, bei Bedarf eine erneute Übertragung eines früheren AutoSupport Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob es noch ausstehende Neuübertragungsanfragen gibt und entsprechend darauf reagiert.
* *Ferndiagnose* -- ermöglicht technischen Support, bei Bedarf einen neuen, aktuellen AutoSupport-Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage-Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob ausstehende neue Anfragen zu bestehen und entsprechend darauf zu reagieren.




== Welche Datentypen werden über die AutoSupport Funktion erfasst?

Die AutoSupport-Funktion enthält drei standardmäßige Entsendungstypen: Ereignispatches, geplante Dispatches sowie On-Demand- und Remote-Diagnose-Patches.

Die AutoSupport-Daten enthalten keine Benutzerdaten.

* *Event-Entsendungen*
+
Wenn Ereignisse auf dem System auftreten, die über proaktive Benachrichtigungen an den technischen Support verfügen, sendet die AutoSupport Funktion automatisch einen Event-ausgelösten Dispatch.

+
** Wird gesendet, wenn ein Support-Ereignis auf dem verwalteten Speicher-Array auftritt.
** In diesem Service wird eine umfassende Übersicht über die Ereignisse zum Zeitpunkt des Ereignisses des Storage-Arrays erstellt.


* *Geplante Entsendungen*
+
Die AutoSupport-Funktion sendet automatisch mehrere Entsendungen nach einem regelmäßigen Zeitplan.

+
** *Tägliche Dispatches* -- wird in einem vom Benutzer konfigurierbaren Zeitintervall einmal täglich gesendet. Enthält die aktuellen Systemereignisprotokolle und Performance-Daten.
** *Wöchentlich Dispatches* -- wird einmal wöchentlich in einem vom Benutzer konfigurierbaren Zeitintervall und Tag gesendet. Einschließlich Konfigurations- und Systemstatus-Informationen.


* *AutoSupport OnDemand und Remote Diagnostics Dispatches*
+
** *AutoSupport OnDemand* -- ermöglicht technischen Support, bei Bedarf eine erneute Übertragung eines früheren AutoSupport Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob es noch ausstehende Neuübertragungsanfragen gibt und entsprechend darauf reagiert.
** *Ferndiagnose* -- ermöglicht technischen Support, bei Bedarf einen neuen, aktuellen AutoSupport-Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage-Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob ausstehende neue Anfragen zu bestehen und entsprechend darauf zu reagieren.






== Wie konfiguriere ich die Bereitstellungsmethode für die AutoSupport-Funktion?

Die AutoSupport-Funktion unterstützt die Protokolle HTTPS und SMTP zur Bereitstellung von AutoSupport-Dispatches an den technischen Support.

.Bevor Sie beginnen
* Die AutoSupport-Funktion muss aktiviert sein. Sie sehen, ob die Funktion auf der Seite AutoSupport aktiviert ist.
* Ein DNS-Server muss in Ihrem Netzwerk installiert und konfiguriert sein. Die DNS-Server-Adresse muss in System Manager konfiguriert sein (diese Aufgabe ist auf der Seite Hardware verfügbar).


.Über diese Aufgabe
Überprüfen Sie die verschiedenen Protokolle:

* *HTTPS* -- ermöglicht es Ihnen, sich direkt mit dem Ziel-Server des technischen Supports über HTTPS zu verbinden. Wenn Sie AutoSupport OnDemand oder Remote-Diagnose aktivieren möchten, muss die AutoSupport-Bereitstellungsmethode auf HTTPS gesetzt werden.
* *E-Mail* -- ermöglicht Ihnen, einen E-Mail-Server als Liefermethode für das Senden von AutoSupport-Entsendungen zu verwenden.


[NOTE]
====
*Unterschiede zwischen den Methoden HTTPS und Email*. Die E-Mail-Versandmethode, die SMTP verwendet, weist einige wichtige Unterschiede zur HTTPS-Bereitstellungsmethode auf. Erstens ist die Größe der Dispatches für die E-Mail-Methode auf 5 MB begrenzt, was bedeutet, dass einige ASUP Datensammlungen nicht versendet werden. Zweitens ist die AutoSupport OnDemand-Funktion nur für die HTTPS-Bereitstellungsmethode verfügbar.

====
.Schritte
. Wählen Sie MENU:Support[Support Center > AutoSupport].
. Wählen Sie *AutoSupport-Bereitstellungsmethode konfigurieren*.
+
Es wird ein Dialogfeld angezeigt, in dem die Versandmethoden aufgeführt sind.

. Wählen Sie die gewünschte Liefermethode aus, und wählen Sie dann die Parameter für diese Bereitstellungsmethode aus. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie HTTPS ausgewählt haben, wählen Sie einen der folgenden Bereitstellungsparameter aus:
+
*** *Direkt* -- dieser Lieferparameter ist die Standardauswahl. Wenn Sie diese Option wählen, können Sie mithilfe des HTTPS-Protokolls eine direkte Verbindung zum technischen Supportsystem des Ziels herstellen.
*** *Über Proxy Server* -- mit dieser Option können Sie die HTTP Proxy-Serverdetails angeben, die für die Verbindung mit dem technischen Zielunterstützungssystem erforderlich sind. Sie müssen die Host-Adresse und die Portnummer angeben. Sie müssen jedoch nur die Details zur Host-Authentifizierung (Benutzername und Passwort) eingeben, falls erforderlich.
*** *Über Proxy Auto-Configuration Script (PAC)* -- Geben Sie den Speicherort einer PAC-Skriptdatei (Proxy Auto-Configuration) an. Mit einer PAC-Datei kann das System automatisch den entsprechenden Proxyserver auswählen, um eine Verbindung mit dem technischen Zielunterstützungssystem herzustellen.


** Wenn Sie E-Mail ausgewählt haben, geben Sie die folgenden Informationen ein:
+
*** Die E-Mail-Server-Adresse als vollständig qualifizierter Domain-Name, IPv4-Adresse oder IPv6-Adresse.
*** Die E-Mail-Adresse, die im Feld „von“ der AutoSupport-Entsendmail angezeigt wird.
*** *Optional; wenn Sie einen Konfigurationstest durchführen möchten.* die E-Mail-Adresse, an die eine Bestätigung gesendet wird, wenn das AutoSupport-System den Testversand erhält.
*** Wenn Sie Nachrichten verschlüsseln möchten, wählen Sie *SMTPS* oder *STARTTLS* für den Verschlüsselungstyp aus, und wählen Sie dann die Portnummer für verschlüsselte Nachrichten aus. Wählen Sie andernfalls * Keine*.
*** Geben Sie bei Bedarf einen Benutzernamen und ein Kennwort für die Authentifizierung mit dem ausgehenden Absender und dem E-Mail-Server ein.




. Klicken Sie auf *Testkonfiguration*, um die Verbindung zum Server des technischen Supports mit den angegebenen Lieferparametern zu testen. Wenn Sie die AutoSupport On-Demand-Funktion aktiviert haben, testet das System auch die Verbindung für die AutoSupport OnDemand-Entsendungsbereitstellung.
+
Wenn der Konfigurationstest fehlschlägt, überprüfen Sie Ihre Konfigurationseinstellungen, und führen Sie den Test erneut aus. Wenden Sie sich an den technischen Support, wenn der Test weiterhin fehlschlägt.

. Klicken Sie Auf *Speichern*.




== Was sind Konfigurationsdaten?

Wenn Sie Konfigurationsdaten erfassen auswählen, speichert das System den aktuellen Status der RAID-Konfigurationsdatenbank.

Die RAID-Konfigurationsdatenbank umfasst alle Daten für Volume-Gruppen und Festplatten-Pools auf dem Controller. Die Funktion Konfigurationsdaten erfassen speichert die gleichen Informationen wie der CLI-Befehl für `save storageArray dbmDatabase`.



== Was muss ich vor einem Upgrade der SANtricity OS Software beachten?

Bevor Sie die Software und Firmware des Controllers aktualisieren, sollten Sie diese Elemente beachten.

* Sie haben das Dokument und das gelesen `readme.txt` Datei und haben festgestellt, dass Sie das Upgrade durchführen möchten.
* Sie wissen, ob Sie Ihre IOM-Firmware aktualisieren möchten.
+
In der Regel sollten Sie alle Komponenten gleichzeitig aktualisieren. Sie können jedoch entscheiden, die IOM-Firmware nicht zu aktualisieren, wenn Sie sie nicht als Teil des Upgrades der SANtricity OS Controller Software aktualisieren möchten oder wenn Sie vom technischen Support aufgefordert wurden, Ihre IOM-Firmware herunterzustufen (Sie können nur die Firmware über die Befehlszeilenschnittstelle herunterstufen).

* Sie wissen, ob Sie die NVSRAM-Controller-Datei aktualisieren möchten.
+
In der Regel sollten Sie alle Komponenten gleichzeitig aktualisieren. Sie entscheiden sich jedoch möglicherweise nicht, die NVSRAM-Controller-Datei zu aktualisieren, wenn Ihre Datei entweder gepatcht wurde oder eine benutzerdefinierte Version ist und Sie sie nicht überschreiben möchten.

* Sie wissen, ob Sie jetzt oder später aktivieren möchten.
+
Gründe für eine spätere Aktivierung sind u. a.:

+
** *Tageszeit* -- die Aktivierung der Software und Firmware kann eine lange Zeit dauern, so dass Sie möglicherweise warten möchten, bis I/O-Lasten leichter sind. Der Controller-Failover während der Aktivierung, sodass die Performance möglicherweise niedriger ist als üblich, bis das Upgrade abgeschlossen ist.
** *Paketyp* -- möglicherweise möchten Sie die neue Software und Firmware auf einem Speicher-Array testen, bevor Sie die Dateien auf anderen Speicher-Arrays aktualisieren.




Diese Komponenten sind Bestandteil des Upgrades der SANtricity OS Controller Software:

* *Management Software* -- System Manager ist die Software, die das Speicher-Array verwaltet.
* *Controller-Firmware* -- Controller-Firmware verwaltet den I/O zwischen Hosts und Volumes.
* *Controller NVSRAM* -- Controller NVSRAM ist eine Controller-Datei, die die Standardeinstellungen für die Controller angibt.
* *IOM-Firmware* -- die I/O-Modul-Firmware (IOM) verwaltet die Verbindung zwischen einem Controller und einem Festplatten-Shelf. Es überwacht auch den Status der Komponenten.
* *Supervisor Software* -- Supervisor Software ist die virtuelle Maschine auf einem Controller, in dem die Software ausgeführt wird.


Im Rahmen des Upgrades muss möglicherweise auch der Multipath-/Failover-Treiber und/oder der HBA-Treiber des Hosts aktualisiert werden, damit der Host mit den Controllern korrekt interagieren kann.

[NOTE]
====
Informationen zum ermitteln, ob dies der Fall ist, finden Sie im https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].

====
Wenn Ihr Storage-Array nur einen Controller enthält oder kein Multipath-Treiber installiert ist, beenden Sie die I/O-Aktivität des Storage-Arrays, um Applikationsfehler zu vermeiden. Wenn Ihr Storage Array über zwei Controller verfügt und Sie einen Multipath-Treiber installiert haben, müssen Sie die I/O-Aktivität nicht stoppen.


CAUTION: Nehmen Sie während des Upgrades keine Änderungen am Storage Array vor.



== Was muss ich wissen, bevor ich die automatische EAM-Synchronisierung unterhalte?

Das Aussetzung der automatischen Synchronisierung von IOM verhindert, dass die IOM-Firmware beim nächsten Upgrade einer SANtricity OS-Controller-Software aktualisiert wird.

Normalerweise werden Controller-Software und IOM-Firmware als Bundle aktualisiert. Sie können die automatische EAM-Synchronisierung unterbrechen, wenn Sie über einen speziellen Build der IOM-Firmware verfügen, den Sie in Ihrem Gehäuse erhalten möchten. Andernfalls werden Sie beim nächsten Controller-Software-Upgrade auf die IOM-Firmware, die mit der Controller-Software gebündelt ist, zurückgesetzt.



== Warum läuft mein Firmware-Upgrade so langsam voran?

Der Fortschritt des Firmware-Upgrades hängt von der Gesamtlast des Systems ab.

Sollte während eines Online-Upgrades der Laufwerk-Firmware ein Volume-Transfer während des schnellen Rekonstruktionsvorgangs durchgeführt werden, initiiert das System eine vollständige Rekonstruktion für das übertragene Volume. Dieser Vorgang kann sehr viel Zeit in Anspruch nehmen. Die tatsächliche komplette Rekonstruktionszeit hängt von mehreren Faktoren ab, einschließlich der Menge der I/O-Aktivitäten während des Rekonstruktionsvorgangs, der Anzahl der Laufwerke in der Volume-Gruppe, der Einstellung für die Priorität bei der Wiederherstellung und der Laufwerk-Performance.



== Was muss ich vor dem Aktualisieren der Laufwerk-Firmware beachten?

Achten Sie vor dem Aktualisieren der Laufwerk-Firmware auf diese Elemente.

* Als Vorsichtsmaßnahme erstellen Sie Ihre Daten mittels Disk-to-Disk Backup, Volume-Kopie (in einer Volume-Gruppe, die nicht von der geplanten Firmware-Aktualisierung betroffen ist) oder einer Remote-Spiegelung.
* Möglicherweise möchten Sie nur einige wenige Laufwerke aktualisieren, um das Verhalten der neuen Firmware zu testen, um sicherzustellen, dass sie ordnungsgemäß funktioniert. Wenn die neue Firmware ordnungsgemäß funktioniert, aktualisieren Sie die verbleibenden Laufwerke.
* Wenn Laufwerke ausgefallen sind, beheben Sie sie, bevor Sie das Firmware-Upgrade starten.
* Wenn die Laufwerke offline aktualisiert werden können, stoppen Sie die I/O-Aktivität aller Volumes, die mit den Laufwerken verbunden sind. Wenn die I/O-Aktivität angehalten ist, können keine Konfigurationsvorgänge für diese Volumes durchgeführt werden.
* Entfernen Sie während des Upgrades der Laufwerk-Firmware keine Laufwerke.
* Nehmen Sie während des Upgrades der Laufwerk-Firmware keine Konfigurationsänderungen am Speicher-Array vor.




== Wie wähle ich die Art des Upgrades aus?

Je nach Status des Pools oder der Volume-Gruppe wählen Sie die Art des Upgrades, die auf dem Laufwerk ausgeführt werden soll.

* *Online*
+
Wenn der Pool oder die Volume-Gruppe Redundanz unterstützt und optimal ist, können Sie die Online-Methode verwenden, um die Festplatten-Firmware zu aktualisieren. Die Online-Methode lädt Firmware _herunter, während das Speicherarray I/O_ zu den zugehörigen Volumes verarbeitet, die diese Laufwerke verwenden. Sie müssen die I/O-Vorgänge für die zugehörigen Volumes, die diese Laufwerke verwenden, nicht anhalten. Diese Laufwerke werden nacheinander auf die Volumes aktualisiert, die mit den Laufwerken verbunden sind. Wenn das Laufwerk einem Pool oder einer Volume-Gruppe nicht zugewiesen ist, kann seine Firmware über die Online- oder Offline-Methode aktualisiert werden. Die Systemleistung kann beeinträchtigt werden, wenn Sie die Online-Methode zur Aktualisierung der Laufwerk-Firmware verwenden.

* *Offline*
+
Wenn der Pool oder die Volume-Gruppe keine Redundanz unterstützt (RAID 0) oder sich beeinträchtigt, müssen Sie die Offline-Methode verwenden, um die Laufwerk-Firmware zu aktualisieren. Die Offline-Methode führt ein Upgrade der Firmware _nur durch, während alle I/O-Aktivitäten zu den zugehörigen Volumes, die diese Laufwerke verwenden, angehalten werden. Sie müssen alle I/O-Vorgänge für alle zugehörigen Volumes beenden, die diese Laufwerke verwenden. Wenn das Laufwerk einem Pool oder einer Volume-Gruppe nicht zugewiesen ist, kann seine Firmware durch die Online- oder Offline-Methode aktualisiert werden.


