---
permalink: sm-support/how-do-i-choose-which-type-of-upgrade-to-perform.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, upgrade, perform 
summary: Je nach Status des Pools oder der Volume-Gruppe wählen Sie die Art des Upgrades, die auf dem Laufwerk ausgeführt werden soll. 
---
= Wie wähle ich die Art des Upgrades aus?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Je nach Status des Pools oder der Volume-Gruppe wählen Sie die Art des Upgrades, die auf dem Laufwerk ausgeführt werden soll.

* *Online*
+
Wenn der Pool oder die Volume-Gruppe Redundanz unterstützt und optimal ist, können Sie die Online-Methode verwenden, um die Festplatten-Firmware zu aktualisieren. Die Online-Methode lädt Firmware _herunter, während das Speicherarray I/O_ zu den zugehörigen Volumes verarbeitet, die diese Laufwerke verwenden. Sie müssen die I/O-Vorgänge für die zugehörigen Volumes, die diese Laufwerke verwenden, nicht anhalten. Diese Laufwerke werden nacheinander auf die Volumes aktualisiert, die mit den Laufwerken verbunden sind. Wenn das Laufwerk einem Pool oder einer Volume-Gruppe nicht zugewiesen ist, kann seine Firmware über die Online- oder Offline-Methode aktualisiert werden. Die Systemleistung kann beeinträchtigt werden, wenn Sie die Online-Methode zur Aktualisierung der Laufwerk-Firmware verwenden.

* *Offline*
+
Wenn der Pool oder die Volume-Gruppe keine Redundanz unterstützt (RAID 0) oder sich beeinträchtigt, müssen Sie die Offline-Methode verwenden, um die Laufwerk-Firmware zu aktualisieren. Die Offline-Methode führt ein Upgrade der Firmware _nur durch, während alle I/O-Aktivitäten zu den zugehörigen Volumes, die diese Laufwerke verwenden, angehalten werden. Sie müssen alle I/O-Vorgänge für alle zugehörigen Volumes beenden, die diese Laufwerke verwenden. Wenn das Laufwerk einem Pool oder einer Volume-Gruppe nicht zugewiesen ist, kann seine Firmware durch die Online- oder Offline-Methode aktualisiert werden.


