---
permalink: sm-support/overview-support.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, support, center 
summary: Nutzen Sie das Support Center, um Diagnose-, Recovery- und Informationserfassung durchzuführen, die vom technischen Support möglicherweise angefordert werden. 
---
= Support-Übersicht
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Auf der Seite Support erhalten Sie Zugriff auf die Ressourcen für den technischen Support.



== Welche Support-Aufgaben stehen zur Verfügung?

In Support können Sie Kontakte für den technischen Support anzeigen, Diagnosen durchführen, AutoSupport konfigurieren, das Ereignisprotokoll anzeigen und Software-Upgrades durchführen.

Weitere Informationen:

* link:autosupport-feature-overview.html["Übersicht über die Funktionen von AutoSupport"]
* link:overview-event-log.html["Übersicht über das Ereignisprotokoll"]
* link:overview-upgrade-center.html["Übersicht zum Upgrade Center"]




== Wie kann ich mich an den technischen Support wenden?

Klicken Sie auf der Hauptseite auf MENU:Support[Support Center > Registerkarte Support Resources]. Die Kontaktinformationen für den technischen Support finden Sie oben rechts auf der Schnittstelle.
