---
permalink: sm-support/what-do-the-autosupport-features-do.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, autosupport features, ASUP 
summary: Die AutoSupport Funktion besteht aus drei separaten Funktionen, die separat aktiviert werden können. 
---
= Was tun die AutoSupport-Funktionen?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die AutoSupport Funktion besteht aus drei separaten Funktionen, die separat aktiviert werden können.

* *Basic AutoSupport* -- ermöglicht Ihrem Speicherarray die automatische Erfassung und Übermittlung von Daten an den technischen Support.
* *AutoSupport OnDemand* -- ermöglicht technischen Support, bei Bedarf eine erneute Übertragung eines früheren AutoSupport Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob es noch ausstehende Neuübertragungsanfragen gibt und entsprechend darauf reagiert.
* *Ferndiagnose* -- ermöglicht technischen Support, bei Bedarf einen neuen, aktuellen AutoSupport-Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage-Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob ausstehende neue Anfragen zu bestehen und entsprechend darauf zu reagieren.

