---
permalink: sm-support/what-type-of-data-is-collected-through-autosupport.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, data, collected, autosupport, ASUP 
summary: 'Die AutoSupport-Funktion enthält drei standardmäßige Entsendungstypen: Ereignispatches, geplante Dispatches sowie On-Demand- und Remote-Diagnose-Patches.' 
---
= Welche Datentypen werden über die AutoSupport Funktion erfasst?
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die AutoSupport-Funktion enthält drei standardmäßige Entsendungstypen: Ereignispatches, geplante Dispatches sowie On-Demand- und Remote-Diagnose-Patches.

Die AutoSupport-Daten enthalten keine Benutzerdaten.

* *Event-Entsendungen*
+
Wenn Ereignisse auf dem System auftreten, die über proaktive Benachrichtigungen an den technischen Support verfügen, sendet die AutoSupport Funktion automatisch einen Event-ausgelösten Dispatch.

+
** Wird gesendet, wenn ein Support-Ereignis auf dem verwalteten Speicher-Array auftritt.
** In diesem Service wird eine umfassende Übersicht über die Ereignisse zum Zeitpunkt des Ereignisses des Storage-Arrays erstellt.


* *Geplante Entsendungen*
+
Die AutoSupport-Funktion sendet automatisch mehrere Entsendungen nach einem regelmäßigen Zeitplan.

+
** *Tägliche Dispatches* -- wird in einem vom Benutzer konfigurierbaren Zeitintervall einmal täglich gesendet. Enthält die aktuellen Systemereignisprotokolle und Performance-Daten.
** *Wöchentlich Dispatches* -- wird einmal wöchentlich in einem vom Benutzer konfigurierbaren Zeitintervall und Tag gesendet. Einschließlich Konfigurations- und Systemstatus-Informationen.


* *AutoSupport OnDemand und Remote Diagnostics Dispatches*
+
** *AutoSupport OnDemand* -- ermöglicht technischen Support, bei Bedarf eine erneute Übertragung eines früheren AutoSupport Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob es noch ausstehende Neuübertragungsanfragen gibt und entsprechend darauf reagiert.
** *Ferndiagnose* -- ermöglicht technischen Support, bei Bedarf einen neuen, aktuellen AutoSupport-Dispatch zur Fehlerbehebung anzufordern. Sämtliche Übertragungen werden vom Storage Array aus initiiert, nicht vom AutoSupport Server. Das Storage-Array überprüft in regelmäßigen Abständen mit dem AutoSupport Server, um zu ermitteln, ob ausstehende neue Anfragen zu bestehen und entsprechend darauf zu reagieren.



