---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Auf SANtricity kann über verschiedene Browsertypen und Betriebssysteme zugegriffen werden. 
---
= Unterstützte Browser und Betriebssysteme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity unterstützt verschiedene Arten von Browsern und Betriebssystemen.



== Browser

Die folgenden Browser und Versionen werden unterstützt.

[cols="1a,1a"]
|===
| Browser | Mindestversion 


 a| 
Google Chrome
 a| 
79



 a| 
Mozilla Firefox
 a| 
70



 a| 
Safari
 a| 
12



 a| 
Microsoft Edge
 a| 
79



 a| 
Microsoft Edge Legacy
 a| 
18



 a| 
Microsoft Internet Explorer (MSIE)
 a| 
11

|===
[NOTE]
====
Für Unified Manager muss der Web Services Proxy installiert und dem Browser zur Verfügung stehen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["SANtricity Web Services Proxy: Überblick"^]

====


== Betriebssysteme

Die folgenden Betriebssysteme und Versionen werden unterstützt.

[cols="1a,1a"]
|===
| Betriebssystem | Mindestversion/Architektur 


 a| 
Red hat Enterprise Linux (RHEL)
 a| 
7.x, 8.x / 64-Bit



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
12.x, 15.x / 64-Bit



 a| 
Oracle Linux (OL)
 a| 
7.x, 8.x / 64-Bit



 a| 
Windows Server
 a| 
2016, 2019, 2022/64-Bit



 a| 
Ubuntu
 a| 
18.04, 20.04/64-Bit

|===