---
permalink: san-getstarted/supported-browsers-os.html 
sidebar: sidebar 
keywords: SANtricity, System Manager, E-Series, 
summary: Auf SANtricity kann über verschiedene Browsertypen und Betriebssysteme zugegriffen werden. 
---
= Browser- und Betriebssystemunterstützung der SANtricity-Software
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity unterstützt verschiedene Arten von Browsern und Betriebssystemen.



== Browser

Die folgenden Browser und Versionen werden unterstützt.

[cols="1a,1a"]
|===
| Browser | Mindestversion 


 a| 
Google Chrome
 a| 
89



 a| 
Mozilla Firefox
 a| 
80



 a| 
Safari
 a| 
14



 a| 
Microsoft Edge
 a| 
90

|===
[NOTE]
====
Für Unified Manager muss der Web Services Proxy installiert und dem Browser zur Verfügung stehen. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/e-series/web-services-proxy/index.html["SANtricity Web Services Proxy: Überblick"^]

====


== Betriebssysteme

Die folgenden Betriebssysteme und Versionen werden unterstützt.

[cols="1a,1a"]
|===
| Betriebssystem | Mindestversion/Architektur 


 a| 
Red hat Enterprise Linux (RHEL)
 a| 
8.x (SP8)、9.x (SP2)/64 位



 a| 
SUSE Linux Enterprise Server (SLES)
 a| 
12.x (SP4、SP5)、15.x (SP4、SP5)/64 位



 a| 
Oracle Linux (OL)
 a| 
8.x (U8)、9.x (U2)/64 位



 a| 
Windows Server
 a| 
2019、2022、2025/64位



 a| 
Ubuntu
 a| 
20.04、22.04/64位

|===