---
permalink: um-certificates/access-management-with-local-user-roles-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, access management, local, user, roles 
summary: 'Administratoren können die in SANtricity Unified Manager erzwungenen RBAC-Funktionen (rollenbasierte Zugriffssteuerung) nutzen. Diese Funktionen werden als lokale Benutzerrollen bezeichnet.' 
---
= Zugriffsverwaltung mit lokalen Benutzerrollen im SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Administratoren können die in SANtricity Unified Manager erzwungenen RBAC-Funktionen (rollenbasierte Zugriffssteuerung) nutzen. Diese Funktionen werden als „lokale Benutzerrollen“ bezeichnet.



== Konfigurationsworkflow

Lokale Benutzerrollen sind im System vorkonfiguriert. Um lokale Benutzerrollen für die Authentifizierung zu verwenden, können Administratoren Folgendes tun:

. Ein Administrator meldet sich bei Unified Manager mit einem Benutzerprofil an, das die Berechtigungen für Sicherheitsadministratoren enthält.
+
[NOTE]
====
Der `admin` Der Benutzer hat vollen Zugriff auf alle Funktionen im System.

====
. Ein Administrator überprüft die Benutzerprofile, die vordefiniert sind und nicht geändert werden können.
. Optional weist der Administrator jedem Benutzerprofil neue Passwörter zu.
. Benutzer melden sich mit ihren zugewiesenen Anmeldedaten am System an.




== Vereinfachtes

Bei der Verwendung von nur lokalen Benutzerrollen für die Authentifizierung können Administratoren die folgenden Verwaltungsaufgaben ausführen:

* Passwörter ändern.
* Legen Sie eine Mindestlänge für Passwörter fest.
* Benutzern erlauben, sich ohne Passwörter anzumelden.

