---
permalink: um-certificates/change-passwords-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, passwords 
summary: Sie können die Benutzerpasswörter für jeden Benutzer in der Zugriffsverwaltung ändern. 
---
= Passwörter für lokale Benutzerprofile ändern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Benutzerpasswörter für jeden Benutzer in der Zugriffsverwaltung ändern.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, der Root-Admin-Berechtigungen enthält.
* Sie müssen das lokale Administratorkennwort kennen.


.Über diese Aufgabe
Beachten Sie bei der Auswahl eines Passworts die folgenden Richtlinien:

* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Einstellung für ein Mindestpasswort erfüllen oder überschreiten (unter „Einstellungen anzeigen/bearbeiten“).
* Bei Passwörtern wird die Groß-/Kleinschreibung berücksichtigt.
* Nachgestellte Leerzeichen werden nicht aus Kennwörtern entfernt, wenn sie gesetzt sind. Achten Sie darauf, Leerzeichen einzugeben, wenn diese im Passwort enthalten waren.
* Um die Sicherheit zu erhöhen, verwenden Sie mindestens 15 alphanumerische Zeichen, und ändern Sie das Passwort häufig.


.Schritte
. Wählen Sie *Zugriffsmanagement*.
. Wählen Sie die Registerkarte * Lokale Benutzerrollen* aus.
. Wählen Sie einen Benutzer aus der Tabelle aus.
+
Die Schaltfläche Kennwort ändern steht zur Verfügung.

. Wählen Sie *Passwort Ändern*.
+
Das Dialogfeld Kennwort ändern wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestkennwortlänge festgelegt ist, können Sie das Kontrollkästchen aktivieren, damit der Benutzer ein Passwort für den Zugriff auf das System eingeben muss.
. Geben Sie das neue Kennwort für den ausgewählten Benutzer in die beiden Felder ein.
. Geben Sie Ihr lokales Administratorpasswort ein, um diesen Vorgang zu bestätigen, und klicken Sie dann auf *Ändern*.


.Ergebnisse
Wenn der Benutzer derzeit angemeldet ist, wird die aktive Sitzung des Benutzers durch die Kennwortänderung beendet.
