---
permalink: um-certificates/change-local-user-passwords-settings-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, local, user, password, settings 
summary: Sie können die erforderliche Mindestlänge für alle neuen oder aktualisierten lokalen Benutzerpasswörter festlegen. Außerdem können lokale Benutzer ohne Eingabe eines Kennworts auf das System zugreifen. 
---
= Ändern Sie die Einstellungen für das lokale Benutzerpasswort
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die erforderliche Mindestlänge für alle neuen oder aktualisierten lokalen Benutzerpasswörter festlegen. Außerdem können lokale Benutzer ohne Eingabe eines Kennworts auf das System zugreifen.

Sie müssen als lokaler Administrator angemeldet sein, der Root-Admin-Berechtigungen enthält.

Beachten Sie die folgenden Richtlinien, wenn Sie die Mindestlänge für lokale Benutzerpasswörter festlegen:

* Die Einstellung von Änderungen hat keine Auswirkung auf vorhandene lokale Benutzerpasswörter.
* Die Mindestlänge für lokale Benutzerpasswörter muss zwischen 0 und 30 Zeichen liegen.
* Alle neuen lokalen Benutzerpasswörter müssen die aktuelle Mindestlängeneinstellung erfüllen oder überschreiten.
* Legen Sie keine Mindestlänge für das Passwort fest, wenn lokale Benutzer ohne Eingabe eines Kennworts auf das System zugreifen möchten.


.Schritte
. Wählen Sie *Zugriffsmanagement*.
. Wählen Sie die Registerkarte * Lokale Benutzerrollen* aus.
. Wählen Sie *Einstellungen Anzeigen/Bearbeiten*.
+
Das Dialogfeld Einstellungen für das lokale Benutzerpasswort wird geöffnet.

. Führen Sie einen der folgenden Schritte aus:
+
** Um lokalen Benutzern den Zugriff auf das System zu ermöglichen _ohne_ ein Passwort einzugeben, deaktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens sein“.
** Um eine Mindestkennwortlänge für alle lokalen Benutzerpasswörter festzulegen, aktivieren Sie das Kontrollkästchen „Alle lokalen Benutzerpasswörter müssen mindestens sein“. Verwenden Sie dann das Spinner-Feld, um die erforderliche Mindestlänge für alle lokalen Benutzerpasswörter festzulegen.
+
Neue lokale Benutzerpasswörter müssen die aktuelle Einstellung erfüllen oder überschreiten.



. Klicken Sie Auf *Speichern*.

