---
permalink: um-certificates/export-certificates-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, export, certificates 
summary: Sie können ein Zertifikat exportieren, um die vollständigen Details anzuzeigen. 
---
= Exportieren von Zertifikaten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Zertifikat exportieren, um die vollständigen Details anzuzeigen.

Um die exportierte Datei zu öffnen, müssen Sie über eine Zertifikatanzeige-Anwendung verfügen.

.Schritte
. Wählen Sie *Zertifikatverwaltung*.
. Wählen Sie eine der folgenden Registerkarten aus:
+
** *Management* -- zeigt das Zertifikat für das System, das den Web Services Proxy hostet. Ein Managementzertifikat kann von einer Zertifizierungsstelle (CA) selbst signiert oder genehmigt werden. Die Lösung ermöglicht den sicheren Zugriff auf Unified Manager.
** *Trusted* -- zeigt Zertifikate an, auf die Unified Manager für Speicher-Arrays und andere Remote-Server, z. B. einen LDAP-Server, zugreifen kann. Die Zertifikate können von einer Zertifizierungsstelle (CA) ausgestellt oder selbst signiert werden.


. Wählen Sie auf der Seite ein Zertifikat aus, und klicken Sie dann am Ende der Zeile auf die Ellipsen.
. Klicken Sie auf *Exportieren* und speichern Sie dann die Zertifikatdatei.
. Öffnen Sie die Datei in Ihrer Zertifikatanzeige-Anwendung.

