---
permalink: um-certificates/resolve-untrusted-certificates-certificate-page.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, resolve, untrusted, certificates 
summary: Nicht vertrauenswürdige Zertifikate treten auf, wenn ein Speicher-Array versucht, eine sichere Verbindung zu SANtricity Unified Manager herzustellen, die Verbindung jedoch nicht als sicher bestätigt. 
---
= Lösen Sie nicht vertrauenswürdige Zertifikate
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nicht vertrauenswürdige Zertifikate treten auf, wenn ein Speicher-Array versucht, eine sichere Verbindung zu Unified Manager herzustellen, die Verbindung jedoch nicht als sicher bestätigt werden kann.

Auf der Zertifikatsseite können Sie nicht vertrauenswürdige Zertifikate auflösen, indem Sie ein selbstsigniertes Zertifikat aus dem Speicher-Array importieren oder ein Zertifikat der Zertifizierungsstelle importieren, das von einem vertrauenswürdigen Dritten ausgestellt wurde.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das die Berechtigungen für den Sicherheitsadministrator enthält.
* Wenn Sie ein von einer Zertifizierungsstelle signiertes Zertifikat importieren möchten:
+
** Sie haben für jeden Controller im Speicher-Array eine Zertifikatsignierungsanforderung (.CSR-Datei) generiert und an die CA gesendet.
** Die CA hat vertrauenswürdige Zertifikatdateien zurückgegeben.
** Die Zertifikatdateien sind auf Ihrem lokalen System verfügbar.




.Über diese Aufgabe
Möglicherweise müssen Sie zusätzliche vertrauenswürdige CA-Zertifikate installieren, wenn eine der folgenden Optionen zutrifft:

* Sie haben kürzlich ein Speicher-Array hinzugefügt.
* Ein oder beide Zertifikate sind abgelaufen.
* Ein oder beide Zertifikate werden widerrufen.
* Ein oder beide Zertifikate fehlen ein Stammzertifikat oder ein Zwischenzertifikat.


.Schritte
. Wählen Sie *Zertifikatverwaltung*.
. Wählen Sie die Registerkarte * Trusted* aus.
+
Auf dieser Seite werden alle Zertifikate angezeigt, die für die Speicher-Arrays gemeldet wurden.

. Wählen Sie entweder Menü:Import[Certificates], um ein CA-Zertifikat oder Menü zu importieren:Importieren[Self-signierte Speicher-Array-Zertifikate], um ein selbstsigniertes Zertifikat zu importieren.
+
Um die Ansicht einzuschränken, können Sie das Filterfeld *Zertifikate anzeigen verwenden, das...* ist, oder Sie können die Zertifikatzeilen sortieren, indem Sie auf eine der Spaltenüberschrift klicken.

. Wählen Sie im Dialogfeld das Zertifikat aus und klicken Sie dann auf *Import*.
+
Das Zertifikat wird hochgeladen und validiert.


