---
permalink: um-admin/administrator-password-protection-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, administrator, password, protection 
summary: Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unbefugtem Zugriff zu schützen. 
---
= Erfahren Sie mehr über den Administratorkennwortschutz im SANtricity Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie müssen SANtricity Unified Manager mit einem Administratorkennwort konfigurieren, um ihn vor unbefugtem Zugriff zu schützen.



== Admin-Passwort und Benutzerprofile

Wenn Sie Unified Manager zum ersten Mal starten, werden Sie aufgefordert, ein Administratorpasswort festzulegen. Jeder Benutzer mit dem Admin-Passwort kann Konfigurationsänderungen an den Speicher-Arrays vornehmen.

Zusätzlich zum Admin-Passwort enthält die Unified Manager-Schnittstelle vorkonfigurierte Benutzerprofile mit einer oder mehreren Rollen, die ihnen zugeordnet sind. Weitere Informationen finden Sie unter link:../um-certificates/how-access-management-works-unified.html["Funktionsweise von Access Management"].

Die Benutzer und Zuordnungen können nicht geändert werden. Es können nur Passwörter geändert werden. Informationen zum Ändern von Passwörtern finden Sie unter:

* link:change-admin-password-unified.html["Ändern Sie das Admin-Passwort"]
* link:../um-certificates/change-passwords-unified.html["Passwörter für lokale Benutzerprofile ändern"]




== Session-Timeouts

Die Software fordert Sie zur Eingabe des Passworts nur einmal während einer einzigen Verwaltungssitzung auf. Eine Sitzung läuft nach 30 Minuten Inaktivität standardmäßig aus. Zu diesem Zeitpunkt müssen Sie das Passwort erneut eingeben. Wenn ein anderer Benutzer von einem anderen Management-Client auf die Software zugreift und das Passwort während der Sitzung ändert, werden Sie beim nächsten Versuch eines Konfigurationsvorgangs oder einer Ansicht aufgefordert, ein Passwort einzugeben.

Aus Sicherheitsgründen können Sie versuchen, ein Passwort nur fünf Mal einzugeben, bevor die Software den Status „Sperre“ eingibt. In diesem Zustand lehnt die Software nachfolgende Passwortversuche ab. Sie müssen 10 Minuten warten, um den Status „Normal“ zurückzusetzen, bevor Sie erneut versuchen, ein Passwort einzugeben.

Sie können Sitzungszeitausfälle anpassen oder Sitzungszeitausfälle komplett deaktivieren. Weitere Informationen finden Sie unter link:manage-session-timeouts-unified.html["Verwalten von Sitzungszeitungen"].
