---
permalink: um-admin/change-storage-array-passwords.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, storage, array, passwords 
summary: Sie können die Passwörter aktualisieren, die für die Anzeige und den Zugriff auf Speicher-Arrays in SANtricity Unified Manager verwendet werden. 
---
= Ändern Sie die Passwörter für das Speicherarray
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die Passwörter aktualisieren, die für die Anzeige und den Zugriff auf Speicher-Arrays in Unified Manager verwendet werden.

.Bevor Sie beginnen
* Sie müssen mit einem Benutzerprofil angemeldet sein, das Storage Admin-Berechtigungen enthält.
* Sie müssen das aktuelle Passwort für das Speicher-Array kennen, das in System Manager festgelegt ist.


In dieser Aufgabe geben Sie das aktuelle Passwort für ein Speicher-Array ein, damit Sie in Unified Manager darauf zugreifen können. Dies kann notwendig sein, wenn das Array-Passwort in System Manager geändert wurde und jetzt auch in Unified Manager geändert werden muss.

.Schritte
. Wählen Sie auf der Seite Verwalten ein oder mehrere Speicher-Arrays aus.
. Menü wählen:Sonstige Aufgaben[Storage Array-Passwörter angeben].
. Geben Sie für jedes Speicherarray das Kennwort oder die Passwörter ein, und klicken Sie dann auf *Speichern*.

