---
permalink: um-admin/change-admin-password-unified.html 
sidebar: sidebar 
keywords: SANtricity, Unified Manager, E-Series, change, admin, password 
summary: Sie können das Admin-Passwort ändern, das für den Zugriff auf SANtricity Unified Manager verwendet wird. 
---
= Ändern Sie das Admin-Passwort
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können das Admin-Passwort ändern, das für den Zugriff auf SANtricity Unified Manager verwendet wird.

.Bevor Sie beginnen
* Sie müssen als lokaler Administrator angemeldet sein, der Root-Admin-Berechtigungen enthält.
* Sie müssen das aktuelle Admin-Passwort kennen.


.Über diese Aufgabe
Beachten Sie bei der Auswahl eines Passworts die folgenden Richtlinien:

* Bei Passwörtern wird die Groß-/Kleinschreibung berücksichtigt.
* Nachgestellte Leerzeichen werden nicht aus Kennwörtern entfernt, wenn sie gesetzt sind. Achten Sie darauf, Leerzeichen einzugeben, wenn diese im Passwort enthalten waren.
* Um die Sicherheit zu erhöhen, verwenden Sie mindestens 15 alphanumerische Zeichen, und ändern Sie das Passwort häufig.


.Schritte
. Wählen Sie Menü:Einstellungen[Zugriffsverwaltung].
. Wählen Sie die Registerkarte * Lokale Benutzerrollen* aus.
. Wählen Sie den *admin*-Benutzer aus der Tabelle aus.
+
Die Schaltfläche Kennwort ändern steht zur Verfügung.

. Wählen Sie *Passwort Ändern*.
+
Das Dialogfeld Kennwort ändern wird geöffnet.

. Wenn für lokale Benutzerpasswörter keine Mindestkennwortlänge festgelegt ist, aktivieren Sie das Kontrollkästchen, damit der Benutzer ein Kennwort für den Zugriff auf das System eingeben muss.
. Geben Sie das neue Passwort in die beiden Felder ein.
. Geben Sie Ihr lokales Administratorpasswort ein, um diesen Vorgang zu bestätigen, und klicken Sie dann auf *Ändern*.

